"""Building max-level tooltips: one clean, labelled row per term.

EU5 1.4 draws a building's maximum level (``max_levels = <script value>``) as a breakdown, one row per operation.
Measured in game on 2026-10-03 (Cookshop and farm cap probes, memory "script value tooltip rows"):

- every top-level operation is a row showing its change to the running total; with a ``desc`` it shows the label,
  without one "missing key" and 0.00;
- inside a described block EVERY operation after the first ``value =`` is a sub-row (``multiply``, ``max``, ``floor``
  ...), and so are the operations of a script value it names directly (``value = some_value`` flattens it); an
  unlabelled sub-row shows "missing key", a labelled one its own change, nesting deeper does not hide anything;
- a script value read through a scope link (``value = this.some_value``, also ``root.`` / ``province.``) is ONE
  atomic number: no sub-rows, whatever it computes inside (``floor = yes`` included).

So a clean row is a described block whose value is a single atom: a number, a game value (``development``),
``modifier:<type>``, a variable, a define, or ``this.<helper>``. ``problems`` lists every step that breaks this, per
script value used as a building's max level over the load order (vanilla buildings included). ``apply`` fixes them
in place without changing any number: each described row with steps keeps its label and reads ``this.<helper>``,
and the helper (the row's original steps) is written right after its cap. Caps defined only in vanilla get a fixed
``REPLACE:`` copy in ``VANILLA_OUTPUT``. The farm caps are written clean by scripts/generate_rural_capacity_values.py
(farmland for this farm minus the land other farms use, in levels).
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from eu5gameparser.clausewitz.parser import parse_file, parse_text
from eu5gameparser.clausewitz.syntax import CEntry, CList

OPERATIONS = {"value", "add", "subtract", "multiply", "divide", "min", "max", "modulo", "round", "floor", "ceiling",
              "abs", "square_root", "fixed_range", "integer_range", "round_to"}
BRANCHES = {"if", "else_if", "else"}
PREFIXES = ("REPLACE:", "TRY_REPLACE:", "INJECT:", "TRY_INJECT:", "REPLACE_OR_CREATE:", "INJECT_OR_CREATE:")
SCOPE_LINKS = ("this.", "root.", "province.", "owner.", "scope:")
SCRIPT_VALUES = Path("in_game/common/script_values")
VANILLA_OUTPUT = SCRIPT_VALUES / "zz_pp_cap_tooltips_vanilla.txt"
HEADER = ("# Generated by ppc build (cap_tooltips.py): vanilla max-level caps with one clean tooltip row per term (the same\n"
          "# numbers; each multi-step row reads a helper through this.). Do not edit by hand.\n")


@dataclass(frozen=True)
class Problem:
    script_value: str
    buildings: tuple[str, ...]
    path: str
    message: str

    def __str__(self) -> str:
        more = "..." if len(self.buildings) > 3 else ""
        return f"{self.script_value} ({', '.join(self.buildings[:3])}{more}): {self.message}"


def game_root(vanilla_root: Path) -> Path:
    """The folder that holds in_game/ (the load order's vanilla_root points one level above it)."""
    return vanilla_root / "game" if (vanilla_root / "game" / "in_game").is_dir() else vanilla_root


def _strip(key: str) -> tuple[str, str]:
    for prefix in PREFIXES:
        if key.startswith(prefix):
            return prefix, key[len(prefix):]
    return "", key


def _files(root: Path, rel: str) -> list[Path]:
    folder = root / rel
    return sorted(folder.glob("*.txt")) if folder.is_dir() else []


def load_script_values(roots: list[Path], *, skip: tuple[Path, ...] = ()) -> dict[str, tuple[CList, str]]:
    """Script values by name over the load order (later roots replace earlier definitions); skip: files left out."""
    out: dict[str, tuple[CList, str]] = {}
    skipped = {s.resolve() for s in skip}
    for root in roots:
        for path in _files(root, str(SCRIPT_VALUES)):
            if path.resolve() in skipped:
                continue
            document = parse_file(path)
            if document is None:
                continue
            for entry in document.entries:
                prefix, name = _strip(entry.key)
                if isinstance(entry.value, CList) and prefix not in ("INJECT:", "TRY_INJECT:"):
                    out[name] = (entry.value, str(path))
    return out


def load_max_levels(roots: list[Path]) -> dict[str, str]:
    """Building -> max_levels value (a script value name or a number) over the load order."""
    out: dict[str, str] = {}
    for root in roots:
        for path in _files(root, "in_game/common/building_types"):
            document = parse_file(path)
            if document is None:
                continue
            for entry in document.entries:
                prefix, name = _strip(entry.key)
                if not isinstance(entry.value, CList):
                    continue
                value = entry.value.first("max_levels")
                if value is not None and not isinstance(value, CList):
                    out[name] = str(value)
                elif prefix in ("REPLACE:", "TRY_REPLACE:") and name in out:
                    del out[name]
    return out


def _name(value: object) -> str:
    return str(value).strip('"')


class _Walker:
    """Walks the tooltip rows of a cap the way the game draws them."""

    def __init__(self, script_values: dict[str, tuple[CList, str]]):
        self.script_values = script_values

    def is_reference(self, value: object) -> bool:
        return not isinstance(value, CList) and _name(value) in self.script_values

    def is_atom(self, value: object) -> bool:
        if isinstance(value, CList):
            return False
        return _name(value).startswith(SCOPE_LINKS) or not self.is_reference(value)

    def clean_row(self, block: CList) -> bool:
        ops = [e for e in block.entries if e.key in OPERATIONS or e.key in BRANCHES]
        return not ops or (len(ops) == 1 and ops[0].key == "value" and self.is_atom(ops[0].value))

    def rows(self, block: CList, flattened: list[str]):
        """Yield (entry, problem or None) for every row-drawing operation at this level; names this level flattens
        (``value = name`` first, or an unlabelled ``add = name``) go to ``flattened``."""
        for index, entry in enumerate(block.entries):
            key = entry.key
            if key in BRANCHES:
                if isinstance(entry.value, CList):
                    yield from self.rows(CList([e for e in entry.value.entries if e.key != "limit"]), flattened)
                continue
            if key not in OPERATIONS:
                continue
            if not isinstance(entry.value, CList):
                if key == "value" and index == 0 and self.is_atom(entry.value):
                    continue   # the level's starting value: no row
                if key in ("value", "add") and self.is_reference(entry.value):
                    flattened.append(_name(entry.value))   # the named value's rows show at this level
                    continue
                yield entry, f"`{key} = {entry.value}` has no desc (a 'missing key' row)"
                continue
            if entry.value.first("desc") is None:
                yield entry, f"`{key} = {{...}}` has no desc (a 'missing key' row)"
                continue
            if self.clean_row(entry.value):
                yield entry, None
            else:
                steps = [e.key for e in entry.value.entries if e.key not in ("desc",)]
                yield entry, f"row {entry.value.first('desc')} has sub-steps {steps} (each draws a sub-row)"


def problems(roots: list[Path]) -> list[Problem]:
    """Every max-level script value step that draws an unwanted row, over the load order ``roots`` (vanilla first)."""
    script_values = load_script_values(roots)
    users: dict[str, list[str]] = {}
    for building, value in load_max_levels(roots).items():
        if _name(value) in script_values:
            users.setdefault(_name(value), []).append(building)
    walker = _Walker(script_values)
    out: list[Problem] = []
    queue = sorted(users)
    seen: set[str] = set()
    while queue:
        name = queue.pop(0)
        if name in seen:
            continue
        seen.add(name)
        block, path = script_values[name]
        flattened: list[str] = []
        for _, message in walker.rows(block, flattened):
            if message:
                out.append(Problem(name, tuple(sorted(users.get(name, ("(via another cap)",)))), path, message))
        queue += [n for n in flattened if n not in seen]
    return out


# ---- fixing ---------------------------------------------------------------------------------------------------------

def _line_offsets(text: str) -> list[int]:
    offsets = [0]
    for index, char in enumerate(text):
        if char == "\n":
            offsets.append(index + 1)
    return offsets


def _offset(offsets: list[int], entry: CEntry) -> int:
    return offsets[entry.location.line - 1] + entry.location.column - 1


def _block_span(text: str, start: int) -> tuple[int, int]:
    """(index of the opening brace, index of its closing brace) of the block that starts at ``start``."""
    open_index = text.index("{", start)
    depth, index, in_string = 0, open_index, False
    while index < len(text):
        char = text[index]
        if in_string:
            if char == '"':
                in_string = False
        elif char == '"':
            in_string = True
        elif char == "#":
            index = text.index("\n", index) if "\n" in text[index:] else len(text)
            continue
        elif char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return open_index, index
        index += 1
    raise ValueError("unclosed block")


def _scalar_end(text: str, start: int) -> int:
    """End index of the scalar entry ``key = value`` that starts at ``start``."""
    index = text.index("=", start) + 1
    while text[index] in " \t":
        index += 1
    if text[index] == '"':
        return text.index('"', index + 1) + 1
    match = re.compile(r"[^\s{}#]+").match(text, index)
    return match.end()


def _dedent(body: str) -> str:
    """A row's steps as a helper body: blank lines dropped, one tab of indent."""
    lines = [line.rstrip() for line in body.splitlines() if line.strip()]
    pad = min((len(line) - len(line.lstrip()) for line in lines), default=0)
    return "\n".join("\t" + line[pad:] for line in lines)


def _slug(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", str(text).lower()).strip("_")
    return slug[:40] or "row"


def fix_text(text: str, names: set[str], script_values: dict[str, tuple[CList, str]]) -> tuple[str, int]:
    """Rewrite the caps ``names`` defined in ``text`` so every described row with steps reads ``this.<helper>``;
    each helper (the row's steps, its desc dropped) follows its cap. Returns (text, rows fixed). Numbers are unchanged:
    the helper runs the same operations from 0, which is what the row did."""
    document = parse_text(text)
    walker = _Walker(script_values)
    offsets = _line_offsets(text)
    edits: list[tuple[int, int, str]] = []
    taken = {_strip(e.key)[1] for e in document.entries}
    fixed = 0
    for top in document.entries:
        cap = _strip(top.key)[1]
        if cap not in names or not isinstance(top.value, CList):
            continue
        helpers: list[str] = []
        for entry, problem in walker.rows(top.value, []):
            if problem is None or not isinstance(entry.value, CList) or entry.value.first("desc") is None:
                continue
            open_index, close_index = _block_span(text, _offset(offsets, entry))
            desc_entry = next(e for e in entry.value.entries if e.key == "desc")
            desc_start = _offset(offsets, desc_entry)
            desc_end = _scalar_end(text, desc_start)
            helper = f"{cap}_{_slug(desc_entry.value)}"
            n = 2
            while helper in taken or helper in script_values:
                helper, n = f"{cap}_{_slug(desc_entry.value)}_{n}", n + 1
            taken.add(helper)
            body = _dedent(text[open_index + 1:desc_start] + text[desc_end:close_index])
            helpers.append(f"{helper} = {{\n{body}\n}}")
            indent = re.match(r"[ \t]*", text[offsets[entry.location.line - 1]:]).group(0)
            edits.append((open_index + 1, close_index,
                          f"\n{indent}\t{text[desc_start:desc_end]}\n{indent}\tvalue = this.{helper}\n{indent}"))
            fixed += 1
        if helpers:
            _, cap_close = _block_span(text, _offset(offsets, top))
            note = f"\n\n# Tooltip helpers of {cap} (cap_tooltips.py): each is one row of the cap, read through this.\n"
            edits.append((cap_close + 1, cap_close + 1, note + "\n\n".join(helpers)))
    for start, end, new in sorted(edits, key=lambda e: e[0], reverse=True):
        text = text[:start] + new + text[end:]
    return text, fixed


def _targets(roots: list[Path], skip: tuple[Path, ...]) -> tuple[set[str], dict[str, tuple[CList, str]]]:
    """Every script value whose rows a building's max-level tooltip draws (caps and the values they flatten)."""
    script_values = load_script_values(roots, skip=skip)
    walker = _Walker(script_values)
    queue = sorted({_name(v) for v in load_max_levels(roots).values() if _name(v) in script_values})
    seen: set[str] = set()
    while queue:
        name = queue.pop(0)
        if name in seen:
            continue
        seen.add(name)
        flattened: list[str] = []
        list(walker.rows(script_values[name][0], flattened))
        queue += [n for n in flattened if n not in seen]
    return seen, script_values


@dataclass(frozen=True)
class FixResult:
    changed: tuple[str, ...]   # files (relative to the mod root) that changed or would change
    rows_fixed: int


def apply(mod_root: Path, vanilla_root: Path, *, write: bool = True) -> FixResult:
    """Fix every max-level tooltip row of the mod's script values in place, and write fixed REPLACE copies of the
    caps defined only in vanilla to VANILLA_OUTPUT (rebuilt from vanilla every time). Idempotent."""
    output = mod_root / VANILLA_OUTPUT
    vanilla_root = game_root(vanilla_root)
    names, script_values = _targets([vanilla_root, mod_root], skip=(output,))
    mod_dir = (mod_root / SCRIPT_VALUES).resolve()
    by_file: dict[Path, set[str]] = {}
    for name in names:
        by_file.setdefault(Path(script_values[name][1]).resolve(), set()).add(name)
    changed: list[str] = []
    rows = 0
    copies: list[str] = []
    for path, file_names in sorted(by_file.items()):
        text = path.read_text(encoding="utf-8-sig")
        if path.parent == mod_dir:
            new, fixed = fix_text(text, file_names, script_values)
            if fixed:
                rows += fixed
                changed.append(str(SCRIPT_VALUES / path.name))
                if write:
                    path.write_text("\ufeff" + new, encoding="utf-8")
            continue
        # defined only in vanilla: a REPLACE copy of the cap, fixed
        document = parse_text(text)
        offsets = _line_offsets(text)
        for top in document.entries:
            if top.key not in file_names or not isinstance(top.value, CList):
                continue
            start = _offset(offsets, top)
            _, close = _block_span(text, start)
            fixed_copy, fixed = fix_text(text[start:close + 1], {top.key}, script_values)
            if fixed:
                rows += fixed
                copies.append("REPLACE:" + fixed_copy.strip("\n"))
    new_output = HEADER + "\n" + "\n\n".join(sorted(copies)) + "\n" if copies else None
    previous = output.read_text(encoding="utf-8-sig") if output.is_file() else None
    if new_output != previous:
        changed.append(str(VANILLA_OUTPUT))
        if write:
            if new_output is None:
                output.unlink()
            else:
                output.parent.mkdir(parents=True, exist_ok=True)
                output.write_text("\ufeff" + new_output, encoding="utf-8")
    return FixResult(tuple(changed), rows)
