"""Keep ``debug_max_profit`` equal to each production method's base-price profit (finalize step).

At load the engine checks each production method that produces a good at the goods' ``default_market_price``:
profit = output value / input cost - 1 (verified against all 618 logged methods, 2026-09-23). A method with
``debug_max_profit`` must lie within 1 % of it ("should be 20.00% +-1%"), one without it must not lose money
("should be at least 0.00%"). A negative target counts as none: the game start of 2026-09-23 still flagged all
488 methods given their negative profit, so a method that loses money at base prices can only be silenced by
making it profitable at base prices. The mod reprices goods and pays labour, so vanilla's
targets no longer hold and error.log listed ~620 methods per start. The value is a debug target only; gameplay
does not read it.

- The mod's own methods: the key is set (idempotently, in place) wherever a method carries one or would be flagged.
- Vanilla's shared methods (common/production_methods) the mod leaves alone and the engine would flag: a
  ``TRY_REPLACE`` copy with the key goes to ``GENERATED_PATH``, which loads last.
- Vanilla's unique methods of buildings the mod REPLACEs stay registered and checked by the engine, but only a
  same-named copy of the vanilla building file could change them, and such a copy loads with the mod's files,
  after the mod's REPLACEs, and would undo them. They are counted, not changed.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from eu5gameparser.clausewitz.syntax import CList
from eu5gameparser.load_order import load_merged_directory, load_profile

from prosper_or_perish_constructor.building_footprint import _brace_pairs, _depth_zero_opens

BUILDING_TYPES = Path("in_game/common/building_types")
PRODUCTION_METHODS = Path("in_game/common/production_methods")
GENERATED_PATH = PRODUCTION_METHODS / "zz_pp_profit_margins.txt"
GENERATED_HEADER = (
    "# Generated by ppc (profit_margins.py): vanilla shared production methods with debug_max_profit set to "
    "their base-price profit, so the engine's load check stays quiet. Do not edit.\n"
)
TOLERANCE = 0.01   # the engine accepts +-1 %
NON_INPUTS = {"produced", "output", "category", "debug_max_profit", "potential", "allow", "no_upkeep"}
_ENTRY_RE = re.compile(r"(?:(?P<mode>[A-Z_]+):)?(?P<key>[A-Za-z_0-9]+)\s*=\s*(?P<value>\{|[^\s{}#]+)")
_DEBUG_RE = re.compile(r"(?<![\w])debug_max_profit\s*=\s*[^\s{}#]+")


@dataclass
class ProfitResult:
    methods_written: int = 0
    files_changed: int = 0
    vanilla_replaced: list[str] = field(default_factory=list)
    vanilla_unchanged: list[str] = field(default_factory=list)   # flagged: replaced buildings' unique methods, losing ones
    mod_losing: list[str] = field(default_factory=list)   # the mod's methods that lose money at base prices (flagged)


def goods_prices(load_order: Path, profile_name: str) -> dict[str, float]:
    """``default_market_price`` per good as the engine reads it: an INJECT's later value wins."""
    profile = load_profile(profile_name, load_order_path=load_order)
    prices: dict[str, float] = {}
    for entry in load_merged_directory(profile, "goods", scope="in_game").entries:
        if isinstance(entry.value, CList):
            values = list(entry.value.values("default_market_price"))
            if values and isinstance(values[-1], (int, float)):
                prices[entry.key] = float(values[-1])
    return prices


def margin_targets(roots: list[Path]) -> dict[str, float]:
    """Numeric script values (``rural_profit_margin = 0.2``) that debug_max_profit may name; later roots win."""
    targets: dict[str, float] = {}
    for root in roots:
        for path in sorted(root.glob("*.txt")):
            for match in re.finditer(r"^(?:[A-Z_]+:)?(\w+)\s*=\s*(-?[0-9.]+)\s*(?:#.*)?$", _read(path), re.MULTILINE):
                targets[match[1]] = float(match[2])
    return targets


def _mask(text: str) -> str:
    """The text with comments and quoted strings blanked out, same length, so indices stay valid."""
    out = list(text)
    i, n = 0, len(text)
    while i < n:
        if text[i] == "#":
            j = text.find("\n", i)
            j = n if j < 0 else j
        elif text[i] == '"':
            j = text.find('"', i + 1)
            j = n if j < 0 else j + 1
        else:
            i += 1
            continue
        out[i:j] = " " * (j - i)
        i = j
    return "".join(out)


def method_blocks(text: str, *, shared: bool) -> list[tuple[str, int, int]]:
    """(name, open, close) of every production method: the top-level blocks of a production_methods file, or
    the children of each building's ``unique_production_methods``."""
    text = _mask(text)
    pairs = _brace_pairs(text)
    tops = _depth_zero_opens(text)
    found = []
    for match in _ENTRY_RE.finditer(text):
        open_ = match.end() - 1
        if match["value"] != "{" or open_ not in tops:
            continue
        if shared:
            found.append((match["key"], open_, pairs[open_]))
            continue
        for inner in _children(text, open_, pairs[open_], pairs):
            if inner[0] == "unique_production_methods":
                found.extend(_children(text, inner[1], inner[2], pairs))
    return found


def _children(text: str, open_: int, close: int, pairs: dict[int, int]) -> list[tuple[str, int, int]]:
    result, i = [], open_ + 1
    while i < close:
        match = _ENTRY_RE.search(text, i, close)
        if not match:
            break
        if match["value"] == "{":
            start = match.end() - 1
            result.append((match["key"], start, pairs[start]))
            i = pairs[start] + 1
        else:
            i = match.end()
    return result


def _flat_entries(body: str) -> dict[str, str]:
    """Scalar entries at the method body's own depth."""
    body = _mask(body)
    pairs = _brace_pairs(body)
    result, i = {}, 0
    while True:
        match = _ENTRY_RE.search(body, i)
        if not match:
            return result
        if match["value"] == "{":
            i = pairs.get(match.end() - 1, match.end()) + 1
        else:
            result[match["key"]] = match["value"]
            i = match.end()


def profit(body: str, prices: dict[str, float]) -> float | None:
    """Base-price profit of one method body, or None when the engine does not check it (nothing produced, no
    priced input, or values the check cannot read)."""
    flat = _flat_entries(body)
    produced, output = flat.get("produced"), flat.get("output")
    if not produced or produced not in prices or output is None:
        return None
    try:
        value = float(output) * prices[produced]
    except ValueError:
        return None
    cost = 0.0
    for key, raw in flat.items():
        if key in NON_INPUTS or key not in prices:
            continue
        try:
            cost += float(raw) * prices[key]
        except ValueError:
            return None
    return value / cost - 1 if cost > 0 else None


def fails(body: str, value: float, targets: dict[str, float]) -> bool:
    """Whether the engine's load check flags the method."""
    raw = _flat_entries(body).get("debug_max_profit")
    if raw is None:
        return value < 0
    try:
        target = float(raw)
    except ValueError:
        if raw not in targets:
            return True
        target = targets[raw]   # rural_profit_margin = 0.2 & co
    if target < 0:
        return value < 0   # no band; vanilla's -1 plantations pass only because they are profitable
    return abs(target - value) > TOLERANCE - 1e-4


def set_debug_profit(body: str, value: float) -> str:
    """The method body (from ``{`` to ``}``) with its debug_max_profit set to ``value``."""
    line = f"debug_max_profit = {value:.3f}"
    inner = body[1:-1]
    existing = _DEBUG_RE.search(_mask(inner))
    if existing:
        return "{" + inner[: existing.start()] + line + inner[existing.end():] + "}"
    if "\n" not in inner:   # one-line body: `{ lumber = 0.1 produced = tar output = 1 }`
        return "{" + inner.rstrip() + " " + line + " }"
    first = next(l for l in inner.splitlines() if l.strip())
    indent = first[: len(first) - len(first.lstrip())]
    head, tail = inner.rsplit("\n", 1)   # tail: the closing brace's indentation
    return "{" + head + "\n" + indent + line + "\n" + tail + "}"


def rewrite(text: str, prices: dict[str, float], targets: dict[str, float], *, shared: bool) -> tuple[str, int]:
    """Text with debug_max_profit kept at the base-price profit on every method that carries the key or that
    the engine would flag."""
    edits = []
    for _, open_, close in method_blocks(text, shared=shared):
        body = text[open_: close + 1]
        value = profit(body, prices)
        # a losing method stays flagged whatever the key says; leave it as authored
        if value is None or value < 0 or not ("debug_max_profit" in _flat_entries(body) or fails(body, value, targets)):
            continue
        new = set_debug_profit(body, value)
        if new != body:
            edits.append((open_, close + 1, new))
    for start, end, new in sorted(edits, reverse=True):
        text = text[:start] + new + text[end:]
    return text, len(edits)


def apply(mod_root: Path, vanilla_root: Path, prices: dict[str, float]) -> ProfitResult:
    result = ProfitResult()
    targets = margin_targets([
        vanilla_root / "game" / scope / "common/script_values" for scope in ("main_menu", "in_game")
    ] + [mod_root / scope / "common/script_values" for scope in ("main_menu", "in_game")])
    generated = mod_root / GENERATED_PATH
    mod_methods: set[str] = set()
    for directory in (BUILDING_TYPES, PRODUCTION_METHODS):
        shared = directory == PRODUCTION_METHODS
        for path in sorted((mod_root / directory).glob("*.txt")):
            if path == generated:
                continue
            text = _read(path)
            if shared:
                mod_methods.update(name for name, _, _ in method_blocks(text, shared=True))
            new, count = rewrite(text, prices, targets, shared=shared)
            result.methods_written += count
            result.mod_losing += [
                name for name, open_, close in method_blocks(text, shared=shared)
                if (value := profit(text[open_: close + 1], prices)) is not None and value < 0
            ]
            if new != text:
                _write(path, new)
                result.files_changed += 1
    blocks = []
    for directory in (BUILDING_TYPES, PRODUCTION_METHODS):
        shared = directory == PRODUCTION_METHODS
        for path in sorted((vanilla_root / "game" / directory).glob("*.txt")):
            if (mod_root / directory / path.name).is_file():
                continue   # the mod ships its own copy of this file (edited above)
            text = _read(path)
            for name, open_, close in method_blocks(text, shared=shared):
                body = text[open_: close + 1]
                value = profit(body, prices)
                if value is None or not fails(body, value, targets) or (shared and name in mod_methods):
                    continue
                if not shared or value < 0:   # replaced buildings' unique methods; losing methods no key helps
                    result.vanilla_unchanged.append(name)
                else:
                    blocks.append(f"TRY_REPLACE:{name} = {set_debug_profit(body, value)}")
                    result.vanilla_replaced.append(name)
    if blocks:
        _write(generated, GENERATED_HEADER + "\n\n".join(blocks) + "\n")
        result.methods_written += len(blocks)
    elif generated.is_file():
        generated.unlink()
    return result


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig", errors="replace")


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("﻿" + text, encoding="utf-8", newline="")
