"""Stored-food effect carrier (EU5 1.4): tier modifiers that follow a province's months of stored food.

EU5 1.4 deleted the engine-scaled static modifier ``positive_province_food_growth``. Growth from stored food is an
engine term now (``NPop.FOOD_STORAGE_POP_GROWTH``, set in pp_defines_adjustments.txt); the other per-stored-year
effects of the 1.3 modifier come back through this carrier:

- ``tiers`` province static modifiers ``pp_stored_food_tier_<t>`` (t = 1 .. tiers); tier t stands for
  t x ``months_per_tier`` whole months of the province's own consumption in store and carries
  ``per_year`` x t x months_per_tier / 12 of each effect (``[stored_food]`` in constructor.toml). Tier 0 has no
  modifier.
- the province-scope script value ``pp_stored_food_tier_target`` = floor(stored months / months_per_tier), capped at
  ``tiers`` (stored months come from ``pp_stored_food_province_months`` in pp_province_food_storage.txt);
- the province-scope scripted effect ``pp_refresh_stored_food_tier``: computes the target into a province variable
  (+100 offset, a variable at 0 counts as unset), compares it with the stored tier through a difference (+100 offset;
  ``var:x = 5`` would be a scope comparison, so only ``<`` / ``>`` ranges are used) and only when the tier changed
  removes the old modifier, adds the new one and stores the new tier.

The refresh runs from ``in_game/common/on_action/pp_stored_food.txt`` (monthly country pulse, staggered over the month)
and once at game start (pp_game_start.txt). ``ppc build`` / ``ppc sync`` write the four generated files in their
finalize step; ``check`` reports files that differ from the configuration.
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path
import tomllib

CONFIG_SECTION = "stored_food"
MODIFIER_PREFIX = "pp_stored_food_tier_"
TARGET_VALUE = "pp_stored_food_tier_target"
MONTHS_VALUE = "pp_stored_food_province_months"
REFRESH_EFFECT = "pp_refresh_stored_food_tier"
TIER_VARIABLE = "pp_stored_food_tier"
NEXT_VARIABLE = "pp_stored_food_tier_next"
CHANGE_VARIABLE = "pp_stored_food_tier_change"
VARIABLE_OFFSET = 100
DECIMALS = 6
MONTHS_PER_YEAR = 12

STATIC_MODIFIERS = Path("in_game/common/static_modifiers/pp_stored_food_tiers.txt")
SCRIPT_VALUES = Path("in_game/common/script_values/pp_stored_food_tiers.txt")
SCRIPTED_EFFECTS = Path("in_game/common/scripted_effects/pp_stored_food_tiers.txt")
LOCALIZATION = Path("main_menu/localization/english/pp_stored_food_tiers_l_english.yml")
GENERATED_FILES = (STATIC_MODIFIERS, SCRIPT_VALUES, SCRIPTED_EFFECTS, LOCALIZATION)

HEADER = "# Generated by ppc build from [stored_food] in constructor.toml (stored_food.py); do not edit by hand.\n"

# Player-facing plain text (generated static-modifier descriptions take no concept links); no balance numbers, the
# modifier tooltip shows them.
DESCRIPTION = (
    "The food this province holds in storage, counted in months of its own consumption. Full stores let its farms "
    "and granaries sell their surplus while taverns earn less from scarcity, and they help the province recover from "
    "devastation, draw settlers and prosper. The effects grow with every stored month up to a cap and follow the "
    "store from month to month."
)


@dataclass(frozen=True)
class StoredFoodConfig:
    tiers: int
    months_per_tier: int
    per_year: tuple[tuple[str, float], ...]


@dataclass(frozen=True)
class StoredFoodResult:
    tiers: int
    files_changed: int
    changed: tuple[Path, ...]


def load_config(project: Path) -> StoredFoodConfig:
    raw = tomllib.loads(project.read_text(encoding="utf-8-sig"))
    section = raw.get(CONFIG_SECTION)
    if not isinstance(section, dict) or not isinstance(section.get("per_year"), dict):
        raise ValueError(f"{project}: [{CONFIG_SECTION}] with a [{CONFIG_SECTION}.per_year] table is required")
    tiers = int(section["tiers"])
    months_per_tier = int(section.get("months_per_tier", 1))
    if tiers < 1 or months_per_tier < 1:
        raise ValueError(f"{project}: [{CONFIG_SECTION}] tiers and months_per_tier must be at least 1")
    per_year = tuple((str(key), float(value)) for key, value in section["per_year"].items())
    if not per_year:
        raise ValueError(f"{project}: [{CONFIG_SECTION}.per_year] is empty")
    return StoredFoodConfig(tiers=tiers, months_per_tier=months_per_tier, per_year=per_year)


def modifier_name(tier: int) -> str:
    return f"{MODIFIER_PREFIX}{tier}"


def tier_months(config: StoredFoodConfig, tier: int) -> int:
    return tier * config.months_per_tier


def tier_values(config: StoredFoodConfig, tier: int) -> dict[str, float]:
    """Each effect of tier ``tier``: the per-stored-year payload x its months / 12, rounded to six decimals."""
    months = Decimal(tier_months(config, tier))
    quantum = Decimal(1).scaleb(-DECIMALS)
    return {
        key: float((Decimal(repr(value)) * months / MONTHS_PER_YEAR).quantize(quantum, rounding=ROUND_HALF_UP))
        for key, value in config.per_year
    }


def format_value(value: float) -> str:
    text = f"{value:.{DECIMALS}f}".rstrip("0")
    if text.endswith("."):
        text += "0"
    return "0.0" if text in {"-0.0", "0.0"} else text


def _tier_limit(variable: str, tier: int) -> str:
    stored = VARIABLE_OFFSET + tier
    return f"var:{variable} > {stored - 0.5} var:{variable} < {stored + 0.5}"


def render_static_modifiers(config: StoredFoodConfig) -> str:
    lines = [
        HEADER,
        "# Stored-food tiers (EU5 1.4 carrier of the 1.3 stored-food effects other than growth, which the define",
        "# NPop.FOOD_STORAGE_POP_GROWTH carries): tier t = t whole months of the province's consumption in store and",
        "# carries the per-stored-year payload x months / 12. pp_refresh_stored_food_tier keeps exactly one tier on each",
        "# province (none below one month).",
        "",
    ]
    for tier in range(1, config.tiers + 1):
        lines.append(f"{modifier_name(tier)} = {{")
        lines.append("\tgame_data = { category = province }")
        for key, value in tier_values(config, tier).items():
            lines.append(f"\t{key} = {format_value(value)}")
        lines.append("}")
    return "\n".join(lines) + "\n"


def render_script_values(config: StoredFoodConfig) -> str:
    divide = "" if config.months_per_tier == 1 else f"\tdivide = {config.months_per_tier}\n"
    return (
        f"{HEADER}\n"
        "# Province scope: the stored-food tier the province should carry, whole tiers of stored months (0 = none).\n"
        f"{TARGET_VALUE} = {{\n"
        f"\tvalue = {MONTHS_VALUE}\n"
        f"{divide}"
        "\tfloor = yes\n"
        "\tmin = 0\n"
        f"\tmax = {config.tiers}\n"
        "}\n"
    )


def render_scripted_effects(config: StoredFoodConfig) -> str:
    def chain(variable: str, action: str) -> list[str]:
        out: list[str] = []
        for tier in range(1, config.tiers + 1):
            keyword = "if" if tier == 1 else "else_if"
            out.append(f"\t{keyword} = {{")
            out.append(f"\t\tlimit = {{ {_tier_limit(variable, tier)} }}")
            out.append(f"\t\t{action.format(name=modifier_name(tier))}")
            out.append("\t}")
        return out

    offset = VARIABLE_OFFSET
    lines = [
        HEADER,
        "# Province scope. Keeps the province's stored-food tier modifier in step with its stored months. Variables hold",
        f"# the tier + {offset} (a variable at 0 counts as unset); `var:x = n` compares scopes, so tiers are matched by",
        "# ranges. Only a changed tier touches the modifiers (about one province in six a month).",
        f"{REFRESH_EFFECT} = {{",
        f"\tset_variable = {{ name = {NEXT_VARIABLE} value = {{ value = {TARGET_VALUE} add = {offset} }} }}",
        f"\tif = {{",
        f"\t\tlimit = {{ NOT = {{ has_variable = {TIER_VARIABLE} }} }}",
        f"\t\tset_variable = {{ name = {TIER_VARIABLE} value = {offset} }}",
        "\t}",
        f"\tset_variable = {{ name = {CHANGE_VARIABLE} value = {{ value = var:{NEXT_VARIABLE} "
        f"subtract = var:{TIER_VARIABLE} add = {offset} }} }}",
        "\tif = {",
        f"\t\tlimit = {{ OR = {{ var:{CHANGE_VARIABLE} < {offset - 0.5} var:{CHANGE_VARIABLE} > {offset + 0.5} }} }}",
        "\t\t# remove the old tier (none at tier 0)",
    ]
    lines += ["\t" + line for line in chain(TIER_VARIABLE, "remove_province_modifier = {name}")]
    lines.append("\t\t# add the new tier (none at tier 0)")
    lines += ["\t" + line for line in chain(NEXT_VARIABLE, "add_province_modifier = {{ modifier = {name} }}")]
    lines += [
        f"\t\tset_variable = {{ name = {TIER_VARIABLE} value = var:{NEXT_VARIABLE} }}",
        "\t}",
        "}",
    ]
    return "\n".join(lines) + "\n"


def render_localization(config: StoredFoodConfig) -> str:
    lines = ["l_english:", f"  {HEADER.strip()}"]
    for tier in range(1, config.tiers + 1):
        months = tier_months(config, tier)
        unit = "month" if months == 1 else "months"
        lines.append(f'  STATIC_MODIFIER_NAME_{modifier_name(tier)}: "Stored Food: {months} {unit}"')
        lines.append(f'  STATIC_MODIFIER_DESC_{modifier_name(tier)}: "{DESCRIPTION}"')
    return "\n".join(lines) + "\n"


def render(config: StoredFoodConfig) -> dict[Path, str]:
    return {
        STATIC_MODIFIERS: render_static_modifiers(config),
        SCRIPT_VALUES: render_script_values(config),
        SCRIPTED_EFFECTS: render_scripted_effects(config),
        LOCALIZATION: render_localization(config),
    }


def _read(path: Path) -> str | None:
    if not path.is_file():
        return None
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return handle.read()


def apply(project: Path, mod_root: Path, *, write: bool = True) -> StoredFoodResult:
    """Write (or with ``write=False`` only compare) the generated stored-food files; UTF-8 with BOM."""
    config = load_config(project)
    changed: list[Path] = []
    for relative, text in render(config).items():
        path = mod_root / relative
        if _read(path) == text:
            continue
        changed.append(relative)
        if write:
            path.parent.mkdir(parents=True, exist_ok=True)
            with path.open("w", encoding="utf-8-sig", newline="") as handle:
                handle.write(text)
    return StoredFoodResult(tiers=config.tiers, files_changed=len(changed), changed=tuple(changed))
