"""Text formatting tags: alias the tags vanilla uses without defining them, and keep the mod's own tags defined.

A ``#tag ... #!`` in GUI text or localization must name a ``format`` from a ``textformatting`` block or an engine
primitive (``bold``, ``color:{...}``, ...); anything else logs ``Unknown formatting tag`` every time the text is drawn.
Names are case-sensitive: vanilla defines ``L`` (game link), and ``#l`` is unknown.

Vanilla's army-recruit panel (``recruit_location_lateralview.gui``) printed its gold costs as ``#l ...#!`` up to EU5 1.3,
which filled debug.log with ~13k lines per session; 1.4 dropped that, but its market and location views (which the mod
overrides) set ``default_format = "#l"``. Overriding the GUI file does not help: CMF re-declares those types with the
same text and loads after the mod. A mod may add its own ``textformatting`` block (other mods do), so ``write_aliases``
defines each such tag as the widget's default format, which leaves the text looking exactly as before.

``check`` scans the mod's own GUI and English localization for tags nothing defines (build print and test).
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

ALIASES_RELATIVE_PATH = Path("main_menu/gui/pp_text_format_aliases.gui")
# tag -> (format it stands for, vanilla file that uses it). The format is the widget's default_format
# (text_single = "#high"), so the aliased text renders as it did while the tag was unknown.
ALIASES: dict[str, tuple[str, str]] = {
    "l": ("high", "in_game/gui/selected_market_view.gui"),
}
# vanilla files that declare textformatting blocks (read instead of scanning the whole install)
VANILLA_FORMAT_FILES = (
    "loading_screen/gui/textformatting.gui",
    "loading_screen/gui/fonttemplates.gui",
    "main_menu/gui/shared/labels.gui",
)
# engine primitives next to the formatter's error message in eu5.exe (TOOLTIP: vanilla loc's #TOOLTIP:TYPE,KEY);
# the others are read from vanilla format strings
ENGINE_PRIMITIVES = frozenset(
    {"bold", "italic", "underline", "strikethrough", "color", "font", "size", "glow_color", "glow_offset",
     "tooltip", "TOOLTIP", "tooltippable", "indent_newline", "onclick"}
)

_QUOTED = re.compile(r'"((?:[^"\\\n]|\\.)*)"')
_TAG = re.compile(r'#(?!!)([^\s#"\[\]]+)')
_NAME = re.compile(r'(?m)^\s*name\s*=\s*"?([^\s"#}]+)')
_FORMAT = re.compile(r'(?m)^\s*format\s*=\s*"([^"]*)"')


@dataclass(frozen=True)
class Unknown:
    tag: str
    path: str
    line: int


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig", errors="replace")


def _format_texts(vanilla_game: Path, mod_root: Path) -> list[str]:
    texts = [_read(vanilla_game / rel) for rel in VANILLA_FORMAT_FILES if (vanilla_game / rel).is_file()]
    texts += [_read(p) for p in sorted((mod_root / "main_menu/gui").rglob("*.gui")) if "textformatting" in _read(p)]
    return texts


def known_tags(vanilla_game: Path, mod_root: Path) -> set[str]:
    """Defined format names plus primitives (the keys used inside vanilla format strings, and the engine list)."""
    known = set(ENGINE_PRIMITIVES)
    for text in _format_texts(vanilla_game, mod_root):
        known.update(_NAME.findall(text))
        for fmt in _FORMAT.findall(text):
            known.update(part.split(":", 1)[0].lstrip("#") for part in fmt.split(";") if part)
    known.discard("")
    return known


def tags_in(text: str):
    """Yield (line number, tag key) for every formatting tag inside a quoted string."""
    for number, line in enumerate(text.splitlines(), 1):
        if "#" not in line:
            continue
        for quoted in _QUOTED.findall(line):
            for match in _TAG.finditer(quoted):
                for part in match.group(1).split(";"):
                    key = part.split(":", 1)[0]
                    if key:
                        yield number, key


def check(vanilla_game: Path, mod_root: Path) -> list[Unknown]:
    """Tags in the mod's GUI files and English localization that no format or primitive defines."""
    known = known_tags(vanilla_game, mod_root)
    files = sorted(mod_root.rglob("*.gui")) + sorted((mod_root / "main_menu/localization/english").rglob("*.yml"))
    unknown = []
    for path in files:
        text = _read(path)
        if "#" not in text:
            continue
        unknown += [Unknown(key, path.relative_to(mod_root).as_posix(), n) for n, key in tags_in(text) if key not in known]
    return unknown


def aliases_text() -> str:
    blocks = "".join(
        f"\n\t# {source}\n\tformat = {{\n\t\tname = {tag}\n\t\tformat = \"{target}\"\n\t}}\n"
        for tag, (target, source) in sorted(ALIASES.items())
    )
    return (
        "# Generated by ppc build (text_formats.py): formats for tags vanilla uses without defining them.\n"
        f"textformatting = {{{blocks}}}\n"
    )


def write_aliases(mod_root: Path) -> bool:
    path = mod_root / ALIASES_RELATIVE_PATH
    text = aliases_text()
    if path.is_file() and _read(path) == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("﻿" + text, encoding="utf-8", newline="")
    return True
