"""The Tavern cap (generated by worldbuilder/market_capacity.py) runs wherever the AI samples a location for a Tavern, so
its neighbour scans only run on coasts: that is only equivalent to scanning everywhere because every land location next
to a navigation reach is coastal (river and channel banks are sea zones for the engine)."""
from __future__ import annotations

import re
import tomllib
from pathlib import Path

import polars as pl
import pytest

from prosper_or_perish_constructor.worldbuilder import coast

REPO = Path(__file__).resolve().parents[1]
MOD = REPO / "mod/Prosper or Perish (Population Growth & Food Rework)"
CAPS = MOD / "in_game/common/script_values/pp_victuals_logistics.txt"


def _tavern_cap() -> str:
    text = CAPS.read_text(encoding="utf-8-sig")
    match = re.search(r"(?ms)^tavern_max_level = \{\n(.*?)^\}", text)
    assert match is not None
    return match.group(1)


def test_every_non_barrier_navigation_bank_is_coastal():
    raw = tomllib.loads((REPO / "constructor.toml").read_text(encoding="utf-8"))
    shores_csv = (REPO / raw["worldbuilder"]["handover"] / "navigation" / "shores.csv").resolve()
    water = coast.cached(REPO)
    if water is None or not shores_csv.is_file():
        pytest.skip("run ppc worldbuilder apply first (water access cache and the navigation handover)")
    shores = pl.read_csv(shores_csv).filter(pl.col("state") != "barrier")
    banks = set(shores["location_tag"].to_list())
    assert banks
    assert sorted(banks - set(water)) == []


def test_tavern_cap_scans_waterways_only_on_coasts_and_stops_at_the_first_match():
    body = _tavern_cap()
    lines = body.splitlines()
    scans = [line for line in lines if "any_neighbor_location" in line]
    # all three neighbour scans sit in the one coastal branch, the maintained scan inside the navigable branch
    assert len(scans) == 1 and scans[0].strip().startswith("if = { limit = { is_coastal = yes }")
    coastal = scans[0]
    assert coastal.count("any_neighbor_location") == 3
    navigable = coastal.index("PP_VM_CAP_NAVIGABLE")
    assert navigable < coastal.index("PP_VM_CAP_MAINTAINED") < coastal.index("else_if")
    # exclusive classes are else_if chains
    for label, count in (("PP_VM_CAP_RIVER", 5), ("PP_VM_CAP_RANK", 3), ("PP_VM_CAP_TERRAIN", 2)):
        chain = [line.strip() for line in lines if label in line]
        assert len(chain) == count, label
        assert chain[0].startswith("if = ") and all(line.startswith("else_if = ") for line in chain[1:]), label
