"""Vanilla scripts that route fleets over the open sea must not be able to pick a navigable river channel.

The channels are sea zones, so river banks are is_coastal and hold ports. A vanilla find_route to such a location
has no sea route and fails at run time (the Chinese treasure voyage: "Failed to fetch variable for
'chinese_treasure_next_location' due to not being set"). These tests fail when a vanilla file that routes or spawns
fleets is not handled in [worldbuilder.navigation_scripts], when a patch no longer applies to the current vanilla
file, and when the built mod lacks the patched copy or the trigger it uses.
"""
from __future__ import annotations

import re
import tomllib
from pathlib import Path

import pytest

from prosper_or_perish_constructor.worldbuilder import navigation_scripts as ns
from prosper_or_perish_constructor.worldbuilder.stage import vanilla_root

REPO = Path(__file__).resolve().parents[1]
PROJECT = REPO / "constructor.toml"
MOD = REPO / "mod/Prosper or Perish (Population Growth & Food Rework)"


def _config():
    raw = tomllib.loads(PROJECT.read_text(encoding="utf-8"))
    return ns.load(raw["worldbuilder"].get("navigation_scripts")), raw["worldbuilder"]["compat"]["vanilla_files"]


@pytest.fixture(scope="module")
def vanilla():
    root = vanilla_root(REPO, PROJECT)
    if not (root / "game/in_game/events").is_dir():
        pytest.skip(f"vanilla files not available at {root}")
    return root


def test_every_vanilla_fleet_script_is_patched_or_reviewed(vanilla):
    cfg, _ = _config()
    assert ns.unlisted(vanilla, cfg) == {}


def test_every_vanilla_sea_route_is_patched(vanilla):
    cfg, _ = _config()
    assert ns.unpatched_routing(vanilla, cfg) == {}, "a file with find_route may only be reviewed if routing cannot pick a river bank; patch it"


def test_listed_files_still_exist_and_patches_still_apply(vanilla):
    cfg, _ = _config()
    for rel in cfg.listed:
        assert (vanilla / "game" / rel).is_file(), f"{rel} no longer exists in vanilla; drop it from the list"
    for rel, replacements in cfg.patches.items():
        ns.patch_text((vanilla / "game" / rel).read_text(encoding="utf-8-sig"), replacements, rel)


def test_built_mod_carries_the_patched_copies_and_the_trigger():
    cfg, _ = _config()
    trigger = (MOD / ns.TRIGGER_RELATIVE_PATH).read_text(encoding="utf-8-sig")
    assert "pp_is_sea_coast = {" in trigger and f"region = region:{ns.NAVIGATION_REGION}" in trigger
    for rel, replacements in cfg.patches.items():
        text = (MOD / rel).read_text(encoding="utf-8-sig")
        # a patched vanilla copy, or a hand-authored mod override the patch was layered onto
        generated = text.startswith("# Generated by ppc worldbuilder")
        assert text.startswith(ns.HEADER) or not generated, f"{rel} is not the patched copy; run ppc worldbuilder apply"
        for r in replacements:
            # >=: one replacement's text may contain another's (is_port = yes pp_is_sea_coast = yes)
            assert text.count(r.replace) >= r.count, f"{rel}: patch missing"


def test_mod_scripts_route_only_to_sea_coasts():
    """The mod's own scripts: every find_route target selection uses pp_is_sea_coast (none use find_route today)."""
    cfg, _ = _config()
    for path in (MOD / "in_game").rglob("*.txt"):
        rel = path.relative_to(MOD).as_posix()
        if rel in cfg.patches:
            continue
        code = "\n".join(line.split("#", 1)[0] for line in path.read_text(encoding="utf-8-sig", errors="replace").splitlines())
        if re.search(r"\b(find_route|create_route)\b", code):
            assert "pp_is_sea_coast" in code, f"{rel} routes fleets without pp_is_sea_coast"


def test_sea_expedition_waypoints_reach_the_open_sea(vanilla):
    """EU5 1.4 expeditions with travel_mode = sea path every leg over open water (the leg's end may be a port). Their
    named waypoints must be sea tiles or sea-coast land on the mod map; a waypoint that is coastal only through a river
    channel or lake, or inland, has no sea path ("failed expedition path")."""
    from prosper_or_perish_constructor.worldbuilder import coast

    state = coast.cached(REPO)
    if state is None:
        pytest.skip("no water access cache; run ppc worldbuilder apply")
    default_map = (MOD / coast.MAP_DIR / "default.map").read_text(encoding="utf-8-sig", errors="replace")
    topography = coast._topographies(MOD / coast.MAP_DIR / "location_templates.txt")
    sea = {t for t in coast._block_tokens(default_map, "sea_zones")
           if not t.startswith(coast.NAVIGATION_PREFIX) and topography.get(t) not in coast.LAKE_TOPOGRAPHIES + coast.IMPASSABLE_WATER}
    waypoints = ns.sea_expedition_waypoints(vanilla)
    assert len(waypoints) > 20, "no sea expedition waypoints found; did vanilla rename travel_mode or waypoints?"
    bad = {name: files for name, files in waypoints.items() if name not in sea and state.get(name) != "sea_coast"}
    assert bad == {}, "sea expedition waypoints off the open sea (patch the expedition or review the map)"


def test_navigation_channels_sit_in_the_trigger_region():
    """pp_is_sea_coast tells channels from the sea by their region; every pp_nav tile must be in it."""
    text = (MOD / "in_game/map_data/definitions.txt").read_text(encoding="utf-8-sig")
    start = text.index(f"{ns.NAVIGATION_REGION} = {{")
    depth, i = 0, text.index("{", start)
    for i in range(i, len(text)):
        depth += {"{": 1, "}": -1}.get(text[i], 0)
        if depth == 0:
            break
    inside = set(re.findall(r"\bpp_nav_\d+\b", text[start:i]))
    everywhere = set(re.findall(r"\bpp_nav_\d+\b", text))
    assert everywhere and inside == everywhere


def test_patch_text_fails_loudly_when_vanilla_changes():
    r = [ns.Replacement("limit = { is_coastal = yes }", "limit = { is_coastal = yes pp_is_sea_coast = yes }", 1)]
    assert "pp_is_sea_coast" in ns.patch_text("x = { limit = { is_coastal = yes } }", r, "f.txt")
    with pytest.raises(ValueError, match="vanilla changed"):
        ns.patch_text("x = { limit = { is_coastal = no } }", r, "f.txt")


def test_patch_goes_on_top_of_the_widened_copy(tmp_path):
    from prosper_or_perish_constructor.worldbuilder import compat

    rel = "in_game/events/x.txt"
    vanilla = tmp_path / "vanilla"
    (vanilla / "game/in_game/events").mkdir(parents=True)
    (vanilla / "game" / rel).write_text("a = { limit = { is_coastal = yes } climate = arid }\n")
    mod = tmp_path / "mod"
    (mod / "in_game/events").mkdir(parents=True)
    (mod / rel).write_text("﻿" + compat.HEADER + "\na = { limit = { is_coastal = yes } OR = { climate = arid climate = desert } }\n")
    cfg = ns.ScriptsConfig({rel: [ns.Replacement("limit = { is_coastal = yes }", "limit = { pp_is_sea_coast = yes }", 1)]}, {})
    ns.write(vanilla, mod, tmp_path, cfg, [rel])
    out = (mod / rel).read_text(encoding="utf-8-sig")
    assert "pp_is_sea_coast = yes" in out and "climate = desert" in out


def test_patch_goes_into_a_hand_authored_override_and_repeats_cleanly(tmp_path):
    """A hand-authored mod override keeps its own changes; the patch is layered into it, and a second apply changes
    nothing (a replacement that contains its find text is not stacked)."""
    rel = "in_game/events/x.txt"
    vanilla = tmp_path / "vanilla"
    (vanilla / "game/in_game/events").mkdir(parents=True)
    (vanilla / "game" / rel).write_text("a = { is_coastal = yes is_port = yes rgo_workers >= 5 }\n")
    mod = tmp_path / "mod"
    (mod / "in_game/events").mkdir(parents=True)
    (mod / rel).write_text("﻿namespace = x\na = { is_coastal = yes is_port = yes rgo_workers >= 0 }\n")
    cfg = ns.ScriptsConfig({rel: [ns.Replacement("is_coastal = yes", "pp_is_sea_coast = yes", 1),
                                  ns.Replacement("is_port = yes", "is_port = yes pp_is_sea_coast = yes", 1)]}, {})
    expected = "namespace = x\na = { pp_is_sea_coast = yes is_port = yes pp_is_sea_coast = yes rgo_workers >= 0 }\n"
    for _ in range(2):
        ns.write(vanilla, mod, tmp_path, cfg, [])
        assert (mod / rel).read_text(encoding="utf-8-sig") == expected
    # the hand-authored file is never deleted when it leaves the patch list
    ns.write(vanilla, mod, tmp_path, ns.ScriptsConfig({}, {}, {rel: "reviewed"}), [])
    assert (mod / rel).read_text(encoding="utf-8-sig") == expected
