"""Bake the population baseline of a reference save into a scripted effect.

The `pp_pop_delta_*` map modes colour `(current / baseline) - 1`. Left to itself the
baseline is whatever `pp_snapshot_population_baselines` captured at that campaign's own
game start, so two campaigns are never comparable. This script freezes the population of
one reference save -- the campaign labelled `base` -- into
`pp_population_baseline_base_data.txt`, so every campaign measures against the same state.

Units: the engine stores population in thousands at 1e-5 fixed point, so five decimals is
exact. Parent-scope baselines are plain sums of the member locations' population; that was
validated against the values the engine itself wrote into the reference save (all six
scopes matched to the last digit for `stockholm`).

Regenerate with:
    uv run python scripts/generate_population_baseline_data.py \
        --locations artifacts/data/savegame/locations.parquet
"""

from __future__ import annotations

import argparse
from pathlib import Path

import polars as pl

ROOT = Path(__file__).resolve().parents[1]
MOD_ROOT = ROOT / "mod" / "Prosper or Perish (Population Growth & Food Rework)"
OUTPUT = (
    MOD_ROOT
    / "in_game"
    / "common"
    / "scripted_effects"
    / "pp_population_baseline_base_data.txt"
)
DEFAULT_LOCATIONS = ROOT / "artifacts" / "data" / "savegame" / "locations.parquet"

EFFECT_NAME = "pp_load_base_population_baselines"

# variable name -> column holding the grouping key ("" = the location itself)
SCOPES: tuple[tuple[str, str], ...] = (
    ("pp_pop_baseline", ""),
    ("pp_province_pop_baseline", "province_slug"),
    ("pp_area_pop_baseline", "area"),
    ("pp_region_pop_baseline", "region"),
    ("pp_macro_region_pop_baseline", "macro_region"),
    ("pp_super_region_pop_baseline", "super_region"),
)


def _fmt(value: float) -> str:
    """Five decimals, trailing zeros trimmed -- the engine's own precision."""
    text = f"{value:.5f}".rstrip("0").rstrip(".")
    return text or "0"


def build_rows(frame: pl.DataFrame) -> list[str]:
    missing = [c for _, c in SCOPES if c and c not in frame.columns]
    if missing:
        raise SystemExit(f"locations parquet is missing columns: {missing}")

    frame = frame.filter(pl.col("total_population") > 0)
    if frame.height == 0:
        raise SystemExit("no locations with population > 0 -- wrong save?")

    for name, column in SCOPES:
        if not column:
            continue
        frame = frame.with_columns(
            pl.col("total_population").sum().over(column).alias(name)
        )
    frame = frame.with_columns(pl.col("total_population").alias("pp_pop_baseline"))

    frame = frame.sort("slug")
    rows: list[str] = []
    for record in frame.iter_rows(named=True):
        sets = " ".join(
            f"set_variable = {{ name = {name} value = {_fmt(record[name])} }}"
            for name, _ in SCOPES
        )
        rows.append(f"location:{record['slug']} = {{ {sets} }}")
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--locations", type=Path, default=DEFAULT_LOCATIONS)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--label", default="base", help="reference save label, for the header")
    args = parser.parse_args()

    if not args.locations.is_file():
        raise SystemExit(f"missing {args.locations}; run `ppc savegame --save <reference>.eu5` first")

    rows = build_rows(pl.read_parquet(args.locations))

    header = [
        f"# Generated by scripts/{Path(__file__).name} -- do not edit by hand.",
        f"# Population baseline frozen from the reference save labelled '{args.label}'.",
        "# Values are population in thousands, the same unit the `population` script value returns.",
        "# Parent-scope rows are sums of the member locations, validated against the engine's own",
        "# snapshot in that save. Re-snapshot a running campaign to 'now' instead with:",
        "#   event pp_population_baseline_debug.1",
        f"{EFFECT_NAME} = {{",
    ]
    text = "﻿" + "\n".join(header) + "\n" + "\n".join(rows) + "\n}\n"
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")

    size_mb = args.output.stat().st_size / 1_048_576
    print(f"wrote {len(rows)} locations to {args.output} ({size_mb:.1f} MiB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
