from __future__ import annotations

import os
import re
import shutil
import sys
import tomllib
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

from map_mode_styles import (  # noqa: E402
    SignedCenteredScale,
    bucketed_color_cases,
    legend_keys,
    load_scale_calibration,
    signed_centered,
    signed_scale_from_data,
)

PROJECT_CONFIG = ROOT / "constructor.toml"

MAP_MODE_REL = Path("in_game/gfx/map/map_modes/pp_local_output_modifier_map_modes.txt")
SCRIPT_VALUES_REL = Path("in_game/common/script_values/pp_local_output_modifier_map_modes.txt")
LOCAL_OUTPUT_MAP_VALUES_ON_ACTION_REL = Path("in_game/common/on_action/pp_local_output_map_values.txt")
LOCATION_MODIFIER_APPLICATION_REL = Path("in_game/common/on_action/pp_apply_location_modifiers.txt")
LOCATION_STATIC_MODIFIERS_REL = Path("main_menu/common/static_modifiers/pp_location_modifiers.txt")
RGO_STATIC_BONUSES_REL = Path("in_game/common/static_modifiers/pp_rgo_static_bonuses.txt")
LOCALIZATION_REL = Path("main_menu/localization/english/pp_building_adjustments_l_english.yml")
MODIFIER_TYPE_DEFINITIONS_REL = Path(
    "main_menu/common/modifier_type_definitions/pp_local_output_map_mode_modifier_types.txt"
)
MODIFIER_ICONS_REL = Path("main_menu/common/modifier_icons/pp_local_output_map_mode_modifier_icons.txt")
MODIFIER_TYPE_LOCALIZATION_REL = Path(
    "main_menu/localization/english/pp_local_output_map_mode_modifier_types_l_english.yml"
)
IN_GAME_ICON_REL = Path("in_game/gfx/interface/icons/map_modes")
MAIN_MENU_ICON_REL = Path("main_menu/gfx/interface/icons/map_modes")
TRADE_GOOD_ICON_REL = Path("main_menu/gfx/interface/icons/trade_goods")

LOCALIZATION_START = "  # Local output modifier map modes (pp_local_output_modifier_map_modes.txt)"
LOCALIZATION_END = "  # End generated local output modifier map modes"
GENERATED_FILE_MARKER = "# Generated by scripts/generate_raw_material_local_map_modes.py - do not edit by hand."
WHEAT_GOOD = "wheat"
RAW_MATERIAL_STRIPE_RGB = (246, 197, 75)
OUTPUT_MODIFIER_LEGEND_CLASSES = (
    "EXTREME_DEFICIT",
    "DEFICIT",
    "NEUTRAL",
    "GOOD",
    "EXCELLENT",
    "EXCEPTIONAL",
)


def main() -> None:
    project = _load_project_config(PROJECT_CONFIG)
    mod_root = _project_path(project["project"]["mod_root"])
    rgo_bonus_values = _rgo_bonus_output_values(mod_root / RGO_STATIC_BONUSES_REL)
    raw_materials = list(rgo_bonus_values)
    modifier_locations = _location_modifier_application_locations(mod_root / LOCATION_MODIFIER_APPLICATION_REL)
    location_potential_values = _location_potential_values(
        mod_root / LOCATION_STATIC_MODIFIERS_REL,
        raw_materials,
        modifier_locations,
    )

    _write_map_modes(mod_root / MAP_MODE_REL, raw_materials)
    goods_with_location_potential = _goods_with_location_potential(location_potential_values)
    _write_script_values(mod_root / SCRIPT_VALUES_REL, rgo_bonus_values, goods_with_location_potential)
    _write_location_potential_variables(
        mod_root / LOCAL_OUTPUT_MAP_VALUES_ON_ACTION_REL,
        raw_materials,
        location_potential_values,
    )
    _remove_obsolete_generated_file(mod_root / MODIFIER_TYPE_DEFINITIONS_REL)
    _remove_obsolete_generated_file(mod_root / MODIFIER_ICONS_REL)
    _remove_obsolete_generated_file(mod_root / MODIFIER_TYPE_LOCALIZATION_REL)
    _remove_generated_map_value_modifiers(mod_root / LOCATION_STATIC_MODIFIERS_REL)
    _remove_generated_map_value_modifiers(mod_root / RGO_STATIC_BONUSES_REL)
    _upsert_localization(mod_root / LOCALIZATION_REL, raw_materials)
    _ensure_icons(mod_root, raw_materials, project)
    print(f"Generated local output modifier map modes for {len(raw_materials)} raw materials.")


def _load_project_config(path: Path) -> dict:
    with path.open("rb") as stream:
        return tomllib.load(stream)


def _project_path(raw: str) -> Path:
    path = _host_path(Path(raw))
    return path if path.is_absolute() else (ROOT / path).resolve()


def _host_path(path: Path) -> Path:
    path_text = str(path)
    match = re.match(r"^([A-Za-z]):[\\/](.*)$", path_text)
    if match is None or os.name == "nt":
        return path
    drive = match.group(1).lower()
    tail = match.group(2).replace("\\", "/")
    return Path("/mnt") / drive / tail


def _vanilla_root(project: dict) -> Path:
    parser = project.get("parser", {})
    load_order = _project_path(str(parser.get("load_order") or "constructor.load_order.toml"))
    with load_order.open("rb") as stream:
        raw = tomllib.load(stream)
    paths = raw.get("paths", {})
    vanilla_root = _host_path(Path(str(paths.get("vanilla_root", ""))))
    if not vanilla_root.is_absolute():
        vanilla_root = (load_order.parent / vanilla_root).resolve()
    return vanilla_root


def _write_map_modes(path: Path, goods: Iterable[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    goods = list(goods)
    scales = _local_output_scales(goods)
    blocks = [
        "# Generated by scripts/generate_raw_material_local_map_modes.py - do not edit by hand.",
        "# Displays static local output potential for every generated raw-material bonus good.",
        "# Red/yellow/green classified diverging scale. Values are additive percentages (0.1 = +10%).",
        "# Map color = per-location potential variable + active pp_rgo_bonus_<good> static modifier.",
        "# Location potential is stored in hidden per-location variables so no map helper modifiers appear in UI.",
        "# Geography index = 2 keeps these in the terrain/climate bucket.",
        "",
        "@zoom_step_near = 2",
        "@data_gradient_alpha_inside = 1",
        "@data_gradient_alpha_outside = 1",
        "@data_gradient_width = 0.25",
        "@data_gradient_color_mult = 0.9",
        "@data_edge_width = 0",
        "@data_edge_sharpness = 0.01",
        "@data_edge_alpha = 0",
        "@data_edge_color_mult = 0",
        "@data_before_lighting_blend = 0.5",
        "@data_after_lighting_blend = 0.5",
        "",
    ]
    for good in goods:
        blocks.append(_map_mode_block(good, scales[good]))
    _write_crlf(path, "\n".join(blocks).rstrip() + "\n")


def _local_output_scales(goods: Iterable[str]) -> dict[str, SignedCenteredScale]:
    calibration = load_scale_calibration()
    configured = calibration.get("scales", {}).get("local_output_modifier", {}) if calibration else {}
    return {good: signed_scale_from_data(configured.get(good)) for good in goods}


def _map_mode_block(good: str, scale: SignedCenteredScale) -> str:
    upper = good.upper()
    return f"""pp_local_{good}_output_modifier = {{
{_output_modifier_map_color_block(_productivity_value_name(good), scale)}
\tsecondary_map_color = {{
\t\tif = {{
\t\t\tlimit = {{
\t\t\t\tis_ownable = yes
\t\t\t\traw_material = goods:{good}
\t\t\t}}
\t\t\tvalue = {_rgb(RAW_MATERIAL_STRIPE_RGB)}
\t\t}}
\t}}
{_output_modifier_legend_keys(upper)}
\ttooltip_key = {{
\t\tif = {{
\t\t\tlimit = {{ is_land = yes }}
\t\t\tvalue = MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER_TT_LAND_BREAKDOWN
\t\t}}
\t\telse = {{
\t\t\tvalue = MAPMODE_PP_LOCAL_OUTPUT_TT_WATER
\t\t}}
\t}}
\tsmall_map_names = location
\tmedium_map_names = location
\tlarge_map_names = location
\tsmall_tooltip_context = location
\tmedium_tooltip_context = location
\tlarge_tooltip_context = location
\tfill_in_impassable = yes
\tenable_snow = no
\tflatmap_behaviour = always
\tuse_fow = no
\tcategory = geography
\tindex = 2
\tallow_allocate_hotkey = no
\tmap_markers = {{ all = no }}
\tgradient_parameters = {{
\t\tzoom_step = @zoom_step_near
\t\tgradient_alpha_inside = @data_gradient_alpha_inside
\t\tgradient_alpha_outside = @data_gradient_alpha_outside
\t\tgradient_width = @data_gradient_width
\t\tgradient_color_mult = @data_gradient_color_mult
\t\tedge_width = @data_edge_width
\t\tedge_sharpness = @data_edge_sharpness
\t\tedge_alpha = @data_edge_alpha
\t\tedge_color_mult = @data_edge_color_mult
\t\tbefore_lighting_blend = @data_before_lighting_blend
\t\tafter_lighting_blend = @data_after_lighting_blend
\t}}
}}
"""


def _output_modifier_map_color_block(value_name: str, scale: SignedCenteredScale) -> str:
    buckets = signed_centered(scale)
    lines = [
        "\tmap_color = {",
        "\t\tif = {",
        "\t\t\tlimit = { is_ownable = no }",
        "\t\t\tvalue = rgb { 128 128 128 }",
        "\t\t}",
        bucketed_color_cases(value_name, buckets, first_branch="else_if"),
        "\t}",
    ]
    return "\n".join(lines)


def _output_modifier_legend_keys(upper: str) -> str:
    lines = [legend_keys(f"MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER", signed_centered(signed_scale_from_data(None)), OUTPUT_MODIFIER_LEGEND_CLASSES)]
    lines.append(
        f'\tlegend_key = {{ desc = "MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER_RAW_MATERIAL" color = {_rgb(RAW_MATERIAL_STRIPE_RGB)} }}'
    )
    return "\n".join(lines)


def _write_script_values(
    path: Path,
    rgo_bonus_values: dict[str, tuple[str, str]],
    goods_with_location_potential: set[str],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    blocks = [
        GENERATED_FILE_MARKER,
        "# Static planning values for the raw-material output map modes.",
        "# Total map value = available generated location potential variable + active raw-material RGO bonus.",
        "# Location potential variables are emitted only for goods with generated source rows.",
        "# Variables avoid visible map helper modifier rows and avoid generated trigger tables.",
        "# RGO bonus checks the raw material directly so pp_rgo_bonus_<good> stays player-facing without helper rows.",
        "",
    ]
    for good, (_modifier, value) in rgo_bonus_values.items():
        blocks.extend(
            _script_value_block(
                good,
                value,
                has_location_potential=good in goods_with_location_potential,
            )
        )
        blocks.append("")
    _write_crlf(path, "\n".join(blocks).rstrip() + "\n")


def _script_value_block(
    good: str,
    rgo_bonus_value: str,
    *,
    has_location_potential: bool,
) -> list[str]:
    variable_name = _productivity_location_potential_variable_name(good)
    lines = [
        f"{_productivity_value_name(good)} = {{",
        "\tvalue = 0",
    ]
    if has_location_potential:
        lines.extend(
            [
                "\tif = {",
                f"\t\tlimit = {{ has_variable = {variable_name} }}",
                f"\t\tvalue = var:{variable_name}",
                "\t}",
            ]
        )
    lines.extend(
        [
            "\tif = {",
            f"\t\tlimit = {{ raw_material = goods:{good} }}",
            f"\t\tadd = {rgo_bonus_value}",
            "\t}",
            "}",
            "",
            f"{_productivity_location_potential_value_name(good)} = {{",
            "\tvalue = 0",
        ]
    )
    if has_location_potential:
        lines.extend(
            [
                "\tif = {",
                f"\t\tlimit = {{ has_variable = {variable_name} }}",
                f"\t\tvalue = var:{variable_name}",
                "\t}",
            ]
        )
    lines.extend(
        [
            "}",
            "",
            f"{_productivity_rgo_bonus_value_name(good)} = {{",
            "\tvalue = 0",
            "\tif = {",
            f"\t\tlimit = {{ raw_material = goods:{good} }}",
            f"\t\tadd = {rgo_bonus_value}",
            "\t}",
            "}",
        ]
    )
    return lines


def _goods_with_location_potential(location_potential_values: dict[str, dict[str, str]]) -> set[str]:
    return {good for values in location_potential_values.values() for good in values}


def _rgo_bonus_output_values(path: Path) -> dict[str, tuple[str, str]]:
    text = path.read_text(encoding="utf-8-sig")
    values: dict[str, tuple[str, str]] = {}
    pattern = re.compile(r"^(pp_rgo_bonus_([a-z0-9_]+))\s*=\s*\{(?P<body>.*?)^\}", re.DOTALL | re.MULTILINE)
    for match in pattern.finditer(text):
        modifier = match.group(1)
        good = match.group(2)
        value_match = re.search(
            rf"^\s*local_{re.escape(good)}_output_modifier\s*=\s*([-+]?\d+(?:\.\d+)?)\s*$",
            match.group("body"),
            flags=re.MULTILINE,
        )
        if value_match is None:
            raise ValueError(f"{modifier} in {path} is missing local_{good}_output_modifier")
        values[good] = (modifier, value_match.group(1))
    if not values:
        raise ValueError(f"Could not find pp_rgo_bonus_<good> output modifiers in {path}")
    return values


def _productivity_value_name(good: str) -> str:
    return f"pp_{good}_productivity_map_value"


def _productivity_location_potential_value_name(good: str) -> str:
    return f"pp_{good}_productivity_location_potential_map_value"


def _productivity_rgo_bonus_value_name(good: str) -> str:
    return f"pp_{good}_productivity_rgo_bonus_map_value"


def _productivity_location_potential_variable_name(good: str) -> str:
    return f"pp_{good}_productivity_location_potential_map_var"


def _location_modifier_application_locations(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8-sig")
    locations: dict[str, str] = {}
    pattern = re.compile(
        r"location:([A-Za-z0-9_]+)\s*=\s*\{\s*"
        r"add_location_modifier\s*=\s*\{\s*modifier\s*=\s*(pp_loc_[a-z0-9_]+)",
        re.MULTILINE,
    )
    for match in pattern.finditer(text):
        locations[match.group(2)] = match.group(1)
    if not locations:
        raise ValueError(f"Could not find pp_loc_* application mappings in {path}")
    return locations


def _location_potential_values(
    path: Path,
    goods: Iterable[str],
    modifier_locations: dict[str, str],
) -> dict[str, dict[str, str]]:
    goods_set = set(goods)
    values: dict[str, dict[str, str]] = {}
    text = path.read_text(encoding="utf-8-sig")
    pattern = re.compile(r"^(pp_loc_[a-z0-9_]+)\s*=\s*\{(?P<body>.*?)^\}", re.DOTALL | re.MULTILINE)
    for match in pattern.finditer(text):
        modifier = match.group(1)
        location = modifier_locations.get(modifier)
        if location is None:
            raise ValueError(f"{modifier} in {path} is not applied by {LOCATION_MODIFIER_APPLICATION_REL}")
        for value_match in re.finditer(
            r"^\s*local_([a-z0-9_]+)_output_modifier\s*=\s*([-+]?\d+(?:\.\d+)?)\s*$",
            match.group("body"),
            flags=re.MULTILINE,
        ):
            good = value_match.group(1)
            value = value_match.group(2)
            if good in goods_set and not _is_zero_value(value):
                values.setdefault(location, {})[good] = value
    return values


def _write_location_potential_variables(
    path: Path,
    goods: Iterable[str],
    location_potential_values: dict[str, dict[str, str]],
) -> None:
    goods = list(goods)
    goods_with_location_potential = _goods_with_location_potential(location_potential_values)
    lines = [
        GENERATED_FILE_MARKER,
        "# Hidden per-location variables for raw-material output map modes.",
        "# Values are generated from pp_loc_* local_<good>_output_modifier source rows.",
        "",
        "on_game_start = {",
        "\ton_actions = {",
        "\t\tpp_precalculate_local_output_map_values",
        "\t}",
        "}",
        "",
        "pp_precalculate_local_output_map_values = {",
        "\teffect = {",
        "\t\tevery_location_in_the_world = {",
    ]
    for good in goods:
        if good not in goods_with_location_potential:
            continue
        lines.append(f"\t\t\tremove_variable = {_productivity_location_potential_variable_name(good)}")
    lines.append("\t\t}")
    for location in sorted(location_potential_values):
        values = location_potential_values[location]
        if not values:
            continue
        lines.append(f"\t\tlocation:{location} = {{")
        for good in goods:
            value = values.get(good)
            if value is None:
                continue
            lines.append(
                f"\t\t\tset_variable = {{ name = {_productivity_location_potential_variable_name(good)} value = {value} }}"
            )
        lines.append("\t\t}")
    lines.extend(["\t}", "}"])
    _write_crlf(path, "\n".join(lines).rstrip() + "\n")


def _remove_obsolete_generated_file(path: Path) -> None:
    if not path.exists():
        return
    text = path.read_text(encoding="utf-8-sig")
    if GENERATED_FILE_MARKER not in text:
        raise ValueError(f"Refusing to delete non-generated map helper file: {path}")
    path.unlink()


def _remove_generated_map_value_modifiers(path: Path) -> None:
    output = [
        line
        for line in path.read_text(encoding="utf-8-sig").splitlines()
        if not _is_generated_map_value_modifier_line(line)
    ]
    _write_crlf(path, "\n".join(output).rstrip() + "\n")


def _is_generated_map_value_modifier_line(line: str) -> bool:
    return (
        re.match(
            r"^\s*pp_[a-z0-9_]+_productivity_(?:location_potential|rgo_bonus)_map_modifier\s*=",
            line,
        )
        is not None
    )


def _is_zero_value(value: str) -> bool:
    return float(value) == 0


def _upsert_localization(path: Path, goods: Iterable[str]) -> None:
    existing = path.read_text(encoding="utf-8-sig")
    generated = _localization_block(goods)
    if LOCALIZATION_START in existing:
        if LOCALIZATION_END in existing:
            pattern = re.compile(
                rf"{re.escape(LOCALIZATION_START)}.*?{re.escape(LOCALIZATION_END)}\n?",
                re.DOTALL,
            )
            updated = pattern.sub(lambda _match: generated, existing)
        else:
            legacy_end = re.compile(
                rf"{re.escape(LOCALIZATION_START)}.*?"
                r'  MAPMODE_PP_LOCAL_OUTPUT_TT_WATER: "[^"]*"\n?',
                re.DOTALL,
            )
            updated = legacy_end.sub(lambda _match: generated, existing)
    else:
        anchor = "  # Unemployed Peasants (Unemployment) map mode - absolute numbers, cap 0-50k"
        if anchor not in existing:
            raise ValueError(f"Could not find localization insertion point in {path}")
        updated = existing.replace(anchor, generated + "\n" + anchor)
    _write_crlf(path, updated.rstrip() + "\n")


def _localization_block(goods: Iterable[str]) -> str:
    lines = [
        LOCALIZATION_START,
        "  # Generated by scripts/generate_raw_material_local_map_modes.py - do not edit by hand.",
        '  PP_LOCAL_OUTPUT_MAPMODE_RANGE: "Red-yellow-green static productivity bands"',
    ]
    goods = list(goods)
    for good in goods:
        display = _localized_good_name(good)
        lines.append(f'  mapmode_pp_local_{good}_output_modifier_name: "Local {display} Productivity"')
    lines.append("")
    for good in goods:
        lines.extend(_output_modifier_legend_localization_lines(good))
    lines.append("")
    for good in goods:
        upper = good.upper()
        display = _localized_good_name(good)
        lines.append(
            f'  PP_LOCAL_{upper}_OUTPUT_MODIFIER_LOCATION_POTENTIAL_TT: '
            f'"Static {display} productivity from location potential."'
        )
        lines.append(
            f'  PP_LOCAL_{upper}_OUTPUT_MODIFIER_RGO_BONUS_TT: '
            f'"Static {display} productivity from the matching raw material."'
        )
        lines.append(
            f'  PP_LOCAL_{upper}_OUTPUT_MODIFIER_TOTAL_TT: '
            f'"Total static {display} productivity from location potential and RGO bonus."'
        )
    lines.append("")
    for good in goods:
        upper = good.upper()
        lines.append(
            f'  MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER_TT_LAND: '
            f'"{_output_modifier_tooltip(good)}"'
        )
    lines.append("")
    for good in goods:
        upper = good.upper()
        lines.append(
            f'  MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER_TT_LAND_BREAKDOWN: '
            f'"{_output_modifier_tooltip(good)}"'
        )
    lines.extend(
        [
            "",
            '  MAPMODE_PP_LOCAL_OUTPUT_TT_WATER: "[ROOT.GetLocation.GetName] is not a land [location|e] so it does not have production modifiers."',
            LOCALIZATION_END,
        ]
    )
    return "\n".join(lines) + "\n"


def _output_modifier_tooltip(good: str) -> str:
    upper = good.upper()
    name_key = f"mapmode_pp_local_{good}_output_modifier_name"
    total_value = _tooltip_value(
        f"SIMPLE_CUSTOM,PP_LOCAL_{upper}_OUTPUT_MODIFIER_TOTAL_TT",
        f"[ROOT.GetLocation.MakeScope.ScriptValue('{_productivity_value_name(good)}')|2]",
    )
    location_value = _tooltip_value(
        f"SIMPLE_CUSTOM,PP_LOCAL_{upper}_OUTPUT_MODIFIER_LOCATION_POTENTIAL_TT",
        f"[ROOT.GetLocation.MakeScope.ScriptValue('{_productivity_location_potential_value_name(good)}')|2]",
    )
    rgo_value = _tooltip_value(
        f"SIMPLE_CUSTOM,PP_LOCAL_{upper}_OUTPUT_MODIFIER_RGO_BONUS_TT",
        f"[ROOT.GetLocation.MakeScope.ScriptValue('{_productivity_rgo_bonus_value_name(good)}')|2]",
    )
    return (
        f"#T ${name_key}$#!\\n"
        f"Location potential static modifier: {location_value}\\n"
        f"RGO bonus static modifier: {rgo_value}\\n"
        f"Total static modifier: {total_value}"
    )


def _tooltip_value(desc_key: str, value: str) -> str:
    return f"#TOOLTIP:{desc_key} #L {value}#!#!"


def _output_modifier_legend_localization_lines(good: str) -> list[str]:
    upper = good.upper()
    name_key = f"mapmode_pp_local_{good}_output_modifier_name"
    display = _localized_good_name(good)
    description = (
        f"This colors [locations|e] by static {display} productivity from location potential and raw-material bonus. "
        "Red marks negative productivity, yellow marks near-neutral productivity, and green marks positive productivity; "
        f"stripes mark locations where {display} is the raw material."
    )
    lines = [f'  MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER: "#T ${name_key}$#!\\n{description}"']
    lines.extend(
        f'  MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER_{suffix}: "{_output_modifier_legend_description(good, suffix)}"'
        for suffix in OUTPUT_MODIFIER_LEGEND_CLASSES
    )
    lines.append(f'  MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER_RAW_MATERIAL: "{display} raw material"')
    return lines


def _output_modifier_legend_description(good: str, suffix: str) -> str:
    display = _localized_good_name(good)
    if good == WHEAT_GOOD:
        return {
            "EXTREME_DEFICIT": f"Severe {display} productivity deficit",
            "DEFICIT": f"{display} productivity deficit",
            "NEUTRAL": f"Near neutral {display} productivity",
            "GOOD": f"Good {display} productivity",
            "EXCELLENT": f"Excellent {display} productivity",
            "EXCEPTIONAL": f"Exceptional {display} productivity",
        }[suffix]
    generic_descriptions = {
        "EXTREME_DEFICIT": f"Extreme local {display} deficit",
        "DEFICIT": f"Local {display} productivity deficit",
        "NEUTRAL": f"Near neutral local {display} productivity",
        "GOOD": f"Good local {display} productivity",
        "EXCELLENT": f"Excellent local {display} productivity",
        "EXCEPTIONAL": f"Exceptional local {display} productivity",
    }
    return generic_descriptions[suffix]


def _localized_good_name(good: str) -> str:
    return f"${good}$"


def _rgb(value: tuple[int, int, int]) -> str:
    red, green, blue = value
    return f"rgb {{ {red} {green} {blue} }}"


def _write_crlf(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="\n") as stream:
        stream.write(text)


def _ensure_icons(mod_root: Path, goods: Iterable[str], project: dict) -> None:
    vanilla_root = _vanilla_root(project)
    targets = [mod_root / IN_GAME_ICON_REL, mod_root / MAIN_MENU_ICON_REL]
    for target in targets:
        target.mkdir(parents=True, exist_ok=True)

    missing: list[str] = []
    for good in goods:
        source = _icon_source(mod_root, vanilla_root, good)
        if source is None:
            missing.append(good)
            continue
        for target_dir in targets:
            destination = target_dir / f"pp_local_{good}_output_modifier.dds"
            if not destination.exists():
                shutil.copy2(source, destination)
    if missing:
        raise FileNotFoundError("Missing icon source for raw material goods: " + ", ".join(missing))


def _icon_source(mod_root: Path, vanilla_root: Path, good: str) -> Path | None:
    candidates = [
        mod_root / IN_GAME_ICON_REL / f"pp_local_{good}_output_modifier.dds",
        mod_root / MAIN_MENU_ICON_REL / f"pp_local_{good}_output_modifier.dds",
        mod_root / IN_GAME_ICON_REL / f"pp_{good}_output.dds",
        mod_root / MAIN_MENU_ICON_REL / f"pp_{good}_output.dds",
        vanilla_root / "game" / TRADE_GOOD_ICON_REL / f"icon_goods_{good}.dds",
        mod_root / TRADE_GOOD_ICON_REL / f"icon_goods_{good}.dds",
        mod_root / "in_game" / "gfx" / "interface" / "icons" / "trade_goods" / f"icon_goods_{good}.dds",
    ]
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    return None


if __name__ == "__main__":
    main()
