from __future__ import annotations

import os
import re
import shutil
import sys
import tomllib
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

from map_mode_styles import (  # noqa: E402
    SignedCenteredScale,
    bucketed_color_cases,
    legend_keys,
    load_scale_calibration,
    signed_centered,
    signed_scale_from_data,
)

PROJECT_CONFIG = ROOT / "constructor.toml"

MAP_MODE_REL = Path("in_game/gfx/map/map_modes/pp_local_output_modifier_map_modes.txt")
SCRIPT_VALUES_REL = Path("in_game/common/script_values/pp_local_output_modifier_map_modes.txt")
LOCATION_STATIC_MODIFIERS_REL = Path("main_menu/common/static_modifiers/pp_location_modifiers.txt")
RGO_STATIC_BONUSES_REL = Path("in_game/common/static_modifiers/pp_rgo_static_bonuses.txt")
LOCALIZATION_REL = Path("main_menu/localization/english/pp_building_adjustments_l_english.yml")
MODIFIER_TYPE_DEFINITIONS_REL = Path(
    "main_menu/common/modifier_type_definitions/pp_local_output_map_mode_modifier_types.txt"
)
MODIFIER_ICONS_REL = Path("main_menu/common/modifier_icons/pp_local_output_map_mode_modifier_icons.txt")
MODIFIER_TYPE_LOCALIZATION_REL = Path(
    "main_menu/localization/english/pp_local_output_map_mode_modifier_types_l_english.yml"
)
IN_GAME_ICON_REL = Path("in_game/gfx/interface/icons/map_modes")
MAIN_MENU_ICON_REL = Path("main_menu/gfx/interface/icons/map_modes")
TRADE_GOOD_ICON_REL = Path("main_menu/gfx/interface/icons/trade_goods")

LOCALIZATION_START = "  # Local output modifier map modes (pp_local_output_modifier_map_modes.txt)"
LOCALIZATION_END = "  # End generated local output modifier map modes"
WHEAT_GOOD = "wheat"
RAW_MATERIAL_STRIPE_RGB = (246, 197, 75)
OUTPUT_MODIFIER_LEGEND_CLASSES = (
    "EXTREME_DEFICIT",
    "DEFICIT",
    "NEUTRAL",
    "GOOD",
    "EXCELLENT",
    "EXCEPTIONAL",
)


def main() -> None:
    project = _load_project_config(PROJECT_CONFIG)
    mod_root = _project_path(project["project"]["mod_root"])
    rgo_bonus_values = _rgo_bonus_output_values(mod_root / RGO_STATIC_BONUSES_REL)
    raw_materials = list(rgo_bonus_values)

    _write_map_modes(mod_root / MAP_MODE_REL, raw_materials)
    _write_script_values(mod_root / SCRIPT_VALUES_REL, raw_materials)
    _write_modifier_type_definitions(mod_root / MODIFIER_TYPE_DEFINITIONS_REL, raw_materials)
    _write_modifier_icons(mod_root / MODIFIER_ICONS_REL, raw_materials)
    _write_modifier_type_localization(mod_root / MODIFIER_TYPE_LOCALIZATION_REL, raw_materials)
    _upsert_location_potential_map_modifiers(mod_root / LOCATION_STATIC_MODIFIERS_REL, raw_materials)
    _upsert_rgo_bonus_map_modifiers(mod_root / RGO_STATIC_BONUSES_REL, raw_materials)
    _upsert_localization(mod_root / LOCALIZATION_REL, raw_materials)
    _ensure_icons(mod_root, raw_materials, project)
    print(f"Generated local output modifier map modes for {len(raw_materials)} raw materials.")


def _load_project_config(path: Path) -> dict:
    with path.open("rb") as stream:
        return tomllib.load(stream)


def _project_path(raw: str) -> Path:
    path = _host_path(Path(raw))
    return path if path.is_absolute() else (ROOT / path).resolve()


def _host_path(path: Path) -> Path:
    path_text = str(path)
    match = re.match(r"^([A-Za-z]):[\\/](.*)$", path_text)
    if match is None or os.name == "nt":
        return path
    drive = match.group(1).lower()
    tail = match.group(2).replace("\\", "/")
    return Path("/mnt") / drive / tail


def _vanilla_root(project: dict) -> Path:
    parser = project.get("parser", {})
    load_order = _project_path(str(parser.get("load_order") or "constructor.load_order.toml"))
    with load_order.open("rb") as stream:
        raw = tomllib.load(stream)
    paths = raw.get("paths", {})
    vanilla_root = _host_path(Path(str(paths.get("vanilla_root", ""))))
    if not vanilla_root.is_absolute():
        vanilla_root = (load_order.parent / vanilla_root).resolve()
    return vanilla_root


def _write_map_modes(path: Path, goods: Iterable[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    goods = list(goods)
    scales = _local_output_scales(goods)
    blocks = [
        "# Generated by scripts/generate_raw_material_local_map_modes.py - do not edit by hand.",
        "# Displays static local output potential for every generated raw-material bonus good.",
        "# Red/yellow/green classified diverging scale. Values are additive percentages (0.1 = +10%).",
        "# Map color = per-location potential + active pp_rgo_bonus_<good> static modifier.",
        "# Map values use generated helper modifiers so activation does not scan every pp_loc_* modifier.",
        "# Geography index = 2 keeps these in the terrain/climate bucket.",
        "",
        "@zoom_step_near = 2",
        "@data_gradient_alpha_inside = 1",
        "@data_gradient_alpha_outside = 1",
        "@data_gradient_width = 0.25",
        "@data_gradient_color_mult = 0.9",
        "@data_edge_width = 0",
        "@data_edge_sharpness = 0.01",
        "@data_edge_alpha = 0",
        "@data_edge_color_mult = 0",
        "@data_before_lighting_blend = 0.5",
        "@data_after_lighting_blend = 0.5",
        "",
    ]
    for good in goods:
        blocks.append(_map_mode_block(good, scales[good]))
    _write_crlf(path, "\n".join(blocks).rstrip() + "\n")


def _local_output_scales(goods: Iterable[str]) -> dict[str, SignedCenteredScale]:
    calibration = load_scale_calibration()
    configured = calibration.get("scales", {}).get("local_output_modifier", {}) if calibration else {}
    return {good: signed_scale_from_data(configured.get(good)) for good in goods}


def _map_mode_block(good: str, scale: SignedCenteredScale) -> str:
    upper = good.upper()
    return f"""pp_local_{good}_output_modifier = {{
{_output_modifier_map_color_block(_productivity_value_name(good), scale)}
\tsecondary_map_color = {{
\t\tif = {{
\t\t\tlimit = {{
\t\t\t\tis_ownable = yes
\t\t\t\traw_material = goods:{good}
\t\t\t}}
\t\t\tvalue = {_rgb(RAW_MATERIAL_STRIPE_RGB)}
\t\t}}
\t}}
{_output_modifier_legend_keys(upper)}
\ttooltip_key = {{
\t\tif = {{
\t\t\tlimit = {{ is_land = yes }}
\t\t\tvalue = MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER_TT_LAND_BREAKDOWN
\t\t}}
\t\telse = {{
\t\t\tvalue = MAPMODE_PP_LOCAL_OUTPUT_TT_WATER
\t\t}}
\t}}
\tsmall_map_names = location
\tmedium_map_names = location
\tlarge_map_names = location
\tsmall_tooltip_context = location
\tmedium_tooltip_context = location
\tlarge_tooltip_context = location
\tfill_in_impassable = yes
\tenable_snow = no
\tflatmap_behaviour = always
\tuse_fow = no
\tcategory = geography
\tindex = 2
\tallow_allocate_hotkey = no
\tmap_markers = {{ all = no }}
\tgradient_parameters = {{
\t\tzoom_step = @zoom_step_near
\t\tgradient_alpha_inside = @data_gradient_alpha_inside
\t\tgradient_alpha_outside = @data_gradient_alpha_outside
\t\tgradient_width = @data_gradient_width
\t\tgradient_color_mult = @data_gradient_color_mult
\t\tedge_width = @data_edge_width
\t\tedge_sharpness = @data_edge_sharpness
\t\tedge_alpha = @data_edge_alpha
\t\tedge_color_mult = @data_edge_color_mult
\t\tbefore_lighting_blend = @data_before_lighting_blend
\t\tafter_lighting_blend = @data_after_lighting_blend
\t}}
}}
"""


def _output_modifier_map_color_block(value_name: str, scale: SignedCenteredScale) -> str:
    buckets = signed_centered(scale)
    lines = [
        "\tmap_color = {",
        "\t\tif = {",
        "\t\t\tlimit = { is_ownable = no }",
        "\t\t\tvalue = rgb { 128 128 128 }",
        "\t\t}",
        bucketed_color_cases(value_name, buckets, first_branch="else_if"),
        "\t}",
    ]
    return "\n".join(lines)


def _output_modifier_legend_keys(upper: str) -> str:
    lines = [legend_keys(f"MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER", signed_centered(signed_scale_from_data(None)), OUTPUT_MODIFIER_LEGEND_CLASSES)]
    lines.append(
        f'\tlegend_key = {{ desc = "MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER_RAW_MATERIAL" color = {_rgb(RAW_MATERIAL_STRIPE_RGB)} }}'
    )
    return "\n".join(lines)


def _write_script_values(path: Path, goods: Iterable[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    blocks = [
        "# Generated by scripts/generate_raw_material_local_map_modes.py - do not edit by hand.",
        "# Static planning values for the raw-material output map modes.",
        "# Total map value = generated location potential + active raw-material RGO bonus.",
        "# Component values read helper modifiers instead of scanning every pp_loc_* static modifier.",
        "",
    ]
    for good in goods:
        blocks.extend(_script_value_block(good))
        blocks.append("")
    _write_crlf(path, "\n".join(blocks).rstrip() + "\n")


def _script_value_block(good: str) -> list[str]:
    lines = [
        f"{_productivity_value_name(good)} = {{",
        f"\tvalue = modifier:{_productivity_location_potential_modifier_name(good)}",
        f"\tadd = modifier:{_productivity_rgo_bonus_modifier_name(good)}",
        "}",
        "",
        f"{_productivity_location_potential_value_name(good)} = {{",
        f"\tvalue = modifier:{_productivity_location_potential_modifier_name(good)}",
        "}",
        "",
        f"{_productivity_rgo_bonus_value_name(good)} = {{",
        f"\tvalue = modifier:{_productivity_rgo_bonus_modifier_name(good)}",
        "}",
    ]
    return lines


def _rgo_bonus_output_values(path: Path) -> dict[str, tuple[str, str]]:
    text = path.read_text(encoding="utf-8-sig")
    values: dict[str, tuple[str, str]] = {}
    pattern = re.compile(r"^(pp_rgo_bonus_([a-z0-9_]+))\s*=\s*\{(?P<body>.*?)^\}", re.DOTALL | re.MULTILINE)
    for match in pattern.finditer(text):
        modifier = match.group(1)
        good = match.group(2)
        value_match = re.search(
            rf"^\s*local_{re.escape(good)}_output_modifier\s*=\s*([-+]?\d+(?:\.\d+)?)\s*$",
            match.group("body"),
            flags=re.MULTILINE,
        )
        if value_match is None:
            raise ValueError(f"{modifier} in {path} is missing local_{good}_output_modifier")
        values[good] = (modifier, value_match.group(1))
    if not values:
        raise ValueError(f"Could not find pp_rgo_bonus_<good> output modifiers in {path}")
    return values


def _productivity_value_name(good: str) -> str:
    return f"pp_{good}_productivity_map_value"


def _productivity_location_potential_value_name(good: str) -> str:
    return f"pp_{good}_productivity_location_potential_map_value"


def _productivity_rgo_bonus_value_name(good: str) -> str:
    return f"pp_{good}_productivity_rgo_bonus_map_value"


def _productivity_location_potential_modifier_name(good: str) -> str:
    return f"pp_{good}_productivity_location_potential_map_modifier"


def _productivity_rgo_bonus_modifier_name(good: str) -> str:
    return f"pp_{good}_productivity_rgo_bonus_map_modifier"


def _write_modifier_type_definitions(path: Path, goods: Iterable[str]) -> None:
    lines = [
        "# Generated by scripts/generate_raw_material_local_map_modes.py - do not edit by hand.",
        "# Hidden planning modifiers used by local output map modes.",
        "",
    ]
    for good in goods:
        for modifier in _map_value_modifier_names(good):
            lines.extend(
                [
                    f"{modifier}={{",
                    "\tpercent=yes",
                    "\tgame_data={",
                    "\t\tcategory=location",
                    "\t}",
                    "}",
                    "",
                ]
            )
    _write_crlf(path, "\n".join(lines).rstrip() + "\n")


def _write_modifier_icons(path: Path, goods: Iterable[str]) -> None:
    lines = [
        "# Generated by scripts/generate_raw_material_local_map_modes.py - do not edit by hand.",
        "# Generic icons for local output map-mode helper modifiers.",
        "",
    ]
    for good in goods:
        for modifier in _map_value_modifier_names(good):
            lines.extend(
                [
                    f"{modifier} = {{",
                    '\tpositive = "gfx/interface/icons/modifier_types/_default.dds"',
                    "}",
                ]
            )
    _write_crlf(path, "\n".join(lines).rstrip() + "\n")


def _write_modifier_type_localization(path: Path, goods: Iterable[str]) -> None:
    lines = [
        "l_english:",
        "  # Generated by scripts/generate_raw_material_local_map_modes.py - do not edit by hand.",
    ]
    for good in goods:
        display = _display_name(good)
        location_modifier = _productivity_location_potential_modifier_name(good)
        rgo_modifier = _productivity_rgo_bonus_modifier_name(good)
        lines.extend(
            [
                f'  MODIFIER_TYPE_NAME_{location_modifier}: "{display} Location Potential"',
                (
                    f'  MODIFIER_TYPE_DESC_{location_modifier}: '
                    f'"Static {display.lower()} productivity from location potential."'
                ),
                f'  MODIFIER_TYPE_NAME_{rgo_modifier}: "{display} RGO Bonus"',
                (
                    f'  MODIFIER_TYPE_DESC_{rgo_modifier}: '
                    f'"Static {display.lower()} productivity from the matching raw-material bonus."'
                ),
            ]
        )
    _write_crlf(path, "\n".join(lines).rstrip() + "\n")


def _map_value_modifier_names(good: str) -> tuple[str, str]:
    return (
        _productivity_location_potential_modifier_name(good),
        _productivity_rgo_bonus_modifier_name(good),
    )


def _upsert_location_potential_map_modifiers(path: Path, goods: Iterable[str]) -> None:
    goods_set = set(goods)
    current_modifier: str | None = None
    output: list[str] = []
    for line in path.read_text(encoding="utf-8-sig").splitlines():
        if _is_generated_map_value_modifier_line(line):
            continue
        start_match = re.match(r"^(pp_loc_[a-z0-9_]+)\s*=\s*\{", line)
        if start_match:
            current_modifier = start_match.group(1)
        elif current_modifier is not None and line.strip() == "}":
            current_modifier = None
        output.append(line)
        if current_modifier is None:
            continue
        value_match = re.match(
            r"^(\s*)local_([a-z0-9_]+)_output_modifier\s*=\s*([-+]?\d+(?:\.\d+)?)\s*$",
            line,
        )
        if value_match is None:
            continue
        good = value_match.group(2)
        value = value_match.group(3)
        if good in goods_set and not _is_zero_value(value):
            output.append(
                f"{value_match.group(1)}{_productivity_location_potential_modifier_name(good)} = {value}"
            )
    _write_crlf(path, "\n".join(output).rstrip() + "\n")


def _upsert_rgo_bonus_map_modifiers(path: Path, goods: Iterable[str]) -> None:
    goods_set = set(goods)
    current_good: str | None = None
    output: list[str] = []
    for line in path.read_text(encoding="utf-8-sig").splitlines():
        if _is_generated_map_value_modifier_line(line):
            continue
        start_match = re.match(r"^pp_rgo_bonus_([a-z0-9_]+)\s*=\s*\{", line)
        if start_match:
            current_good = start_match.group(1)
        elif current_good is not None and line.strip() == "}":
            current_good = None
        output.append(line)
        if current_good is None or current_good not in goods_set:
            continue
        value_match = re.match(
            rf"^(\s*)local_{re.escape(current_good)}_output_modifier\s*=\s*([-+]?\d+(?:\.\d+)?)\s*$",
            line,
        )
        if value_match is not None and not _is_zero_value(value_match.group(2)):
            output.append(
                f"{value_match.group(1)}{_productivity_rgo_bonus_modifier_name(current_good)} = {value_match.group(2)}"
            )
    _write_crlf(path, "\n".join(output).rstrip() + "\n")


def _is_generated_map_value_modifier_line(line: str) -> bool:
    return (
        re.match(
            r"^\s*pp_[a-z0-9_]+_productivity_(?:location_potential|rgo_bonus)_map_modifier\s*=",
            line,
        )
        is not None
    )


def _is_zero_value(value: str) -> bool:
    return float(value) == 0


def _upsert_localization(path: Path, goods: Iterable[str]) -> None:
    existing = path.read_text(encoding="utf-8-sig")
    generated = _localization_block(goods)
    if LOCALIZATION_START in existing:
        if LOCALIZATION_END in existing:
            pattern = re.compile(
                rf"{re.escape(LOCALIZATION_START)}.*?{re.escape(LOCALIZATION_END)}\n?",
                re.DOTALL,
            )
            updated = pattern.sub(lambda _match: generated, existing)
        else:
            legacy_end = re.compile(
                rf"{re.escape(LOCALIZATION_START)}.*?"
                r'  MAPMODE_PP_LOCAL_OUTPUT_TT_WATER: "[^"]*"\n?',
                re.DOTALL,
            )
            updated = legacy_end.sub(lambda _match: generated, existing)
    else:
        anchor = "  # Unemployed Peasants (Unemployment) map mode - absolute numbers, cap 0-50k"
        if anchor not in existing:
            raise ValueError(f"Could not find localization insertion point in {path}")
        updated = existing.replace(anchor, generated + "\n" + anchor)
    _write_crlf(path, updated.rstrip() + "\n")


def _localization_block(goods: Iterable[str]) -> str:
    lines = [
        LOCALIZATION_START,
        "  # Generated by scripts/generate_raw_material_local_map_modes.py - do not edit by hand.",
        '  PP_LOCAL_OUTPUT_MAPMODE_RANGE: "Red-yellow-green static productivity bands"',
    ]
    goods = list(goods)
    for good in goods:
        name = "Wheat Productivity" if good == WHEAT_GOOD else f"Local {_display_name(good)} Output"
        lines.append(f'  mapmode_pp_local_{good}_output_modifier_name: "{name}"')
    lines.append("")
    for good in goods:
        lines.extend(_output_modifier_legend_localization_lines(good))
    lines.append("")
    for good in goods:
        upper = good.upper()
        display = _display_name(good).lower()
        lines.append(
            f'  PP_LOCAL_{upper}_OUTPUT_MODIFIER_TOTAL_TT: '
            f'"Total static {display} productivity from location potential and RGO bonus."'
        )
    lines.append("")
    for good in goods:
        upper = good.upper()
        lines.append(
            f'  MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER_TT_LAND: '
            f'"{_output_modifier_tooltip(good)}"'
        )
    lines.append("")
    for good in goods:
        upper = good.upper()
        lines.append(
            f'  MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER_TT_LAND_BREAKDOWN: '
            f'"{_output_modifier_tooltip(good)}"'
        )
    lines.extend(
        [
            "",
            '  MAPMODE_PP_LOCAL_OUTPUT_TT_WATER: "[ROOT.GetLocation.GetName] is not a land [location|e] so it does not have production modifiers."',
            LOCALIZATION_END,
        ]
    )
    return "\n".join(lines) + "\n"


def _output_modifier_tooltip(good: str) -> str:
    upper = good.upper()
    name_key = f"mapmode_pp_local_{good}_output_modifier_name"
    total_value = _tooltip_value(
        f"SIMPLE_CUSTOM,PP_LOCAL_{upper}_OUTPUT_MODIFIER_TOTAL_TT",
        f"[ROOT.GetLocation.MakeScope.ScriptValue('{_productivity_value_name(good)}')|2]",
    )
    location_modifier = _productivity_location_potential_modifier_name(good)
    rgo_modifier = _productivity_rgo_bonus_modifier_name(good)
    location_value = _tooltip_value(
        f"MODIFIER_TYPE,{location_modifier}",
        f"[ROOT.GetLocation.MakeScope.ScriptValue('{_productivity_location_potential_value_name(good)}')|2]",
    )
    rgo_value = _tooltip_value(
        f"MODIFIER_TYPE,{rgo_modifier}",
        f"[ROOT.GetLocation.MakeScope.ScriptValue('{_productivity_rgo_bonus_value_name(good)}')|2]",
    )
    return (
        f"#T ${name_key}$#!\\n"
        f"Location potential static modifier: {location_value}\\n"
        f"RGO bonus static modifier: {rgo_value}\\n"
        f"Total static modifier: {total_value}"
    )


def _tooltip_value(desc_key: str, value: str) -> str:
    return f"#TOOLTIP:{desc_key} #L {value}#!#!"


def _output_modifier_legend_localization_lines(good: str) -> list[str]:
    upper = good.upper()
    name_key = f"mapmode_pp_local_{good}_output_modifier_name"
    display = _display_name(good).lower()
    description = (
        f"This colors [locations|e] by static {display} productivity from location potential and raw-material bonus. "
        "Red marks negative productivity, yellow marks near-neutral productivity, and green marks positive productivity; "
        f"stripes mark locations where {display} is the raw material."
    )
    lines = [f'  MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER: "#T ${name_key}$#!\\n{description}"']
    lines.extend(
        f'  MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER_{suffix}: "{_output_modifier_legend_description(good, suffix)}"'
        for suffix in OUTPUT_MODIFIER_LEGEND_CLASSES
    )
    lines.append(f'  MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER_RAW_MATERIAL: "{_display_name(good)} raw material"')
    return lines


def _output_modifier_legend_description(good: str, suffix: str) -> str:
    if good == WHEAT_GOOD:
        return {
            "EXTREME_DEFICIT": "Severe wheat productivity deficit",
            "DEFICIT": "Wheat productivity deficit",
            "NEUTRAL": "Near neutral wheat productivity",
            "GOOD": "Good wheat productivity",
            "EXCELLENT": "Excellent wheat productivity",
            "EXCEPTIONAL": "Exceptional wheat productivity",
        }[suffix]
    display = _display_name(good).lower()
    generic_descriptions = {
        "EXTREME_DEFICIT": f"Extreme local {display} deficit",
        "DEFICIT": f"Local {display} productivity deficit",
        "NEUTRAL": f"Near neutral local {display} output",
        "GOOD": f"Good local {display} productivity",
        "EXCELLENT": f"Excellent local {display} productivity",
        "EXCEPTIONAL": f"Exceptional local {display} output",
    }
    return generic_descriptions[suffix]


def _display_name(good: str) -> str:
    return good.replace("_", " ").title()


def _rgb(value: tuple[int, int, int]) -> str:
    red, green, blue = value
    return f"rgb {{ {red} {green} {blue} }}"


def _write_crlf(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="\n") as stream:
        stream.write(text)


def _ensure_icons(mod_root: Path, goods: Iterable[str], project: dict) -> None:
    vanilla_root = _vanilla_root(project)
    targets = [mod_root / IN_GAME_ICON_REL, mod_root / MAIN_MENU_ICON_REL]
    for target in targets:
        target.mkdir(parents=True, exist_ok=True)

    missing: list[str] = []
    for good in goods:
        source = _icon_source(mod_root, vanilla_root, good)
        if source is None:
            missing.append(good)
            continue
        for target_dir in targets:
            destination = target_dir / f"pp_local_{good}_output_modifier.dds"
            if not destination.exists():
                shutil.copy2(source, destination)
    if missing:
        raise FileNotFoundError("Missing icon source for raw material goods: " + ", ".join(missing))


def _icon_source(mod_root: Path, vanilla_root: Path, good: str) -> Path | None:
    candidates = [
        mod_root / IN_GAME_ICON_REL / f"pp_local_{good}_output_modifier.dds",
        mod_root / MAIN_MENU_ICON_REL / f"pp_local_{good}_output_modifier.dds",
        mod_root / IN_GAME_ICON_REL / f"pp_{good}_output.dds",
        mod_root / MAIN_MENU_ICON_REL / f"pp_{good}_output.dds",
        vanilla_root / "game" / TRADE_GOOD_ICON_REL / f"icon_goods_{good}.dds",
        mod_root / TRADE_GOOD_ICON_REL / f"icon_goods_{good}.dds",
        mod_root / "in_game" / "gfx" / "interface" / "icons" / "trade_goods" / f"icon_goods_{good}.dds",
    ]
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    return None


if __name__ == "__main__":
    main()
