from __future__ import annotations

import os
import re
import shutil
import tomllib
from pathlib import Path
from typing import Iterable

from eu5gameparser.domain.eu5 import load_eu5_data


ROOT = Path(__file__).resolve().parents[1]
PROJECT_CONFIG = ROOT / "constructor.toml"

MAP_MODE_REL = Path("in_game/gfx/map/map_modes/pp_goods_output_map_modes_generated.txt")
SCRIPT_VALUES_REL = Path("in_game/common/script_values/pp_goods_output_map_modes_generated.txt")
LOCALIZATION_REL = Path("main_menu/localization/english/pp_goods_output_map_modes_l_english.yml")
IN_GAME_ICON_REL = Path("in_game/gfx/interface/icons/map_modes")
TRADE_GOOD_ICON_REL = Path("main_menu/gfx/interface/icons/trade_goods")
GOODS_OUTPUT_BUCKETS = (
    ("RANGE_0_10", 0, 10, "define:NMapColors|MAP_COLOR_MIN", "define:NMapColors|MAP_COLOR_LOW"),
    ("RANGE_10_30", 10, 30, "define:NMapColors|MAP_COLOR_LOW", "define:NMapColors|MAP_COLOR_MID"),
    ("RANGE_30_60", 30, 60, "define:NMapColors|MAP_COLOR_MID", "define:NMapColors|MAP_COLOR_HIGH"),
    ("RANGE_60_100", 60, 100, "define:NMapColors|MAP_COLOR_HIGH", "define:NMapColors|MAP_COLOR_MAX"),
    ("RANGE_100_150", 100, 150, "define:NMapColors|MAP_COLOR_MAX", "define:NMapColors|MAP_COLOR_TOP"),
    ("RANGE_150_300", 150, 300, "define:NMapColors|MAP_COLOR_TOP", "rgb { 245 245 245 }"),
)
GOODS_OUTPUT_CAP_COLOR = "rgb { 245 245 245 }"
GOODS_OUTPUT_OVERFLOW_COLOR = "rgb { 70 210 255 }"


def main() -> None:
    project = _load_project_config(PROJECT_CONFIG)
    mod_root = _project_path(project["project"]["mod_root"])
    goods = sorted(_all_goods(project))

    _write_crlf(mod_root / MAP_MODE_REL, _map_modes_file(goods))
    _write_crlf(mod_root / SCRIPT_VALUES_REL, _script_values_file(goods))
    _write_crlf(mod_root / LOCALIZATION_REL, _localization_file(goods))
    _ensure_icons(mod_root, goods, project)
    print(f"Generated goods output map modes for {len(goods)} goods.")


def _load_project_config(path: Path) -> dict:
    with path.open("rb") as stream:
        return tomllib.load(stream)


def _project_path(raw: str) -> Path:
    path = _host_path(Path(raw))
    return path if path.is_absolute() else (ROOT / path).resolve()


def _host_path(path: Path) -> Path:
    path_text = str(path)
    match = re.match(r"^([A-Za-z]):[\\/](.*)$", path_text)
    if match is None or os.name == "nt":
        return path
    drive = match.group(1).lower()
    tail = match.group(2).replace("\\", "/")
    return Path("/mnt") / drive / tail


def _all_goods(project: dict) -> list[str]:
    parser = project.get("parser", {})
    profile = str(parser.get("profile") or "constructor")
    load_order = _project_path(str(parser.get("load_order") or "constructor.load_order.toml"))
    data = load_eu5_data(profile=profile, load_order_path=load_order)
    return data.goods.select("name").to_series().to_list()


def _vanilla_root(project: dict) -> Path:
    parser = project.get("parser", {})
    load_order = _project_path(str(parser.get("load_order") or "constructor.load_order.toml"))
    with load_order.open("rb") as stream:
        raw = tomllib.load(stream)
    paths = raw.get("paths", {})
    vanilla_root = _project_path(str(paths.get("vanilla_root", "")))
    if not vanilla_root.is_absolute():
        vanilla_root = (load_order.parent / vanilla_root).resolve()
    return vanilla_root


def _map_modes_file(goods: Iterable[str]) -> str:
    goods_list = list(goods)
    blocks = [
        "# Generated by tools/generate_pp_goods_output_map_modes.py - do not edit by hand.",
        "# Fixed bucket heatmap: raw = local output x market_access; colors lerp inside each configured range.",
        "# Locations with zero local output of the good get no overlay (terrain); sea/unowned stay grey.",
        "",
        "@zoom_step_near = 2",
        "@data_gradient_alpha_inside = 1",
        "@data_gradient_alpha_outside = 1",
        "@data_gradient_width = 0.25",
        "@data_gradient_color_mult = 0.9",
        "@data_edge_width = 0",
        "@data_edge_sharpness = 0.01",
        "@data_edge_alpha = 0",
        "@data_edge_color_mult = 0",
        "@data_before_lighting_blend = 0.5",
        "@data_after_lighting_blend = 0.5",
        "",
    ]
    for good in goods_list:
        blocks.append(_map_mode_block(good))
    return "\n".join(blocks).rstrip() + "\n"


def _map_mode_block(good: str) -> str:
    upper = good.upper()
    return f"""pp_{good}_output = {{
\tmap_color = {{
{_goods_output_color_cases(good)}
\t\telse_if = {{
\t\t\tlimit = {{
\t\t\t\tOR = {{
\t\t\t\t\tNOT = {{ has_owner = yes }}
\t\t\t\t\tis_land = no
\t\t\t\t}}
\t\t\t}}
\t\t\tvalue = rgb {{ 128 128 128 }}
\t\t}}
\t}}
{_goods_output_legend_keys(f"MAPMODE_PP_{upper}_OUTPUT")}
\ttooltip_key = {{
\t\tif = {{ limit = {{ is_land = yes }} value = MAPMODE_PP_{upper}_OUTPUT_TT_LAND }}
\t\telse = {{ value = MAPMODE_PP_{upper}_OUTPUT_TT_WATER }}
\t}}
\tsmall_map_names = location
\tmedium_map_names = location
\tlarge_map_names = location
\tsmall_tooltip_context = location
\tmedium_tooltip_context = location
\tlarge_tooltip_context = location
\tfill_in_impassable = yes
\tenable_snow = no
\tflatmap_behaviour = always
\tuse_fow = no
\tcategory = economy
\tindex = 3
\tmap_markers = {{ all = no }}
\tgradient_parameters = {{
\t\tzoom_step = @zoom_step_near
\t\tgradient_alpha_inside = @data_gradient_alpha_inside
\t\tgradient_alpha_outside = @data_gradient_alpha_outside
\t\tgradient_width = @data_gradient_width
\t\tgradient_color_mult = @data_gradient_color_mult
\t\tedge_width = @data_edge_width
\t\tedge_sharpness = @data_edge_sharpness
\t\tedge_alpha = @data_edge_alpha
\t\tedge_color_mult = @data_edge_color_mult
\t\tbefore_lighting_blend = @data_before_lighting_blend
\t\tafter_lighting_blend = @data_after_lighting_blend
\t}}
\tcolor_refresh_counters = {{ Month ProductionList LocationConstructionUnitChanged MarketReach }}
\tcolor_and_names_refresh_counters = {{ LocationOwnerChanged CountryStatus MarketReach }}
}}
"""


def _goods_output_color_cases(good: str) -> str:
    value_name = f"pp_{good}_output_raw"
    cases: list[str] = []
    for index, (_suffix, lower, upper, min_color, max_color) in enumerate(GOODS_OUTPUT_BUCKETS):
        keyword = "if" if index == 0 else "else_if"
        factor_lines = [f"\t\t\t\t\tvalue = {value_name}"]
        if lower:
            factor_lines.append(f"\t\t\t\t\tsubtract = {lower}")
        factor_lines.extend(
            [
                f"\t\t\t\t\tdivide = {upper - lower}",
                "\t\t\t\t\tmax = 1",
                "\t\t\t\t\tmin = 0",
            ]
        )
        cases.append(
            f"""\t\t{keyword} = {{
\t\t\tlimit = {{
\t\t\t\thas_owner = yes
\t\t\t\t"goods_output(goods:{good})" > 0
\t\t\t\t{value_name} < {upper}
\t\t\t}}
\t\t\tlerp = {{
\t\t\t\tmin_color = {min_color}
\t\t\t\tmax_color = {max_color}
\t\t\t\tfactor = {{
{chr(10).join(factor_lines)}
\t\t\t\t}}
\t\t\t}}
\t\t}}"""
        )
    cases.append(
        f"""\t\telse_if = {{
\t\t\tlimit = {{
\t\t\t\thas_owner = yes
\t\t\t\t"goods_output(goods:{good})" > 0
\t\t\t}}
\t\t\tvalue = {GOODS_OUTPUT_OVERFLOW_COLOR}
\t\t}}"""
    )
    return "\n".join(cases)


def _goods_output_legend_keys(prefix: str) -> str:
    lines = []
    for suffix, _lower, _upper, color, _max_color in GOODS_OUTPUT_BUCKETS:
        lines.extend(
            [
                "\tlegend_key = {",
                f'\t\tdesc = "{prefix}_{suffix}"',
                f"\t\tcolor = {color}",
                "\t}",
            ]
        )
    lines.extend(
        [
            "\tlegend_key = {",
            f'\t\tdesc = "{prefix}_CAPPED"',
            f"\t\tcolor = {GOODS_OUTPUT_OVERFLOW_COLOR}",
            "\t}",
        ]
    )
    return "\n".join(lines)


def _script_values_file(goods: Iterable[str]) -> str:
    blocks = [
        "# Generated by tools/generate_pp_goods_output_map_modes.py - do not edit by hand.",
        "# Local monthly goods output x location market_access (cf. Location.GetMarketAccess).",
        "",
    ]
    for good in goods:
        blocks.append(_script_value_block(good))
    return "\n".join(blocks).rstrip() + "\n"


def _script_value_block(good: str) -> str:
    return f"""pp_{good}_output_raw = {{
\tvalue = "goods_output(goods:{good})"
\tmultiply = market_access
}}
"""


def _localization_file(goods: Iterable[str]) -> str:
    lines = [
        "l_english:",
        "  # Generated by tools/generate_pp_goods_output_map_modes.py - do not edit by hand.",
    ]
    for good in goods:
        upper = good.upper()
        lines.extend(
            [
                f'  mapmode_pp_{good}_output_name: "[ShowGoodsName(\'{good}\')|e] Output (x Market Access)"',
                f'  MAPMODE_PP_{upper}_OUTPUT: "{_legend_text(good)}"',
                f'  MAPMODE_PP_{upper}_OUTPUT_RANGE_0_10: "0-10 output"',
                f'  MAPMODE_PP_{upper}_OUTPUT_RANGE_10_30: "10-30 output"',
                f'  MAPMODE_PP_{upper}_OUTPUT_RANGE_30_60: "30-60 output"',
                f'  MAPMODE_PP_{upper}_OUTPUT_RANGE_60_100: "60-100 output"',
                f'  MAPMODE_PP_{upper}_OUTPUT_RANGE_100_150: "100-150 output"',
                f'  MAPMODE_PP_{upper}_OUTPUT_RANGE_150_300: "150-300 output"',
                f'  MAPMODE_PP_{upper}_OUTPUT_CAPPED: "300+ output"',
                f'  MAPMODE_PP_{upper}_OUTPUT_TT_LAND: "{_land_tooltip_text(good)}"',
                f'  MAPMODE_PP_{upper}_OUTPUT_TT_WATER: "$MAPMODE_PP_LOCAL_OUTPUT_TT_WATER$"',
            ]
        )
    return "\n".join(lines) + "\n"


def _legend_text(good: str) -> str:
    base = (
        f"#T $mapmode_pp_{good}_output_name$#!\\n"
        f"Colors [locations|e] by local [ShowGoodsName('{good}')|e] [output|e] x "
        "[market_access|e] using fixed buckets: 0-10, 10-30, 30-60, 60-100, 100-150, 150-300, and 300+. Colors blend inside each bounded bucket; zero-output locations are left without overlay."
    )
    if good == "marble":
        base += (
            " Marble comes from dedicated [ShowBuildingTypeName('marble_quarry')|e] and "
            "[ShowBuildingTypeName('marble_saw_yard')|e] production."
        )
    return base


def _land_tooltip_text(good: str) -> str:
    base = (
        f"#T $mapmode_pp_{good}_output_name$#!\\n"
        f"[ROOT.GetLocation.GetName]: [ROOT.GetLocation.MakeScope.ScriptValue('pp_{good}_output_raw')|2] = "
        f"[ShowGoodsName('{good}')|e] [output|e] x [market_access|e] (per month).\\n"
        "[market_access|e]: [ROOT.GetLocation.GetMarketAccess|2%V]."
    )
    if good == "marble":
        base += (
            "\\n#italic Marble is produced by dedicated [ShowBuildingTypeName('marble_quarry')|e] "
            "and [ShowBuildingTypeName('marble_saw_yard')|e] buildings.#!"
        )
    return base


def _ensure_icons(mod_root: Path, goods: Iterable[str], project: dict) -> None:
    vanilla_root = _vanilla_root(project)
    target = mod_root / IN_GAME_ICON_REL
    target.mkdir(parents=True, exist_ok=True)

    missing: list[str] = []
    for good in goods:
        destination = target / f"pp_{good}_output.dds"
        if destination.exists():
            continue
        source = vanilla_root / "game" / TRADE_GOOD_ICON_REL / f"icon_goods_{good}.dds"
        if source.is_file():
            shutil.copy2(source, destination)
        else:
            missing.append(good)

    if missing:
        raise FileNotFoundError("Missing icon source for goods: " + ", ".join(missing))


def _write_crlf(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="\r\n") as stream:
        stream.write(text)


if __name__ == "__main__":
    main()
