"""Location-window tooltips of the geography chips: what an attribute value does first, its goods output after.

View only: nothing here changes a game value. The engine lists every modifier line of a climate, vegetation or
topography class in one list, so the ~20 goods output rows of the World Builder fit bury the handful of effects a
player opens the chip for. For every attribute value with goods rows the constructor writes

- ``pp_tt_<attribute>_<value>``: a static modifier holding the value's other lines. It is never applied; the tooltip
  shows it with ``ShowModifierEffect``, so the engine formats it like any modifier list;
- the engine's non-modifier terrain lines (winter, movement cost, attacker penalty, ...) as one text block, worded from
  vanilla's own localization;
- a goods table: one icon and value per good, best first, a few per row.

The values are read back from the files the game loads (the class definitions with the mod's injects, the World
Builder static modifiers), so the view shows what applies. The location window is patched before those files are
written (geography sync), so it refers to the generated templates and types by name only.
"""

from __future__ import annotations

import re
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from pathlib import Path

from .modifiers import CLASS_DIRS

GUI_PATH = Path("in_game/gui/shared/pp_attribute_tooltips.gui")
MODIFIERS_PATH = Path("main_menu/common/static_modifiers/pp_attribute_tooltip_views.txt")
CUSTOM_LOC_PATH = Path("in_game/common/customizable_localization/pp_attribute_tooltips.txt")
LOCALIZATION_PATH = Path("main_menu/localization/english/pp_attribute_tooltips_l_english.yml")
VANILLA_TOOLTIPS = Path("game/in_game/gui/shared/location_tooltips.gui")
GENERATED = "# Generated by ppc worldbuilder (attribute_tooltips.py); do not edit by hand."

_LOC = "LocationView.GetLocation"
# vanilla tooltip template of each class chip; the geography sync points the chips at pp_attribute_tooltip_<attribute>
CLASS_TEMPLATES = {"topography": "Topography_tooltip", "climate": "Climate_tooltip", "vegetation": "Vegetation_tooltip"}
# The World Builder static modifiers behind the other chips, and how the location window tells which one applies.
SHORE_GATES = {"pp_wb_coastal": ("coast", f"{_LOC}.IsCoastal"), "pp_wb_lake": ("lake", f"EqualTo_string({_LOC}.Custom('ha1300_native_lake'), Localize('HA1300_LAKESIDE'))")}
CELLS_PER_ROW = 5
_OUTPUT = re.compile(r"local_(\w+)_output_modifier")


# --- reading the files the game loads ------------------------------------------------------------------------------

_TOKENS = re.compile(r'"[^"\n]*"|[{}]|[<>!]?=|[^\s{}=<>!"]+')
_COLOUR_LITERALS = {"rgb", "hsv", "hsv360", "hex"}
_PREFIX = re.compile(r"^(?:(?P<mode>TRY_INJECT|INJECT_OR_CREATE|INJECT|TRY_REPLACE|REPLACE_OR_CREATE|REPLACE):)?(?P<key>\w+)$")

Block = list[tuple[str | None, "str | Block"]]


def parse(text: str) -> Block:
    """A Paradox script file as nested ``(key, value)`` lists; bare list items have the key ``None``.

    Comments are cut at ``#`` without regard to quotes; the class and static-modifier files carry no ``#`` in strings.
    """
    tokens = _TOKENS.findall(re.sub(r"#[^\n]*", "", text))
    pos = 0

    def value() -> str | Block:
        nonlocal pos
        token = tokens[pos]
        pos += 1
        if token == "{":
            return block()
        if token in _COLOUR_LITERALS and pos < len(tokens) and tokens[pos] == "{":
            pos += 1
            return block()
        return token.strip('"')

    def block() -> Block:
        nonlocal pos
        items: Block = []
        while pos < len(tokens):
            token = tokens[pos]
            if token == "}":
                pos += 1
                return items
            if pos + 1 < len(tokens) and tokens[pos + 1].endswith("="):
                pos += 2
                items.append((token, value()))
            else:
                items.append((None, value()))
        return items

    return block()


def game_files(vanilla_root: Path | None, mod_root: Path, rel: str) -> list[Path]:
    """The files the game loads from one folder: vanilla's, each replaced by the mod's file of the same name, plus the
    mod's own; in name order."""
    files: dict[str, Path] = {}
    for root in ([Path(vanilla_root) / "game"] if vanilla_root is not None else []) + [Path(mod_root)]:
        folder = root / rel
        if folder.is_dir():
            for path in folder.glob("*.txt"):
                files[path.name] = path
    return [files[name] for name in sorted(files)]


def definitions(paths: Iterable[Path]) -> dict[str, Block]:
    """Top-level blocks after the database prefixes: a plain or replacing definition sets the block, an inject adds its
    lines. The engine ignores an inject into a block the mod replaced (modifiers.py folds such injects into the
    replacement), so those are dropped here too."""
    defs: dict[str, Block] = {}
    replaced: set[str] = set()
    for path in paths:
        for key, body in parse(path.read_text(encoding="utf-8-sig")):
            match = _PREFIX.match(key or "")
            if match is None or not isinstance(body, list):
                continue
            mode, name = match["mode"], match["key"]
            if mode in ("TRY_INJECT", "INJECT", "INJECT_OR_CREATE"):
                if name in defs and name not in replaced:
                    defs[name] = defs[name] + body
                elif name not in defs and mode == "INJECT_OR_CREATE":
                    defs[name] = list(body)
                continue
            if mode in ("TRY_REPLACE", "REPLACE") and name not in defs:
                continue
            defs[name] = list(body)
            if mode:
                replaced.add(name)
    return defs


def _number(text: str) -> float | None:
    try:
        return float(text)
    except ValueError:
        return None


def _fmt(value: float) -> str:
    text = f"{value:.6f}".rstrip("0").rstrip(".")
    return text if text not in ("", "-0") else "0"


def modifier_lines(body: Block, nested: str | None = None) -> dict[str, str]:
    """The effective lines of a modifier: every ``nested`` block of the definition (or the definition's own lines),
    numbers summed per key, lines that cancel out dropped."""
    lines: dict[str, float | str] = {}
    blocks = [value for key, value in body if key == nested and isinstance(value, list)] if nested else [body]
    for block in blocks:
        for key, value in block:
            if key is None or key == "game_data" or isinstance(value, list):
                continue
            number = _number(value)
            if number is None:
                lines[key] = value
            elif isinstance(lines.get(key, 0.0), float):
                lines[key] = lines.get(key, 0.0) + number
    return {key: _fmt(value) if isinstance(value, float) else value for key, value in lines.items() if value not in ("no", "0") and not (isinstance(value, float) and abs(value) < 1e-9)}


def scalars(body: Block) -> dict[str, str]:
    return {key: value for key, value in body if key is not None and isinstance(value, str)}


def goods_keys(vanilla_root: Path | None, mod_root: Path) -> set[str]:
    return set(definitions(game_files(vanilla_root, mod_root, "in_game/common/goods")))


def vanilla_localization(vanilla_root: Path | None, keys: Iterable[str]) -> dict[str, str]:
    wanted = set(keys)
    found: dict[str, str] = {}
    if vanilla_root is None:
        return found
    for path in sorted((Path(vanilla_root) / "game/main_menu/localization/english").glob("*.yml")):
        for match in re.finditer(r'^\s*(\w+):\d*\s*"(.*)"\s*$', path.read_text(encoding="utf-8-sig"), flags=re.MULTILINE):
            if match[1] in wanted:
                found.setdefault(match[1], match[2])
    return found


# --- the view -------------------------------------------------------------------------------------------------------

@dataclass(frozen=True)
class View:
    attribute: str                   # chip: climate, vegetation, topography, fertility, soil, coast, lake
    value: str                       # class key, fertility or soil class, or the shore modifier
    gate: str                        # GUI test: the location has this value
    name: str                        # localization naming the value
    effects: dict[str, str]          # the value's lines without goods output
    goods: list[tuple[str, float]]   # goods output, best first
    extras: list[str] = ()           # the engine's non-modifier terrain lines, localized

    @property
    def modifier(self) -> str:
        return f"pp_tt_{self.attribute}_{self.value}"

    @property
    def extras_key(self) -> str:
        return f"PP_TT_EXTRAS_{self.attribute}_{self.value}".upper()


def split_goods(lines: Mapping[str, str], goods: set[str]) -> tuple[dict[str, str], list[tuple[str, float]]]:
    """(effects, goods output best first): output lines of real goods move to the table, everything else stays."""
    effects: dict[str, str] = {}
    output: list[tuple[str, float]] = []
    for key, value in lines.items():
        match = _OUTPUT.fullmatch(key)
        number = _number(value)
        if match and match[1] in goods and number is not None:
            output.append((match[1], number))
        else:
            effects[key] = value
    return effects, sorted(output, key=lambda item: (-item[1], item[0]))


# Terrain fields the engine prints in a class tooltip, in its order, with the vanilla localization that words them.
# Movement cost is a multiplier; the line shows how far it is from normal ground.
TERRAIN_LINES = (
    ("movement_cost", "TERRAIN_MOVEMENT_COST", lambda v: v - 1.0),
    ("defender", "TERRAIN_ATTACKER_PENALTY", lambda v: v),
    ("proximity", "TERRAIN_PROXIMITY_COST", lambda v: v),
    ("colonial_migration_size_modifier", "TERRAIN_COLONIAL_MIGRATION", lambda v: v),
)
TERRAIN_FLAGS = (("can_freeze_over", "TERRAIN_CAN_FREEZE_OVER"), ("blocked_in_winter", "TERRAIN_BLOCKS_IN_WINTER"))
WINTER_KEY = "CLIMATE_TT_WINTER"
EXTRA_KEYS = [key for _, key, _ in TERRAIN_LINES] + [key for _, key in TERRAIN_FLAGS] + [WINTER_KEY]


def format_value(value: float, flags: str) -> str:
    """A number as the game's ``$VALUE|flags$`` shows it: ``%`` percent, ``=`` explicit plus, ``+``/``-`` green when
    the value is positive/negative."""
    shown = value * 100 if "%" in flags else value
    text = f"{shown:.1f}".rstrip("0").rstrip(".")
    text = ("+" + text if "=" in flags and shown > 0 else text) + ("%" if "%" in flags else "")
    good = (shown > 0) if "+" in flags else (shown < 0) if "-" in flags else None
    if good is None or shown == 0:
        return text
    return f"#{'P' if good else 'N'} {text}#!"


def _substitute(text: str, value: float) -> str:
    return re.sub(r"\$VALUE(?:\|([^$]*))?\$", lambda m: format_value(value, m[1] or ""), text)


def terrain_lines(fields: Mapping[str, str], loc: Mapping[str, str]) -> list[str]:
    lines: list[str] = []
    if "winter" in fields and WINTER_KEY in loc:
        lines.append(loc[WINTER_KEY].replace("$MAX$", fields["winter"]))
    for field, key, shown in TERRAIN_LINES:
        number = _number(fields.get(field, ""))
        if number is not None and key in loc and abs(shown(number)) > 1e-9:
            lines.append(_substitute(loc[key], shown(number)))
    lines.extend(loc[key] for field, key in TERRAIN_FLAGS if fields.get(field) == "yes" and key in loc)
    return lines


def class_gate(attribute: str, key: str) -> str:
    return f"EqualTo_string({_LOC}.Custom('pp_tt_{attribute}'), Localize('{class_token(attribute, key)}'))"


def class_token(attribute: str, key: str) -> str:
    return f"PP_TT_KEY_{attribute}_{key}".upper()


def class_views(vanilla_root: Path | None, mod_root: Path, goods: set[str], loc: Mapping[str, str]) -> dict[str, list[View]]:
    views: dict[str, list[View]] = {}
    for attribute, directory in CLASS_DIRS.items():
        views[attribute] = []
        for key, body in definitions(game_files(vanilla_root, mod_root, f"in_game/common/{directory}")).items():
            effects, output = split_goods(modifier_lines(body, "location_modifier"), goods)
            views[attribute].append(View(attribute, key, class_gate(attribute, key), f"${key}$", effects, output, terrain_lines(scalars(body), loc)))
    return views


def static_views(vanilla_root: Path | None, mod_root: Path, goods: set[str]) -> dict[str, list[View]]:
    """Fertility, soil, coast and lake chips: the World Builder static modifiers, gated like the chips gate them."""
    defs = definitions(game_files(vanilla_root, mod_root, "main_menu/common/static_modifiers"))
    views: dict[str, list[View]] = {"fertility": [], "soil": [], "coast": [], "lake": []}
    for name, body in defs.items():
        if match := re.fullmatch(r"pp_wb_fertility_(\w+)", name):
            attribute, value = "fertility", match[1]
            gate = f"EqualTo_string({_LOC}.Custom('ha1300_fertility_name'), Localize('HA1300_FERTILITY_{value.upper()}'))"
        elif match := re.fullmatch(r"pp_wb_soil_(\w+)", name):
            attribute, value = "soil", match[1]
            gate = f"EqualTo_string({_LOC}.Custom('ha1300_soil_type_name'), Localize('HA1300_SOIL_{value.upper()}_TITLE'))"
        elif name in SHORE_GATES:
            (attribute, gate), value = SHORE_GATES[name], name.removeprefix("pp_wb_")
        else:
            continue
        effects, output = split_goods(modifier_lines(body), goods)
        views[attribute].append(View(attribute, value, gate, f"$STATIC_MODIFIER_NAME_{name}$", effects, output))
    return views


# --- GUI ------------------------------------------------------------------------------------------------------------

_TYPES = """\
\ttype pp_goods_output_table = TooltipListBase {
\t\tblockoverride "block_title" { text = "PP_TT_GOODS_OUTPUT" }
\t\tvbox = {
\t\t\tlayoutpolicy_horizontal = expanding
\t\t\tblock "rows" {}
\t\t}
\t}

\ttype pp_goods_output_row = TooltipManualTableField {
\t\tblockoverride "field_margin" { margin = { 10 0 } spacing = 4 }
\t\tblockoverride "field_content" {
\t\t\tblock "cells" {}
\t\t\texpand = {}
\t\t}
\t}

\t# fixed width, so the values line up in columns
\ttype pp_goods_output_cell = widget {
\t\tsize = { 70 30 }
\t\ticon = {
\t\t\tsize = { 24 24 }
\t\t\tposition = { 0 3 }
\t\t\tblock "good_icon" {}
\t\t}
\t\ttext_single = {
\t\t\tusing = text_single_template
\t\t\tposition = { 27 7 }
\t\t\tblock "good_value" {}
\t\t}
\t}
"""


def goods_table(goods: list[tuple[str, float]]) -> str:
    rows = []
    for start in range(0, len(goods), CELLS_PER_ROW):
        cells = " ".join(
            f'pp_goods_output_cell = {{ blockoverride "good_icon" {{ texture = "gfx/interface/icons/trade_goods/icon_goods_{good}.dds" '
            f'tooltip = "[ShowGoodsName(\'{good}\')]" }} blockoverride "good_value" {{ raw_text = "{format_value(value, "+=%")}" }} }}'
            for good, value in goods[start:start + CELLS_PER_ROW]
        )
        rows.append(f'\t\t\t\t\tpp_goods_output_row = {{ blockoverride "cells" {{ {cells} }} }}')
    return "\t\t\t\tpp_goods_output_table = { blockoverride \"rows\" {\n" + "\n".join(rows) + "\n\t\t\t\t} }"


def view_section(view: View) -> str:
    parts = []
    if view.effects:
        parts.append(f"\t\t\t\tTooltipStringPairList = {{ textcontext = \"[ShowModifierEffect('{view.modifier}')]\" }}")
    if view.extras:
        parts.append(f'\t\t\t\tTooltipTextBlock = {{ blockoverride "text" {{ text = "{view.extras_key}" }} }}')
    if view.goods:
        parts.append(goods_table(view.goods))
    body = "\n".join(parts)
    return f'\t\tTooltipContentSection = {{\n\t\t\tvisible = "[{view.gate}]"\n\t\t\tblockoverride "section_content" {{\n{body}\n\t\t\t}}\n\t\t}}'


def view_type(attribute: str, views: list[View]) -> str:
    sections = "\n".join(view_section(view) for view in views if view.effects or view.extras or view.goods)
    return f"\ttype pp_attribute_view_{attribute} = vbox {{\n\t\tlayoutpolicy_horizontal = expanding\n\t\tspacing = 10\n\t\tignoreinvisible = yes\n{sections}\n\t}}"


def _close(text: str, start: int) -> int:
    """Index just past the brace block opening at ``text[start] == '{'``; comments and strings are skipped."""
    depth, i = 0, start
    while i < len(text):
        char = text[i]
        if char == "#":
            i = text.find("\n", i)
            if i < 0:
                break
            continue
        if char == '"':
            i = text.index('"', i + 1)
        elif char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    raise ValueError("unbalanced braces")


def _template(gui: str, name: str) -> str:
    match = re.search(rf"^template {name} \{{", gui, flags=re.MULTILINE)
    if match is None:
        raise ValueError(f"vanilla location tooltips: template {name} not found")
    return gui[match.start():_close(gui, match.end() - 1)]


def class_template(gui: str, attribute: str) -> str:
    """Vanilla's class tooltip with its modifier list swapped for the view. The engine's own list stays for classes the
    view does not know (another mod's), where the location's key resolves to the fallback."""
    template = _template(gui, CLASS_TEMPLATES[attribute])
    content = re.search(r'blockoverride "tooltip_content" \{', template)
    if content is None:
        raise ValueError(f"{CLASS_TEMPLATES[attribute]}: no tooltip_content")
    end = _close(template, content.end() - 1)
    marker = template.find(".GetTooltip]", content.end(), end)
    if marker < 0:
        raise ValueError(f"{CLASS_TEMPLATES[attribute]}: no engine modifier list to replace")
    i = content.end()
    while True:   # the direct child of tooltip_content holding the engine list
        child = re.compile(r"\w+\s*=\s*\{").search(template, i, end)
        if child is None:
            raise ValueError(f"{CLASS_TEMPLATES[attribute]}: engine list not found among the content blocks")
        child_end = _close(template, child.end() - 1)
        if child.start() < marker < child_end:
            break
        i = child_end
    fallback = f'visible = "[EqualTo_string({_LOC}.Custom(\'pp_tt_{attribute}\'), Localize(\'PP_TT_KEY_NONE\'))]"'
    engine_list = template[child.start():child.end()] + f"\n                {fallback}" + template[child.end():child_end]
    swapped = template[:child.start()] + f"pp_attribute_view_{attribute} = {{}}\n            " + engine_list + template[child_end:]
    return swapped.replace(f"template {CLASS_TEMPLATES[attribute]} {{", f"template pp_attribute_tooltip_{attribute} {{", 1)


def render_gui(vanilla_gui: str, views: Mapping[str, list[View]]) -> str:
    templates = "\n\n".join(class_template(vanilla_gui, attribute) for attribute in CLASS_TEMPLATES)
    types = "\n\n".join(view_type(attribute, attribute_views) for attribute, attribute_views in views.items())
    header = f"{GENERATED}\n# The geography chips of the location window: effects first, goods output as an icon table after (view only)."
    return f"{header}\n\n{templates}\n\ntypes pp_attribute_tooltips\n{{\n{_TYPES}\n{types}\n}}\n"


# --- script and localization ---------------------------------------------------------------------------------------

def render_modifiers(views: Iterable[View]) -> str:
    blocks = [GENERATED, "# Tooltip views of the attribute chips (attribute_tooltips.py): never applied, only shown with ShowModifierEffect."]
    for view in views:
        if view.effects:
            lines = "\n".join(f"\t{key} = {value}" for key, value in view.effects.items())
            blocks.append(f"{view.modifier} = {{\n\tgame_data = {{ category = location }}\n{lines}\n}}")
    return "\n\n".join(blocks) + "\n"


def render_custom_localization(views: Mapping[str, list[View]]) -> str:
    blocks = [GENERATED]
    for attribute in CLASS_TEMPLATES:
        lines = [f"pp_tt_{attribute} = {{", "\ttype = location"]
        lines += [f"\ttext = {{ localization_key = {class_token(attribute, v.value)} trigger = {{ {attribute} = {v.value} }} }}" for v in views[attribute]]
        lines += ["\ttext = { localization_key = PP_TT_KEY_NONE fallback = yes }", "}"]
        blocks.append("\n".join(lines))
    return "\n\n".join(blocks) + "\n"


_LOC_NEWLINE = "\\n"   # a line break inside a localization string


def _yml(text: str) -> str:
    return text.replace('"', '\\"')


def render_localization(views: Mapping[str, list[View]]) -> str:
    lines = ["l_english:", f" {GENERATED}", ' PP_TT_GOODS_OUTPUT: "Goods Output"', ' PP_TT_KEY_NONE: "none"']
    for attribute_views in views.values():
        for view in attribute_views:
            if view.attribute in CLASS_TEMPLATES:
                lines.append(f' {class_token(view.attribute, view.value)}: "{view.value}"')
            if view.effects:
                lines.append(f' STATIC_MODIFIER_NAME_{view.modifier}: "{view.name}"')
            if view.extras:
                lines.append(f' {view.extras_key}: "{_LOC_NEWLINE.join(_yml(line) for line in view.extras)}"')
    return "\n".join(lines) + "\n"


def write(mod_root: Path, vanilla_root: Path | None) -> dict[str, int]:
    """Write the chip tooltips; run after the class injects and the World Builder static modifiers are written."""
    goods = goods_keys(vanilla_root, mod_root)
    loc = vanilla_localization(vanilla_root, EXTRA_KEYS)
    views = {**class_views(vanilla_root, mod_root, goods, loc), **static_views(vanilla_root, mod_root, goods)}
    vanilla_gui = (Path(vanilla_root) / VANILLA_TOOLTIPS).read_text(encoding="utf-8-sig")
    outputs = {
        GUI_PATH: render_gui(vanilla_gui, views),
        MODIFIERS_PATH: render_modifiers(view for attribute_views in views.values() for view in attribute_views),
        CUSTOM_LOC_PATH: render_custom_localization(views),
        LOCALIZATION_PATH: render_localization(views),
    }
    for rel, text in outputs.items():
        path = Path(mod_root) / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("﻿" + text, encoding="utf-8", newline="\n")
    return {attribute: sum(1 for v in attribute_views if v.goods) for attribute, attribute_views in views.items()}
