"""Location-window tooltips that list goods output apart from the other effects, and the land-potential chip.

View only: nothing here changes a game value. The engine lists every line of a modifier in one list, so the ~20-30
goods output rows of a climate, vegetation or topography class, a winter or a harvest bury the handful of effects a
player opens the tooltip for. For every such value the constructor writes

- ``pp_tt_<attribute>_<value>``: a static modifier holding the value's other lines. It is never applied; the tooltip
  shows it with ``ShowModifierEffect``, so the engine formats it like any modifier list;
- for the classes, the engine's non-modifier terrain lines (winter, movement cost, attacker penalty, ...) as one text
  block, worded from vanilla's own localization;
- a goods table, best first: one icon and value per good, or one row per value when many goods share it.

The land-potential chip sums the goods output of the land attributes (class, fertility, soil, coast, lake) per good
in script values and lists the goods in six labelled tiers. The GUI cannot sort by a value, so a script value puts each
good in a 2% step and a tier's line holds a cell per (good, step), steps best first, shown only in the good's step.
Only the (good, step) pairs that occur at some location get a cell (the attributes never change), which keeps the
tooltip at a few hundred cheap tests.

The values are read back from the files the game loads (the class definitions with the mod's injects, the static
modifiers), so the views show what applies. The location window is patched before those files are written (geography
sync), so it refers to the generated templates and types by name only.
"""

from __future__ import annotations

import math
import re
from collections import Counter
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from pathlib import Path

from prosper_or_perish_constructor import location_status

from .modifiers import CLASS_DIRS

GUI_PATH = Path("in_game/gui/shared/pp_attribute_tooltips.gui")
MODIFIERS_PATH = Path("main_menu/common/static_modifiers/pp_attribute_tooltip_views.txt")
SCRIPT_VALUES_PATH = Path("in_game/common/script_values/pp_land_potential.txt")
CUSTOM_LOC_PATH = Path("in_game/common/customizable_localization/pp_attribute_tooltips.txt")
LOCALIZATION_PATH = Path("main_menu/localization/english/pp_attribute_tooltips_l_english.yml")
VANILLA_TOOLTIPS = Path("game/in_game/gui/shared/location_tooltips.gui")
GENERATED = "# Generated by ppc worldbuilder (attribute_tooltips.py); do not edit by hand."

_LOC = "LocationView.GetLocation"
# Vanilla tooltip templates copied with their engine list swapped for a view: mod template, vanilla template, the
# data function of the engine list. The location window uses pp_attribute_tooltip_<attribute> in their place.
SWAPPED_TEMPLATES = {
    "topography": ("Topography_tooltip", ".GetTooltip]"),
    "climate": ("Climate_tooltip", ".GetTooltip]"),
    "vegetation": ("Vegetation_tooltip", ".GetTooltip]"),
    "winter": ("location_winter_tooltip", ".GetWinterDetails]"),
}
WINTER_LEVELS = ("mild", "normal", "severe")
# The World Builder static modifiers behind the other chips, and how the location window tells which one applies.
SHORE_GATES = {"pp_wb_coastal": ("coast", f"{_LOC}.IsCoastal"), "pp_wb_lake": ("lake", f"EqualTo_string({_LOC}.Custom('ha1300_native_lake'), Localize('HA1300_LAKESIDE'))")}
LAND_ATTRIBUTES = ("climate", "vegetation", "topography", "fertility", "soil", "coast", "lake")
CELLS_PER_ROW = 5
ICONS_PER_GROUP_ROW = 12
LOCATION_TEMPLATES = Path("in_game/map_data/location_templates.txt")
SETUP_MODIFIERS = Path("main_menu/setup/start/21_pp_wb_attribute_modifiers.txt")


@dataclass(frozen=True)
class Tier:
    key: str
    name: str
    low: int | None          # lowest percent in the tier (None: open)
    high: int | None         # first percent above the tier (None: open)
    icons_only: bool = False


# Land-potential steps: the rounded percent halved (2% per step), clamped. The top step holds +40% and more; the
# bottom one (-21% and less) is no tier's: the unsuited tier sorts by tens of percent instead (LOW_LINES).
STEP = 2
STEP_MIN, STEP_MAX = -11, 20
TIERS = (
    Tier("excellent", "Excellent", 20, None),
    Tier("good", "Good", 10, 20),
    Tier("fair", "Fair", 0, 10),
    Tier("marginal", "Marginal", -10, 0),
    Tier("poor", "Poor", -20, -10),
    # usually many goods and little to tell apart: icons only (value on hover), on two lines
    Tier("unsuited", "Unsuited", None, -20, icons_only=True),
)
# The unsuited tier's lines: floor(percent / 10), clamped; -3 is -21% to -30%, -4 is -31% and less, -2 is not unsuited.
LOW_LINES = (-3, -4)
LOW_MIN, LOW_MAX = -4, -2
_OUTPUT = re.compile(r"local_(\w+)_output_modifier")
_GOODS_ICON = "gfx/interface/icons/trade_goods/icon_goods_{good}.dds"


# --- reading the files the game loads ------------------------------------------------------------------------------

_TOKENS = re.compile(r'"[^"\n]*"|[{}]|[<>!]?=|[^\s{}=<>!"]+')
_COLOUR_LITERALS = {"rgb", "hsv", "hsv360", "hex"}
_PREFIX = re.compile(r"^(?:(?P<mode>TRY_INJECT|INJECT_OR_CREATE|INJECT|TRY_REPLACE|REPLACE_OR_CREATE|REPLACE):)?(?P<key>\w+)$")

Block = list[tuple[str | None, "str | Block"]]


def parse(text: str) -> Block:
    """A Paradox script file as nested ``(key, value)`` lists; bare list items have the key ``None``.

    Comments are cut at ``#`` without regard to quotes; the class and static-modifier files carry no ``#`` in strings.
    """
    tokens = _TOKENS.findall(re.sub(r"#[^\n]*", "", text))
    pos = 0

    def value() -> str | Block:
        nonlocal pos
        token = tokens[pos]
        pos += 1
        if token == "{":
            return block()
        if token in _COLOUR_LITERALS and pos < len(tokens) and tokens[pos] == "{":
            pos += 1
            return block()
        return token.strip('"')

    def block() -> Block:
        nonlocal pos
        items: Block = []
        while pos < len(tokens):
            token = tokens[pos]
            if token == "}":
                pos += 1
                return items
            if pos + 1 < len(tokens) and tokens[pos + 1].endswith("="):
                pos += 2
                items.append((token, value()))
            else:
                items.append((None, value()))
        return items

    return block()


def game_files(vanilla_root: Path | None, mod_root: Path, rel: str) -> list[Path]:
    """The files the game loads from one folder: vanilla's, each replaced by the mod's file of the same name, plus the
    mod's own; in name order."""
    files: dict[str, Path] = {}
    for root in ([Path(vanilla_root) / "game"] if vanilla_root is not None else []) + [Path(mod_root)]:
        folder = root / rel
        if folder.is_dir():
            for path in folder.glob("*.txt"):
                files[path.name] = path
    return [files[name] for name in sorted(files)]


def definitions(paths: Iterable[Path]) -> dict[str, Block]:
    """Top-level blocks after the database prefixes: a plain or replacing definition sets the block, an inject adds its
    lines. The engine ignores an inject into a block the mod replaced (modifiers.py folds such injects into the
    replacement), so those are dropped here too."""
    defs: dict[str, Block] = {}
    replaced: set[str] = set()
    for path in paths:
        for key, body in parse(path.read_text(encoding="utf-8-sig")):
            match = _PREFIX.match(key or "")
            if match is None or not isinstance(body, list):
                continue
            mode, name = match["mode"], match["key"]
            if mode in ("TRY_INJECT", "INJECT", "INJECT_OR_CREATE"):
                if name in defs and name not in replaced:
                    defs[name] = defs[name] + body
                elif name not in defs and mode == "INJECT_OR_CREATE":
                    defs[name] = list(body)
                continue
            if mode in ("TRY_REPLACE", "REPLACE") and name not in defs:
                continue
            defs[name] = list(body)
            if mode:
                replaced.add(name)
    return defs


def static_modifier_definitions(vanilla_root: Path | None, mod_root: Path) -> dict[str, Block]:
    """Static modifiers from both database folders; the in_game ones load after main_menu's (the mod injects its
    winter and harvest lines there)."""
    return definitions(game_files(vanilla_root, mod_root, "main_menu/common/static_modifiers") + game_files(vanilla_root, mod_root, "in_game/common/static_modifiers"))


def _number(text: str) -> float | None:
    try:
        return float(text)
    except ValueError:
        return None


def _fmt(value: float) -> str:
    text = f"{value:.6f}".rstrip("0").rstrip(".")
    return text if text not in ("", "-0") else "0"


def modifier_lines(body: Block, nested: str | None = None) -> dict[str, str]:
    """The effective lines of a modifier: every ``nested`` block of the definition (or the definition's own lines),
    numbers summed per key, lines that cancel out dropped."""
    lines: dict[str, float | str] = {}
    blocks = [value for key, value in body if key == nested and isinstance(value, list)] if nested else [body]
    for block in blocks:
        for key, value in block:
            if key is None or key == "game_data" or isinstance(value, list):
                continue
            number = _number(value)
            if number is None:
                lines[key] = value
            elif isinstance(lines.get(key, 0.0), float):
                lines[key] = lines.get(key, 0.0) + number
    return {key: _fmt(value) if isinstance(value, float) else value for key, value in lines.items() if value not in ("no", "0") and not (isinstance(value, float) and abs(value) < 1e-9)}


def scalars(body: Block) -> dict[str, str]:
    return {key: value for key, value in body if key is not None and isinstance(value, str)}


def goods_keys(vanilla_root: Path | None, mod_root: Path) -> set[str]:
    return set(definitions(game_files(vanilla_root, mod_root, "in_game/common/goods")))


def vanilla_localization(vanilla_root: Path | None, keys: Iterable[str]) -> dict[str, str]:
    wanted = set(keys)
    found: dict[str, str] = {}
    if vanilla_root is None:
        return found
    for path in sorted((Path(vanilla_root) / "game/main_menu/localization/english").glob("*.yml")):
        for match in re.finditer(r'^\s*(\w+):\d*\s*"(.*)"\s*$', path.read_text(encoding="utf-8-sig"), flags=re.MULTILINE):
            if match[1] in wanted:
                found.setdefault(match[1], match[2])
    return found


# --- the views ------------------------------------------------------------------------------------------------------

@dataclass(frozen=True)
class View:
    attribute: str                   # climate, vegetation, topography, fertility, soil, coast, lake, winter, harvest
    value: str                       # class key, fertility or soil class, winter level, harvest, shore modifier
    gate: str                        # GUI test: the location has this value
    name: str                        # localization naming the value
    effects: dict[str, str]          # the value's lines without goods output
    goods: list[tuple[str, float]]   # goods output, best first
    extras: list[str] = ()           # the engine's non-modifier terrain lines, localized
    trigger: str | None = None       # script trigger for the land potential (land attributes only)

    @property
    def modifier(self) -> str:
        return f"pp_tt_{self.attribute}_{self.value}"

    @property
    def extras_key(self) -> str:
        return f"PP_TT_EXTRAS_{self.attribute}_{self.value}".upper()


def split_goods(lines: Mapping[str, str], goods: set[str]) -> tuple[dict[str, str], list[tuple[str, float]]]:
    """(effects, goods output best first): output lines of real goods move to the table, everything else stays."""
    effects: dict[str, str] = {}
    output: list[tuple[str, float]] = []
    for key, value in lines.items():
        match = _OUTPUT.fullmatch(key)
        number = _number(value)
        if match and match[1] in goods and number is not None:
            output.append((match[1], number))
        else:
            effects[key] = value
    return effects, sorted(output, key=lambda item: (-item[1], item[0]))


# Terrain fields the engine prints in a class tooltip, in its order, with the vanilla localization that words them.
# Movement cost is a multiplier; the line shows how far it is from normal ground.
TERRAIN_LINES = (
    ("movement_cost", "TERRAIN_MOVEMENT_COST", lambda v: v - 1.0),
    ("defender", "TERRAIN_ATTACKER_PENALTY", lambda v: v),
    ("proximity", "TERRAIN_PROXIMITY_COST", lambda v: v),
    ("colonial_migration_size_modifier", "TERRAIN_COLONIAL_MIGRATION", lambda v: v),
)
TERRAIN_FLAGS = (("can_freeze_over", "TERRAIN_CAN_FREEZE_OVER"), ("blocked_in_winter", "TERRAIN_BLOCKS_IN_WINTER"))
WINTER_KEY = "CLIMATE_TT_WINTER"
EXTRA_KEYS = [key for _, key, _ in TERRAIN_LINES] + [key for _, key in TERRAIN_FLAGS] + [WINTER_KEY]


def format_value(value: float, flags: str) -> str:
    """A number as the game's ``$VALUE|flags$`` shows it: ``%`` percent, ``=`` explicit plus, ``+``/``-`` green when
    the value is positive/negative."""
    shown = value * 100 if "%" in flags else value
    text = f"{shown:.1f}".rstrip("0").rstrip(".")
    text = ("+" + text if "=" in flags and shown > 0 else text) + ("%" if "%" in flags else "")
    good = (shown > 0) if "+" in flags else (shown < 0) if "-" in flags else None
    if good is None or shown == 0:
        return text
    return f"#{'P' if good else 'N'} {text}#!"


def _substitute(text: str, value: float) -> str:
    return re.sub(r"\$VALUE(?:\|([^$]*))?\$", lambda m: format_value(value, m[1] or ""), text)


def terrain_lines(fields: Mapping[str, str], loc: Mapping[str, str]) -> list[str]:
    lines: list[str] = []
    if "winter" in fields and WINTER_KEY in loc:
        lines.append(loc[WINTER_KEY].replace("$MAX$", fields["winter"]))
    for field, key, shown in TERRAIN_LINES:
        number = _number(fields.get(field, ""))
        if number is not None and key in loc and abs(shown(number)) > 1e-9:
            lines.append(_substitute(loc[key], shown(number)))
    lines.extend(loc[key] for field, key in TERRAIN_FLAGS if fields.get(field) == "yes" and key in loc)
    return lines


def class_gate(attribute: str, key: str) -> str:
    return f"EqualTo_string({_LOC}.Custom('pp_tt_{attribute}'), Localize('{class_token(attribute, key)}'))"


def class_token(attribute: str, key: str) -> str:
    return f"PP_TT_KEY_{attribute}_{key}".upper()


def class_views(vanilla_root: Path | None, mod_root: Path, goods: set[str], loc: Mapping[str, str]) -> dict[str, list[View]]:
    views: dict[str, list[View]] = {}
    for attribute, directory in CLASS_DIRS.items():
        views[attribute] = []
        for key, body in definitions(game_files(vanilla_root, mod_root, f"in_game/common/{directory}")).items():
            effects, output = split_goods(modifier_lines(body, "location_modifier"), goods)
            views[attribute].append(View(attribute, key, class_gate(attribute, key), f"${key}$", effects, output, terrain_lines(scalars(body), loc), f"{attribute} = {key}"))
    return views


def static_views(defs: Mapping[str, Block], goods: set[str], harvests: Iterable[str]) -> dict[str, list[View]]:
    """Fertility, soil, coast and lake chips (the World Builder static modifiers, gated like the chips gate them), the
    winter levels and the harvests."""
    harvest_keys = set(harvests)
    views: dict[str, list[View]] = {"fertility": [], "soil": [], "coast": [], "lake": [], "winter": [], "harvest": []}
    for name, body in defs.items():
        trigger = f"has_location_modifier = {name}"
        if match := re.fullmatch(r"pp_wb_fertility_(\w+)", name):
            attribute, value = "fertility", match[1]
            gate = f"EqualTo_string({_LOC}.Custom('ha1300_fertility_name'), Localize('HA1300_FERTILITY_{value.upper()}'))"
        elif match := re.fullmatch(r"pp_wb_soil_(\w+)", name):
            attribute, value = "soil", match[1]
            gate = f"EqualTo_string({_LOC}.Custom('ha1300_soil_type_name'), Localize('HA1300_SOIL_{value.upper()}_TITLE'))"
        elif name in SHORE_GATES:
            (attribute, gate), value = SHORE_GATES[name], name.removeprefix("pp_wb_")
        elif (match := re.fullmatch(r"winter_(\w+)", name)) and match[1] in WINTER_LEVELS:
            attribute, value, trigger = "winter", match[1], None
            gate = class_gate("winter", value)
        elif name in harvest_keys:
            attribute, value, trigger = "harvest", name.removeprefix("pp_harvest_"), None
            gate = location_status.harvest_gate(name)
        else:
            continue
        effects, output = split_goods(modifier_lines(body), goods)
        views[attribute].append(View(attribute, value, gate, f"$STATIC_MODIFIER_NAME_{name}$", effects, output, trigger=trigger))
    return views


# --- GUI ------------------------------------------------------------------------------------------------------------

_TYPES = """\
\ttype pp_goods_output_table = TooltipListBase {
\t\tblockoverride "block_title" { text = "PP_TT_GOODS_OUTPUT" }
\t\tvbox = {
\t\t\tlayoutpolicy_horizontal = expanding
\t\t\tblock "rows" {}
\t\t}
\t}

\ttype pp_goods_output_row = TooltipManualTableField {
\t\tblockoverride "field_margin" { margin = { 10 0 } spacing = 4 }
\t\tblockoverride "field_content" {
\t\t\tblock "cells" {}
\t\t\texpand = {}
\t\t}
\t}

\t# fixed width, so the values line up in columns
\ttype pp_goods_output_cell = widget {
\t\tsize = { 70 30 }
\t\tbackground = {
\t\t\tusing = bg_round_corners
\t\t\talpha = 0.6
\t\t\tblock "highlight" { visible = no }
\t\t}
\t\ticon = {
\t\t\tsize = { 24 24 }
\t\t\tposition = { 2 3 }
\t\t\tblock "good_icon" {}
\t\t}
\t\ttext_single = {
\t\t\tusing = text_single_template
\t\t\tposition = { 29 7 }
\t\t\tblock "good_value" {}
\t\t}
\t}

\t# goods that share a value: the value once, then their icons
\ttype pp_goods_output_group_row = TooltipManualTableField {
\t\tblockoverride "field_margin" { margin = { 10 0 } spacing = 6 }
\t\tblockoverride "field_content" {
\t\t\ttext_single = {
\t\t\t\tusing = text_single_template
\t\t\t\tautoresize = no
\t\t\t\tsize = { 48 30 }
\t\t\t\talign = right|nobaseline
\t\t\t\tblock "group_value" {}
\t\t\t}
\t\t\thbox = {
\t\t\t\tspacing = 2
\t\t\t\tblock "group_icons" {}
\t\t\t}
\t\t\texpand = {}
\t\t}
\t}
"""


def _good_icon(good: str, size: int = 24) -> str:
    return f'icon = {{ size = {{ {size} {size} }} texture = "{_GOODS_ICON.format(good=good)}" tooltip = "[ShowGoodsName(\'{good}\')]" }}'


def goods_table(goods: list[tuple[str, float]]) -> str:
    """Best first. Goods with a value of their own get a cell each; when many share values (winters, harvests), each
    value gets one row with its goods' icons."""
    groups: list[tuple[float, list[str]]] = []
    for good, value in goods:
        if groups and groups[-1][0] == value:
            groups[-1][1].append(good)
        else:
            groups.append((value, [good]))
    rows = []
    if len(groups) * 2 <= len(goods):
        for value, members in groups:
            for start in range(0, len(members), ICONS_PER_GROUP_ROW):
                label = format_value(value, "+=%") if start == 0 else ""
                icons = " ".join(_good_icon(good) for good in members[start:start + ICONS_PER_GROUP_ROW])
                rows.append(f'\t\t\t\t\tpp_goods_output_group_row = {{ blockoverride "group_value" {{ raw_text = "{label}" }} blockoverride "group_icons" {{ {icons} }} }}')
    else:
        for start in range(0, len(goods), CELLS_PER_ROW):
            cells = " ".join(
                f'pp_goods_output_cell = {{ blockoverride "good_icon" {{ texture = "{_GOODS_ICON.format(good=good)}" tooltip = "[ShowGoodsName(\'{good}\')]" }} '
                f'blockoverride "good_value" {{ raw_text = "{format_value(value, "+=%")}" }} }}'
                for good, value in goods[start:start + CELLS_PER_ROW]
            )
            rows.append(f'\t\t\t\t\tpp_goods_output_row = {{ blockoverride "cells" {{ {cells} }} }}')
    return "\t\t\t\tpp_goods_output_table = { blockoverride \"rows\" {\n" + "\n".join(rows) + "\n\t\t\t\t} }"


def view_section(view: View) -> str:
    parts = []
    if view.effects:
        parts.append(f"\t\t\t\tTooltipStringPairList = {{ textcontext = \"[ShowModifierEffect('{view.modifier}')]\" }}")
    if view.extras:
        parts.append(f'\t\t\t\tTooltipTextBlock = {{ blockoverride "text" {{ text = "{view.extras_key}" }} }}')
    if view.goods:
        parts.append(goods_table(view.goods))
    body = "\n".join(parts)
    return f'\t\tTooltipContentSection = {{\n\t\t\tvisible = "[{view.gate}]"\n\t\t\tblockoverride "section_content" {{\n{body}\n\t\t\t}}\n\t\t}}'


def view_type(attribute: str, views: list[View]) -> str:
    sections = "\n".join(view_section(view) for view in views if view.effects or view.extras or view.goods)
    return f"\ttype pp_attribute_view_{attribute} = vbox {{\n\t\tlayoutpolicy_horizontal = expanding\n\t\tspacing = 10\n\t\tignoreinvisible = yes\n{sections}\n\t}}"


def _close(text: str, start: int) -> int:
    """Index just past the brace block opening at ``text[start] == '{'``; comments and strings are skipped."""
    depth, i = 0, start
    while i < len(text):
        char = text[i]
        if char == "#":
            i = text.find("\n", i)
            if i < 0:
                break
            continue
        if char == '"':
            i = text.index('"', i + 1)
        elif char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    raise ValueError("unbalanced braces")


def _template(gui: str, name: str) -> str:
    match = re.search(rf"^template {name} \{{", gui, flags=re.MULTILINE)
    if match is None:
        raise ValueError(f"vanilla location tooltips: template {name} not found")
    return gui[match.start():_close(gui, match.end() - 1)]


def swapped_template(gui: str, attribute: str) -> str:
    """Vanilla's tooltip template with its engine list swapped for the view. The engine list stays for values the view
    does not know (another mod's class, no winter), where the location's key resolves to the fallback."""
    vanilla, marker_text = SWAPPED_TEMPLATES[attribute]
    template = _template(gui, vanilla)
    content = re.search(r'blockoverride "tooltip_content" \{', template)
    if content is None:
        raise ValueError(f"{vanilla}: no tooltip_content")
    end = _close(template, content.end() - 1)
    marker = template.find(marker_text, content.end(), end)
    if marker < 0:
        raise ValueError(f"{vanilla}: no engine list ({marker_text}) to replace")
    i = content.end()
    while True:   # the direct child of tooltip_content holding the engine list
        child = re.compile(r"\w+\s*=\s*\{").search(template, i, end)
        if child is None:
            raise ValueError(f"{vanilla}: engine list not found among the content blocks")
        child_end = _close(template, child.end() - 1)
        if child.start() < marker < child_end:
            break
        i = child_end
    fallback = f'visible = "[EqualTo_string({_LOC}.Custom(\'pp_tt_{attribute}\'), Localize(\'PP_TT_KEY_NONE\'))]"'
    engine_list = template[child.start():child.end()] + f"\n                {fallback}" + template[child.end():child_end]
    swapped = template[:child.start()] + f"pp_attribute_view_{attribute} = {{}}\n            " + engine_list + template[child_end:]
    return swapped.replace(f"template {vanilla} {{", f"template pp_attribute_tooltip_{attribute} {{", 1)


def land_goods(views: Mapping[str, list[View]]) -> list[str]:
    """Goods with a land-attribute row anywhere, in name order."""
    return sorted({good for attribute in LAND_ATTRIBUTES for view in views.get(attribute, []) for good, _ in view.goods})


def land_rows(views: Mapping[str, list[View]]) -> dict[tuple[str, str], dict[str, float]]:
    return {(attribute, view.value): dict(view.goods) for attribute in LAND_ATTRIBUTES for view in views.get(attribute, [])}


def location_attributes(mod_root: Path) -> list[dict[str, str]]:
    """Every land location's attribute values as the game sets them up: climate, vegetation and topography from the
    location templates, fertility, soil, coast and lake from the setup's World Builder modifiers."""
    locations: dict[str, dict[str, str]] = {}
    templates, setup = Path(mod_root) / LOCATION_TEMPLATES, Path(mod_root) / SETUP_MODIFIERS
    if templates.is_file():
        for match in re.finditer(r"(?m)^(\w+)\s*=\s*\{([^\n]*)", templates.read_text(encoding="utf-8-sig")):
            locations[match[1]] = {a: m[1] for a in CLASS_DIRS if (m := re.search(rf"\b{a}\s*=\s*(\w+)", match[2]))}
    if setup.is_file():
        for match in re.finditer(r"(?ms)^\t(\w+) = \{(.*?)^\t\}", setup.read_text(encoding="utf-8-sig")):
            location = locations.setdefault(match[1], {})
            for key in re.findall(r'modifier = "(\w+)"', match[2]):
                for attribute in ("fertility", "soil"):
                    if key.startswith(f"pp_wb_{attribute}_"):
                        location[attribute] = key.removeprefix(f"pp_wb_{attribute}_")
                if key in SHORE_GATES:
                    location[SHORE_GATES[key][0]] = key.removeprefix("pp_wb_")
    return [location for location in locations.values() if "climate" in location]


def land_step(percent: int) -> int:
    """The step of a rounded percent, as ``pp_land_potential_step_<good>`` computes it."""
    return max(STEP_MIN, min(STEP_MAX, percent // STEP))


def land_low(percent: int) -> int:
    """The unsuited line of a rounded percent, as ``pp_land_potential_low_<good>`` computes it."""
    return max(LOW_MIN, min(LOW_MAX, math.floor(percent / 10)))


def occupied_percents(views: Mapping[str, list[View]], locations: list[dict[str, str]]) -> dict[str, set[int]]:
    """The rounded percents each good takes at some location. The attributes never change, so no other value can occur,
    and only these get a cell; without locations every percent is kept."""
    rows, goods = land_rows(views), land_goods(views)
    if not locations:
        return {good: set(range(-100, 101)) for good in goods}
    occupied: dict[str, set[int]] = {good: set() for good in goods}
    for combination in {tuple(sorted(location.items())) for location in locations}:
        for good in goods:
            occupied[good].add(round(sum(rows.get(item, {}).get(good, 0.0) for item in combination) * 100))
    return occupied


def tier_steps(tier: Tier) -> list[int]:
    """The tier's steps, best first (none for the unsuited tier, which has LOW_LINES)."""
    if tier.low is None:
        return []
    top = STEP_MAX if tier.high is None else tier.high // STEP - 1
    return list(range(top, tier.low // STEP - 1, -1))


def tier_cells(tier: Tier, occupied: Mapping[str, set[int]]) -> list[list[tuple[str, int]]]:
    """The tier's lines of (good, step or unsuited line) cells, best first, goods in name order within one."""
    if tier.low is None:
        return [[(good, line) for good in sorted(occupied) if any(p < tier.high and land_low(p) == line for p in occupied[good])] for line in LOW_LINES]
    steps = {good: {land_step(p) for p in percents if p >= tier.low and (tier.high is None or p < tier.high)} for good, percents in occupied.items()}
    return [[(good, step) for step in tier_steps(tier) for good in sorted(occupied) if step in steps[good]]]


def _percent(value: int) -> str:
    return f"+{value}%" if value > 0 else f"{value}%"


def tier_label(tier: Tier) -> str:
    if tier.low is None:
        return f"{tier.name}: {_percent(tier.high - 1)} or less"
    if tier.high is None:
        return f"{tier.name}: {_percent(tier.low)} or more"
    return f"{tier.name}: {_percent(tier.low)} to {_percent(tier.high - 1)}"


def _land_cell(good: str, position: int, icons_only: bool) -> str:
    potential = f"{_LOC}.MakeScope.ScriptValue('pp_land_potential_{good}')"
    kind = "low" if icons_only else "step"
    visible = f"EqualTo_int32(FixedPointToInt({_LOC}.MakeScope.ScriptValue('pp_land_potential_{kind}_{good}')), '(int32){position}')"
    rgo = f"And({_LOC}.HasRawMaterial, EqualTo_string({_LOC}.GetRawMaterial.GetKey, '{good}'))"
    if icons_only:
        return (f'pp_land_potential_icon = {{ visible = "[{visible}]" blockoverride "highlight" {{ visible = "[{rgo}]" }} '
                f'blockoverride "good_icon" {{ texture = "{_GOODS_ICON.format(good=good)}" tooltip = "[ShowGoodsName(\'{good}\')] [{potential}|+=%0]" }} }}')
    return (f'pp_land_potential_cell = {{ visible = "[{visible}]" blockoverride "highlight" {{ visible = "[{rgo}]" }} '
            f'blockoverride "good_icon" {{ texture = "{_GOODS_ICON.format(good=good)}" tooltip = "[ShowGoodsName(\'{good}\')]" }} '
            f'blockoverride "good_value" {{ raw_text = "[{potential}|+=%0]" }} }}')


def land_tier(tier: Tier, occupied: Mapping[str, set[int]]) -> str:
    """One labelled tier: its steps best first, each step's goods in name order; the icon-only tier on two lines."""
    hboxes = []
    for line in tier_cells(tier, occupied):
        cells = " ".join(_land_cell(good, position, tier.icons_only) for good, position in line)
        hboxes.append(f"hbox = {{ layoutpolicy_horizontal = expanding ignoreinvisible = yes spacing = 2 {cells} expand = {{}} }}")
    return (f'\t\t\t\t\t\tpp_land_potential_tier = {{ blockoverride "tier_title" {{ text = "PP_LAND_TIER_{tier.key.upper()}" }} '
            f'blockoverride "tier_lines" {{ {" ".join(hboxes)} }} }}')


_LAND_TYPES = """\
\ttype pp_land_potential_tier = TooltipListBase {
\t\tblockoverride "block_title" { block "tier_title" {} }
\t\tvbox = {
\t\t\tlayoutpolicy_horizontal = expanding
\t\t\tmargin = { 8 2 }
\t\t\tblock "tier_lines" {}
\t\t}
\t}

\t# fixed width, so the values line up in columns
\ttype pp_land_potential_cell = widget {
\t\tsize = { 56 28 }
\t\tbackground = {
\t\t\tusing = bg_round_corners
\t\t\talpha = 0.6
\t\t\tblock "highlight" { visible = no }
\t\t}
\t\ticon = {
\t\t\tsize = { 22 22 }
\t\t\tposition = { 2 3 }
\t\t\tblock "good_icon" {}
\t\t}
\t\ttext_single = {
\t\t\tusing = text_single_template
\t\t\tposition = { 26 6 }
\t\t\tblock "good_value" {}
\t\t}
\t}

\ttype pp_land_potential_icon = widget {
\t\tsize = { 26 28 }
\t\tbackground = {
\t\t\tusing = bg_round_corners
\t\t\talpha = 0.6
\t\t\tblock "highlight" { visible = no }
\t\t}
\t\ticon = {
\t\t\tsize = { 22 22 }
\t\t\tposition = { 2 3 }
\t\t\tblock "good_icon" {}
\t\t}
\t}
"""


def land_potential_chip(occupied: Mapping[str, set[int]]) -> str:
    """The chip: the goods in labelled tiers, best tier first; every tier is shown, so the rows read as a scale."""
    body = "\n".join(land_tier(tier, occupied) for tier in TIERS)
    return f"""{_LAND_TYPES}
\ttype pp_land_potential_chip = widget {{
\t\tname = "pp_land_potential_chip"
\t\tsize = {{ 30 30 }}
\t\ttooltipwidget = {{
\t\t\tContextualTooltipType = {{
\t\t\t\tblockoverride "title_text" {{ text = "PP_LAND_POTENTIAL_TITLE" }}
\t\t\t\tblockoverride "concept_link" {{ visible = yes text = "[goods|E]" }}
\t\t\t\tblockoverride "title_icon" {{
\t\t\t\t\twidget = {{
\t\t\t\t\t\tusing = tooltip_title_icon_size
\t\t\t\t\t\tbackground = {{ texture = "[GetClimateFrame({_LOC}.GetClimate)]" }}
\t\t\t\t\t\ticon = {{ using = tooltip_title_icon_size texture = "[GetConceptTexture('goods')]" }}
\t\t\t\t\t}}
\t\t\t\t}}
\t\t\t\tblockoverride "tooltip_content" {{
\t\t\t\t\tTooltipTextBlock = {{ blockoverride "text" {{ text = "PP_LAND_POTENTIAL_HELP" }} }}
\t\t\t\t\tvbox = {{
\t\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\t\tspacing = 2
{body}
\t\t\t\t\t}}
\t\t\t\t}}
\t\t\t}}
\t\t}}
\t\tbackground = {{ texture = "[GetClimateFrame({_LOC}.GetClimate)]" }}
\t\ticon = {{ size = {{ 24 24 }} parentanchor = center texture = "[GetConceptTexture('goods')]" }}
\t}}"""


def render_gui(vanilla_gui: str, views: Mapping[str, list[View]], occupied: Mapping[str, set[int]]) -> str:
    templates = "\n\n".join(swapped_template(vanilla_gui, attribute) for attribute in SWAPPED_TEMPLATES)
    types = "\n\n".join(view_type(attribute, attribute_views) for attribute, attribute_views in views.items())
    header = f"{GENERATED}\n# Location-window tooltips: effects first, goods output as an icon table after; the land-potential chip (view only)."
    return f"{header}\n\n{templates}\n\ntypes pp_attribute_tooltips\n{{\n{_TYPES}\n{land_potential_chip(occupied)}\n\n{types}\n}}\n"


# --- script and localization ---------------------------------------------------------------------------------------

def render_modifiers(views: Iterable[View]) -> str:
    blocks = [GENERATED, "# Tooltip views (attribute_tooltips.py): never applied, only shown with ShowModifierEffect."]
    for view in views:
        if view.effects:
            lines = "\n".join(f"\t{key} = {value}" for key, value in view.effects.items())
            blocks.append(f"{view.modifier} = {{\n\tgame_data = {{ category = location }}\n{lines}\n}}")
    return "\n\n".join(blocks) + "\n"


def render_script_values(views: Mapping[str, list[View]], locations: list[dict[str, str]] = ()) -> str:
    """Per good: the land attributes' goods output at this location (``pp_land_potential_<good>``) and its step
    (``pp_land_potential_step_<good>``: the rounded percent halved, clamped). Only read by the land-potential chip.
    Each attribute's classes are tested most common first, so a location usually matches early."""
    common = {attribute: Counter(location.get(attribute) for location in locations) for attribute in LAND_ATTRIBUTES}
    blocks = [GENERATED, "# Land potential (attribute_tooltips.py): goods output from climate, vegetation, topography, fertility, soil, coast and lake."]
    for good in land_goods(views):
        lines = [f"pp_land_potential_{good} = {{", "\tvalue = 0"]
        for attribute in LAND_ATTRIBUTES:
            terms = [(view.value, view.trigger, value) for view in views.get(attribute, []) for g, value in view.goods if g == good and view.trigger]
            terms.sort(key=lambda term: -common[attribute][term[0]])
            for index, (_, trigger, value) in enumerate(terms):
                lines.append(f"\t{'if' if index == 0 else 'else_if'} = {{ limit = {{ {trigger} }} add = {_fmt(value)} }}")
        lines.append("}")
        blocks.append("\n".join(lines))
        for kind, divisor, low, high in (("step", STEP, STEP_MIN, STEP_MAX), ("low", 10, LOW_MIN, LOW_MAX)):
            blocks.append(
                f"pp_land_potential_{kind}_{good} = {{\n\tvalue = pp_land_potential_{good}\n\tmultiply = 100\n\tround = yes\n"
                f"\tdivide = {divisor}\n\tfloor = yes\n\tmin = {low}\n\tmax = {high}\n}}"
            )
    return "\n\n".join(blocks) + "\n"


def render_custom_localization(views: Mapping[str, list[View]]) -> str:
    blocks = [GENERATED]
    for attribute in SWAPPED_TEMPLATES:
        trigger = "winter_level" if attribute == "winter" else attribute
        lines = [f"pp_tt_{attribute} = {{", "\ttype = location"]
        lines += [f"\ttext = {{ localization_key = {class_token(attribute, v.value)} trigger = {{ {trigger} = {v.value} }} }}" for v in views[attribute]]
        lines += ["\ttext = { localization_key = PP_TT_KEY_NONE fallback = yes }", "}"]
        blocks.append("\n".join(lines))
    return "\n\n".join(blocks) + "\n"


_LOC_NEWLINE = "\\n"   # a line break inside a localization string


def _yml(text: str) -> str:
    return text.replace('"', '\\"')


def render_localization(views: Mapping[str, list[View]]) -> str:
    lines = [
        "l_english:", f" {GENERATED}",
        ' PP_TT_GOODS_OUTPUT: "Goods Output"',
        ' PP_TT_KEY_NONE: "none"',
        ' PP_LAND_POTENTIAL_TITLE: "Land Potential"',
        ' PP_LAND_POTENTIAL_HELP: "How well the land here suits each good, from its [climate|e], [vegetation|e], [topography|e], soil and fertility, and a coast or lake shore; best first in each row. [winter|e], harvests and the raw material bonus come on top. The raw material produced here is highlighted."',
        *(f' PP_LAND_TIER_{tier.key.upper()}: "{tier_label(tier)}"' for tier in TIERS),
    ]
    for attribute_views in views.values():
        for view in attribute_views:
            if view.attribute in SWAPPED_TEMPLATES:
                lines.append(f' {class_token(view.attribute, view.value)}: "{view.value}"')
            if view.effects:
                lines.append(f' STATIC_MODIFIER_NAME_{view.modifier}: "{view.name}"')
            if view.extras:
                lines.append(f' {view.extras_key}: "{_LOC_NEWLINE.join(_yml(line) for line in view.extras)}"')
    return "\n".join(lines) + "\n"


def build_views(vanilla_root: Path | None, mod_root: Path) -> dict[str, list[View]]:
    goods = goods_keys(vanilla_root, mod_root)
    loc = vanilla_localization(vanilla_root, EXTRA_KEYS)
    harvest_file = Path(mod_root) / location_status.HARVEST_MODIFIERS
    harvests = location_status.harvest_modifiers(harvest_file.read_text(encoding="utf-8-sig")) if harvest_file.is_file() else []
    return {**class_views(vanilla_root, mod_root, goods, loc), **static_views(static_modifier_definitions(vanilla_root, mod_root), goods, harvests)}


def write(mod_root: Path, vanilla_root: Path | None) -> dict[str, int]:
    """Write the tooltips; run after the class injects and the World Builder static modifiers are written."""
    views = build_views(vanilla_root, mod_root)
    locations = location_attributes(mod_root)
    occupied = occupied_percents(views, locations)
    vanilla_gui = (Path(vanilla_root) / VANILLA_TOOLTIPS).read_text(encoding="utf-8-sig")
    outputs = {
        GUI_PATH: render_gui(vanilla_gui, views, occupied),
        MODIFIERS_PATH: render_modifiers(view for attribute_views in views.values() for view in attribute_views),
        SCRIPT_VALUES_PATH: render_script_values(views, locations),
        CUSTOM_LOC_PATH: render_custom_localization(views),
        LOCALIZATION_PATH: render_localization(views),
    }
    for rel, text in outputs.items():
        path = Path(mod_root) / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("﻿" + text, encoding="utf-8", newline="\n")
    report = {attribute: sum(1 for v in attribute_views if v.goods) for attribute, attribute_views in views.items()}
    report["land_potential_cells"] = sum(len(line) for tier in TIERS for line in tier_cells(tier, occupied))
    return report
