"""Terrain biomes for the World Builder classes and the river channels. Visual only.

EU5 1.4 paints each location's ground from the biome ``in_game/gfx/map/biome_definitions/biomes.txt`` gives its
climate, vegetation and topography (a definition lists the keys it applies to, repeated keys being alternatives). A
biome is a palette in ``in_game/gfx/terrain2/materials.txt``: 6 coast slots (one per topography, then the coastline
transition), rivers/lakes, borders/water transition, vegetation transition, climate transition, then the variation
slots that fill the location. A location whose keys no definition lists falls back to ``000`` (``default_biome``: one
plain material, no detail). The World Builder classes (``ha1300_*``) and the channel topographies (``pp_river_*``) are
keys vanilla does not know, so on the vanilla files about 16,500 locations were drawn plain.

The mod's copies of both files (``config/terrain_biomes.toml``):

* climate and topography classes are listed next to their vanilla parent in every definition (the World Builder
  families), the river channels next to ``narrows``: they look like their parent;
* each vegetation class gets one definition per vanilla climate group and terrain (flat, wet, rough). Its biome is the
  class's own where the combination has enough locations: a copy of the vanilla palette of its parent vegetation in
  that climate and terrain, whose variation slots follow the class pattern (conifer canopy, wet meadow with ponds, ...);
  rarer combinations take the class's biome of another terrain or a neighbouring climate group, else the parent's;
* on mountains and the special topographies the vegetation classes keep the parent's definitions.

Every location matches exactly one definition, as in vanilla.
"""

from __future__ import annotations

import re
import tomllib
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

RELATIVE_PATH = Path("in_game/gfx/map/biome_definitions/biomes.txt")
MATERIALS_PATH = Path("in_game/gfx/terrain2/materials.txt")
TEXTURE_ROOT = Path("in_game/gfx/terrain2/terrain_textures")
HEADER = ("# Generated by ppc worldbuilder apply from vanilla's biomes.txt and config/terrain_biomes.toml: World Builder "
          "classes and river channels next to their vanilla parent, own biomes for the vegetation classes. Do not edit by hand.\n")
MATERIALS_HEADER = ("# Generated by ppc worldbuilder apply from vanilla's materials.txt and config/terrain_biomes.toml: the mod's "
                    "materials and the vegetation classes' biomes are appended. Do not edit by hand.\n")
CHANNEL_PARENT = "narrows"
VARIATION_START = 10          # 6 coast slots, rivers/lakes, borders/water, vegetation transition, climate transition
SLOT_NAMES = ["coast flatland", "coast hills", "coast plateaus", "coast mountains", "coast wetlands", "coastline transition",
              "rivers/lakes", "borders/water transition", "transition vegetation", "transition climate"]
TERRAINS = ("flat", "wet", "rough")
FALLBACK_TERRAINS = {"flat": ("wet", "rough"), "wet": ("flat", "rough"), "rough": ("flat", "wet")}
_KEY_RE = re.compile(r"^(?P<indent>[ \t]*)(?P<attr>climate|vegetation|topography)[ \t]*=[ \t]*(?P<value>[A-Za-z0-9_]+)[ \t]*(#.*)?$")
_BLOCK_RE = re.compile(r"(?ms)^(?P<name>[A-Za-z0-9_]+)\s*=\s*\{(?P<body>[^{}]*)\}")
_TEMPLATE_RE = re.compile(r"(?m)^([\w.-]+)\s*=\s*\{([^{}]*)\}")
_ATTR_RE = re.compile(r"\b(climate|vegetation|topography)\s*=\s*([A-Za-z0-9_]+)")

Families = dict[str, dict[str, list[str]]]


# ------------------------------------------------------------------------------------------------ design
@dataclass(frozen=True)
class Design:
    minimum: int
    max_total: int
    own_biomes: bool
    groups: dict[str, list[str]]
    neighbours: dict[str, list[str]]
    tones: dict[str, dict[str, str]]
    terrain: dict[str, str]
    terrain_base: dict[str, str]
    classes: dict[str, list[str]]
    materials: dict[str, dict[str, str]]


def load_design(path: Path) -> Design:
    raw = tomllib.loads(Path(path).read_text(encoding="utf-8"))
    general = raw.get("general", {})
    groups = {g: list(v["climates"]) for g, v in raw["climate_groups"].items()}
    return Design(int(general.get("own_biome_minimum_locations", 50)), int(general.get("max_total_biomes", 191)),
                  bool(general.get("own_biomes", False)), groups,
                  {g: list(v.get("neighbours", [])) for g, v in raw["climate_groups"].items()},
                  {g: dict(v) for g, v in raw.get("tones", {}).items()}, dict(raw["terrain"]), dict(raw["terrain_base"]),
                  {k: list(v) for k, v in raw["classes"].items()}, {k: dict(v) for k, v in raw.get("materials", {}).items()})


def with_channels(families: Families, channel_topographies: list[str]) -> Families:
    out = {attr: {parent: list(children) for parent, children in parents.items()} for attr, parents in families.items()}
    narrows = out.setdefault("topography", {}).setdefault(CHANNEL_PARENT, [])
    narrows.extend(key for key in channel_topographies if key not in narrows)
    return out


def _child_to_parent(families: Families) -> dict[str, dict[str, str]]:
    return {attr: {c: p for p, cs in parents.items() for c in cs} for attr, parents in families.items()}


# ------------------------------------------------------------------------------------------------ biomes.txt
def widen(text: str, families: Families, *, skip_vegetation_in: set[str] = frozenset()) -> tuple[str, int]:
    """Add ``attr = child`` after every ``attr = parent`` line of a definition; returns (text, lines added).

    Vegetation children are not added to definitions that list a topography of ``skip_vegetation_in`` (their own
    definitions cover those)."""
    out: list[str] = []
    added = 0
    blocks = [(m.start(), m.end(), {v for a, v in _ATTR_RE.findall(re.sub(r"#[^\n]*", "", m["body"])) if a == "topography"})
              for m in _BLOCK_RE.finditer(text)]
    pos = 0
    for line in text.splitlines(keepends=True):
        start = pos
        pos += len(line)
        out.append(line)
        body = line.rstrip("\r\n")
        match = _KEY_RE.match(body)
        if not match:
            continue
        if match["attr"] == "vegetation" and skip_vegetation_in:
            topos = next((t for a, b, t in blocks if a <= start < b), set())
            if topos & skip_vegetation_in:
                continue
        ending = line[len(body):] or "\n"
        for child in families.get(match["attr"], {}).get(match["value"], []):
            out.append(f"{match['indent']}{match['attr']} = {child}{ending}")
            added += 1
    return "".join(out), added


def definitions(text: str) -> list[tuple[str, dict[str, set[str]], str]]:
    """``(name, {attr: keys}, biome)`` of every definition, comments removed."""
    clean = re.sub(r"#[^\n]*", "", text)
    out = []
    for block in _BLOCK_RE.finditer(clean):
        keys: dict[str, set[str]] = {}
        biome = ""
        for attr, value in re.findall(r"\b(climate|vegetation|topography|biome)\s*=\s*([A-Za-z0-9_\-]+)", block["body"]):
            if attr == "biome":
                biome = value
            else:
                keys.setdefault(attr, set()).add(value)
        out.append((block["name"], keys, biome))
    return out


def _templates(templates: str) -> list[tuple[str, dict[str, str]]]:
    return [(m[1], dict(_ATTR_RE.findall(m[2]))) for m in _TEMPLATE_RE.finditer(templates)]


def matching(defs, attrs: dict[str, str]) -> list[str]:
    """Names of the keyed definitions a location's keys match (the keyless default excluded)."""
    return [name for name, keys, _ in defs if keys and all(attrs.get(a) in values for a, values in keys.items())]


def plain_locations(text: str, templates: str) -> list[str]:
    """Locations of ``templates`` that only the keyless default definition matches."""
    defs = definitions(text)
    return [name for name, attrs in _templates(templates) if not matching(defs, attrs)]


# ------------------------------------------------------------------------------------------------ materials.txt
def _block_end(text: str, opening: int) -> int:
    """Index of the brace closing the block whose ``{`` is at ``opening`` (comments and strings skipped)."""
    depth, i, n = 0, opening, len(text)
    while i < n:
        ch = text[i]
        if ch == "#":
            nl = text.find("\n", i)
            i = n if nl < 0 else nl
            continue
        if ch == '"':
            i = text.find('"', i + 1) + 1
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    raise ValueError("unbalanced braces")


def _top_block(text: str, key: str) -> tuple[int, int]:
    match = re.search(rf"(?m)^﻿?{key}\s*=\s*\{{", text)
    if not match:
        raise ValueError(f"materials.txt: no top-level {key} block")
    opening = match.end() - 1
    return opening, _block_end(text, opening)


def parse_materials(text: str) -> tuple[list[str], dict[str, list[str]]]:
    """(material names, biome name -> material list) of a materials.txt."""
    m0, m1 = _top_block(text, "materials")
    b0, b1 = _top_block(text, "biomes")
    names = re.findall(r'name\s*=\s*"([^"]+)"', re.sub(r"#[^\n]*", "", text[m0:m1]))
    biome_lists = {}
    for match in re.finditer(r'name\s*=\s*"?([A-Za-z0-9_\-]+)"?\s*materials\s*=\s*\{([^}]*)\}', re.sub(r"#[^\n]*", "", text[b0:b1])):
        if match[1] in biome_lists:
            raise ValueError(f"materials.txt: biome {match[1]} defined twice")
        biome_lists[match[1]] = match[2].split()
    return names, biome_lists


# ------------------------------------------------------------------------------------------------ plan
@dataclass
class Plan:
    counts: dict[tuple[str, str, str], int]
    own: list[tuple[str, str, str]]
    resolved: dict[tuple[str, str, str], str]       # (class, group, terrain) -> biome name
    palettes: dict[str, list[str]]                   # own biome -> materials
    bases: dict[str, str]                            # own biome -> vanilla base biome


def own_name(cls: str, group: str, terrain: str) -> str:
    return f"pp_{cls.removeprefix('ha1300_veg_')}_{group}_{terrain}_biome"


def plan(design: Design, vanilla_biomes: str, vanilla_materials: dict[str, list[str]], families: Families,
         templates: str) -> Plan:
    child = _child_to_parent(families)
    group_of = {c: g for g, cs in design.groups.items() for c in cs}
    counts: Counter = Counter()
    for _, attrs in _templates(templates):
        cls = attrs.get("vegetation")
        if cls not in design.classes:
            continue
        group = group_of.get(child.get("climate", {}).get(attrs.get("climate"), attrs.get("climate")))
        terrain = design.terrain.get(child.get("topography", {}).get(attrs.get("topography"), attrs.get("topography")))
        if group and terrain:
            counts[(cls, group, terrain)] += 1
    order = {k: i for i, k in enumerate(design.classes)}
    gorder = {g: i for i, g in enumerate(design.groups)}
    candidates = sorted((k for k, n in counts.items() if n >= design.minimum),
                        key=lambda k: (-counts[k], order[k[0]], gorder[k[1]], TERRAINS.index(k[2])))
    room = design.max_total - len(vanilla_materials)
    own = sorted(candidates[:max(room, 0)], key=lambda k: (order[k[0]], gorder[k[1]], TERRAINS.index(k[2])))
    owned = set(own)
    vdefs = definitions(vanilla_biomes)
    resolved: dict[tuple[str, str, str], str] = {}
    for cls in design.classes:
        parent_veg = child.get("vegetation", {}).get(cls)
        for group in design.groups:
            for terrain in TERRAINS:
                key = (cls, group, terrain)
                choice = None
                tries = [(cls, group, terrain)] + [(cls, group, t) for t in FALLBACK_TERRAINS[terrain]]
                for neighbour in design.neighbours.get(group, []):
                    tries += [(cls, neighbour, terrain)] + [(cls, neighbour, t) for t in FALLBACK_TERRAINS[terrain]]
                # last: the class's own look from any climate group, the same terrain first
                tries += [(cls, g, terrain) for g in design.groups] + [(cls, g, t) for g in design.groups for t in FALLBACK_TERRAINS[terrain]]
                for t in tries:
                    if t in owned:
                        choice = own_name(*t)
                        break
                if choice is None:
                    choice = _vanilla_biome(vdefs, design.groups[group][0], design.terrain_base[terrain], parent_veg)
                resolved[key] = choice
    palettes, bases = {}, {}
    for cls, group, terrain in own:
        base = _vanilla_biome(vdefs, design.groups[group][0], design.terrain_base[terrain], child["vegetation"][cls])
        palette = list(vanilla_materials[base])
        if len(palette) <= VARIATION_START:
            raise ValueError(f"{base}: palette without variation slots")
        pattern = [design.tones.get(group, {}).get(token, token) for token in design.classes[cls]]
        for i in range(VARIATION_START, len(palette)):
            j = i - VARIATION_START
            if (terrain == "rough" and j % 3 == 2) or (terrain == "wet" and j % 3 == 1):
                continue
            palette[i] = pattern[j % len(pattern)]
        name = own_name(cls, group, terrain)
        palettes[name] = palette
        bases[name] = base
    return Plan(dict(counts), own, resolved, palettes, bases)


def _vanilla_biome(vdefs, climate: str, topography: str, vegetation: str | None) -> str:
    hits = [biome for name, keys, biome in vdefs if keys and all(
        {"climate": climate, "topography": topography, "vegetation": vegetation}.get(a) in v for a, v in keys.items())]
    if not hits:
        raise ValueError(f"no vanilla biome for {climate} / {topography} / {vegetation}")
    return hits[0]


# ------------------------------------------------------------------------------------------------ render
def biome_text(vanilla: str, families: Families, design: Design, the_plan: Plan) -> tuple[str, int]:
    own_topos = set(design.terrain)
    widened, added = widen(vanilla, families, skip_vegetation_in=own_topos | {
        c for t in own_topos for c in families.get("topography", {}).get(t, [])})
    children = families
    lines = ["\n\n########################################################################################################### "
             "PROSPER OR PERISH: WORLD BUILDER VEGETATION CLASSES\n"]
    for cls in design.classes:
        for group, climates in design.groups.items():
            for terrain in TERRAINS:
                topos = [t for t, r in design.terrain.items() if r == terrain]
                topos += [c for t in list(topos) for c in children.get("topography", {}).get(t, [])]
                clims = list(climates) + [c for cl in climates for c in children.get("climate", {}).get(cl, [])]
                body = [f"\tclimate = {c}" for c in clims] + [f"\tvegetation = {cls}"] + [f"\ttopography = {t}" for t in topos]
                body.append(f"\tbiome = {the_plan.resolved[(cls, group, terrain)]}")
                name = f"pp_{cls.removeprefix('ha1300_veg_')}_{group}_{terrain}"
                lines.append(f"\n{name} =\n{{\n" + "\n".join(body) + "\n}\n")
    return widened.rstrip("\n") + "\n" + "".join(lines), added


def materials_text(vanilla: str, design: Design, the_plan: Plan) -> str:
    m0, m1 = _top_block(vanilla, "materials")
    blocks = []
    for name, files in design.materials.items():
        blocks.append(f'\n\t#### Prosper or Perish\n\t{{\n\t\tname = \t\t"{name}"\n\t\tdiffuse =\t"{files["diffuse"]}"\n'
                      f'\t\tnormal =\t"{files["normal"]}"\n\t\tproperties =\t"{files["properties"]}"\n\t}}\n')
    text = vanilla[:m1] + "".join(blocks) + vanilla[m1:]
    b0, b1 = _top_block(text, "biomes")
    entries = ["\n########################################################################################################### "
               "PROSPER OR PERISH: WORLD BUILDER VEGETATION CLASSES\n"]
    for name, palette in the_plan.palettes.items():
        slots = []
        for i, material in enumerate(palette):
            label = SLOT_NAMES[i] if i < VARIATION_START else f"variation {i - VARIATION_START + 1}"
            slots.append(f"\t\t\t{material}\t#{label}")
        entries.append(f"\n\t{{\n\t\tname = {name}\t# from {the_plan.bases[name]}\n\t\tmaterials = {{\n" + "\n".join(slots)
                       + "\n\t\t}\n\t}\n")
    return text[:b1] + "".join(entries) + text[b1:]


# ------------------------------------------------------------------------------------------------ checks
def check(biomes_text: str, materials: str, templates: str) -> dict[str, object]:
    """Quality checks of a generated pair; raises on a broken reference."""
    names, palettes = parse_materials(materials)
    defs = definitions(biomes_text)
    missing_biomes = sorted({b for _, keys, b in defs if b and b not in palettes})
    missing_materials = sorted({m for p in palettes.values() for m in p if m not in names})
    duplicate_materials = sorted(n for n, c in Counter(names).items() if c > 1)
    duplicate_definitions = [n for n, c in Counter(n for n, _, _ in defs).items() if c > 1]
    if missing_biomes or missing_materials or duplicate_materials or duplicate_definitions:
        raise ValueError(f"terrain biomes broken: biomes {missing_biomes} materials {missing_materials} duplicate "
                         f"materials {duplicate_materials} definitions {duplicate_definitions}")
    plain, multiple = [], []
    used = Counter()
    for name, attrs in _templates(templates):
        hits = matching(defs, attrs)
        if not hits:
            plain.append(name)
        elif len(hits) > 1:
            multiple.append(name)
        else:
            used[next(b for n, _, b in defs if n == hits[0])] += 1
    return {"biomes": len(palettes), "materials": len(names), "definitions": len(defs), "plain_locations": len(plain),
            "plain_sample": plain[:12], "ambiguous": multiple, "biomes_in_use": len(used)}


# ------------------------------------------------------------------------------------------------ write
def write(vanilla_root: Path, mod_root: Path, families: Families, channel_topographies: list[str],
          design: Design | None = None) -> dict[str, object]:
    game = Path(vanilla_root) / "game"
    vanilla_biomes = (game / RELATIVE_PATH).read_text(encoding="utf-8-sig")
    full = with_channels(families, channel_topographies)
    templates_path = Path(mod_root) / "in_game/map_data/location_templates.txt"
    templates = templates_path.read_text(encoding="utf-8-sig") if templates_path.is_file() else ""
    report: dict[str, object] = {}
    if design is None or not design.own_biomes:
        # parent looks only: vanilla's definitions and biomes, no materials.txt override
        biomes_out, added = widen(vanilla_biomes, full)
        vanilla_defs = len(definitions(vanilla_biomes))
        if len(definitions(biomes_out)) != vanilla_defs:
            raise ValueError("parent-only biomes.txt must keep vanilla's definitions")
        _write(Path(mod_root) / RELATIVE_PATH, HEADER + biomes_out)
        stale = Path(mod_root) / MATERIALS_PATH
        if stale.is_file() and stale.read_text(encoding="utf-8-sig").startswith(MATERIALS_HEADER[:40]):
            stale.unlink()
            report["removed_materials_override"] = True
        report.update({"mode": "parent_only", "keys_added": added, "definitions": vanilla_defs})
        if templates:
            report["plain_before"] = len(plain_locations(vanilla_biomes, templates))
            report["plain_after"] = len(plain_locations(biomes_out, templates))
            defs_out = definitions(biomes_out)
            unexpected = sorted(set(n for n, a in _templates(templates) if len(matching(defs_out, a)) > 1)
                                - set(parent_ambiguous(vanilla_biomes, templates, full)))
            if unexpected:
                raise ValueError(f"locations matching several biome definitions: {unexpected[:12]}")
        return report
    vanilla_materials = (game / MATERIALS_PATH).read_text(encoding="utf-8-sig")
    _, vanilla_palettes = parse_materials(vanilla_materials)
    the_plan = plan(design, vanilla_biomes, vanilla_palettes, full, templates)
    biomes_out, added = biome_text(vanilla_biomes, full, design, the_plan)
    materials_out = materials_text(vanilla_materials, design, the_plan)
    missing = sorted(f for files in design.materials.values() for f in files.values() if not (game / TEXTURE_ROOT / f).is_file())
    if missing:
        raise ValueError(f"terrain materials point at missing textures: {missing}")
    checks = check(biomes_out, materials_out, templates)
    if checks["biomes"] > design.max_total:
        raise ValueError(f"{checks['biomes']} biomes exceed max_total_biomes {design.max_total}")
    unexpected = sorted(set(checks.pop("ambiguous")) - set(parent_ambiguous(vanilla_biomes, templates, full)))
    if unexpected:
        raise ValueError(f"locations matching several biome definitions: {unexpected[:12]}")
    _write(Path(mod_root) / RELATIVE_PATH, HEADER + biomes_out)
    _write(Path(mod_root) / MATERIALS_PATH, MATERIALS_HEADER + materials_out)
    report.update({"keys_added": added, "own_biomes": len(the_plan.own),
                   "own_biome_locations": sum(the_plan.counts[k] for k in the_plan.own),
                   "class_locations": sum(the_plan.counts.values()), **checks})
    if templates:
        report["plain_with_vanilla_files"] = len(plain_locations(vanilla_biomes, templates))
    return report


def parent_ambiguous(vanilla_biomes: str, templates: str, families: Families) -> list[str]:
    """Locations whose keys, mapped to their vanilla parents, match several vanilla definitions (a vanilla quirk)."""
    defs = definitions(vanilla_biomes)
    child = _child_to_parent(families)
    out = []
    for name, attrs in _templates(templates):
        parent = {a: child.get(a, {}).get(v, v) for a, v in attrs.items()}
        if len(matching(defs, parent)) > 1:
            out.append(name)
    return out


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    data = "﻿" + content
    if not path.is_file() or path.read_text(encoding="utf-8") != data:
        path.write_text(data, encoding="utf-8", newline="")
