"""Improvement buildings, farm land costs and game-start setup from the World Builder contract.

Improvement buildings (one per World Builder ledger type, mapped to blueprint keys in constructor.toml):
- ``raw_modifier local_population_capacity`` = people per level / 1000 (unscaled by staffing);
- ``max_levels = pp_wb_cap_<key>``: a script value = base + attribute class terms + levels per development
  point x development, floored, clamped to the level limit; classes are tested with the location's own
  climate/vegetation/topography, the ``pp_wb_fertility_*`` / ``pp_wb_soil_*`` static modifiers (placed in the
  game-start setup, so they already exist when the engine validates starting levels), the river size
  modifier, coast and lake;
- ``location_potential``: the World Builder gate (OR of ANDs over the same attributes);
- starting levels written to ``main_menu/setup/1337/14_pp_worldbuilder_buildings.txt`` for owned locations.

Niche buildings (``[worldbuilder.buildings.niche]``: culture- or country-locked vanilla buildings such as the Khmer
baray) keep their lock and join a general family: every member carries a level counter
(``raw_modifier pp_wb_levels_<key> = 1``) and its max is the family's cap equation minus the other members' levels,
so a location never holds two full sets of the same idea. A niche level is worth ``strength`` x the family's people
per level. A member with ``upgrades = <key>`` is a later tier of that building: its blueprint says ``obsolete = <key>``,
so each level built converts one lower-tier level, and its cap leaves the lower tiers' levels out (as the farm upgrade
chains do). Their blueprints must be full ``REPLACE`` or new ``CREATE`` definitions (the lock, the gate and the level formula cannot be
injected). ``vanilla_capacity_leaks`` lists vanilla buildings with capacity lines that the mod does not REPLACE.

Farm buildings (the mod's rural land users) take farmland: ``raw_modifier local_population_capacity = -land``
per level; their max level is generated by ``scripts/generate_rural_capacity_values.py`` from the same constants.
Levels and people per level may be rescaled per building with ``[worldbuilder.level_scale]`` (multiply
levels, divide people per level).
"""

from __future__ import annotations

import json
import math
import re
from collections.abc import Mapping
from pathlib import Path

import polars as pl
import yaml

from prosper_or_perish_constructor.worldbuilder.contract import Contract, WorldBuilderConfig, units
from prosper_or_perish_constructor import yaml_io
from prosper_or_perish_constructor.setup_layout import LEGACY_SETUP_DIR, SETUP_DIR

CAPS_PATH = Path("in_game/common/script_values/pp_wb_building_caps.txt")
SETUP_PATH = SETUP_DIR / "14_pp_worldbuilder_buildings.txt"
LEGACY_SETUP = (str(LEGACY_SETUP_DIR / "14_pp_population_irrigation.txt"),)
BLUEPRINTS = Path("blueprints/accepted/buildings")
MANIFEST = Path("blueprints/buildings.manifest.yml")
GENERATED = "# Generated by ppc worldbuilder from the World Builder handover; do not edit by hand."
ATTRIBUTE_TRIGGERS = {
    "location_tag": "this = location:{value}",
    "climate": "climate = {key}",
    "vegetation": "vegetation = {key}",
    "topography": "topography = {key}",
    "fertility": "has_location_modifier = pp_wb_fertility_{value}",   # placed in the setup, so valid during building validation
    "soil_type": "has_location_modifier = pp_wb_soil_{value}",
    "river_level": "has_location_modifier = river_flowing_through_{value}",
    "is_coastal": "is_coastal = yes",
    "is_adjacent_to_lake": "is_adjacent_to_lake = yes",
    "culture": "dominant_culture ?= culture:{value}",
    "province": "province_definition = province_definition:{value}",
}
# One class per location: the engine's climate/vegetation/topography, the setup's single fertility and soil modifier.
EXCLUSIVE_ATTRIBUTES = frozenset({"climate", "vegetation", "topography", "fertility", "soil_type"})
OTHER_CAPACITY_BLUEPRINTS = (
    "terraces", "irrigation_reservoirs", "aqueduct_system", "pound_lock_canal_infrastructure",
)
LEVELS_MODIFIER = "pp_wb_levels_{key}"
LEVELS_TYPES_PATH = Path("main_menu/common/modifier_type_definitions/pp_wb_building_levels.txt")
LEVELS_ICONS_PATH = Path("main_menu/common/modifier_icons/pp_wb_building_levels.txt")
LEVELS_LOC_PATH = Path("main_menu/localization/english/pp_wb_building_levels_l_english.yml")
_VANILLA_BUILDING_RE = re.compile(r"^(?P<key>[A-Za-z0-9_]+)\s*=\s*\{", re.MULTILINE)
_CAPACITY_LINE_RE = re.compile(r"^\s*local_population_capacity(?:_modifier)?\s*=", re.MULTILINE)
_RAW_MODIFIER_RE = re.compile(r"(?P<indent>[ \t]*)raw_modifier\s*=\s*\{(?P<body>.*?)\n(?P=indent)\}", re.DOTALL)
_MAX_LEVELS_RE = re.compile(r"^(?P<indent>[ \t]*)max_levels\s*=\s*\S+[ \t]*$", re.MULTILINE)
_POTENTIAL_RE = re.compile(r"(?P<indent>[ \t]*)location_potential\s*=\s*\{.*?\n(?P=indent)\}", re.DOTALL)


# River size as the caps read it. The engine's own river_flowing_through_N static modifier is invisible to
# has_location_modifier (only the ones pp_navigation_preserve_rivers adds where the engine traces no river are
# visible), so a cap row tested that way was missing in game wherever the engine traced the river itself (EU5 1.4
# start: irrigated fields on the Yangtze banks 8 levels and Taverns 1 level above max). Modifier values add up over
# static and script-added modifiers alike, and each river_flowing_through_N carries irrigant_cap_modifier = N
# (pp_location_modifier_adjustments.txt; start_simulation.run checks it).
RIVER_SIZE_MODIFIER = "irrigant_cap_modifier"
RIVER_SIZE_TRIGGERS_PATH = Path("in_game/common/scripted_triggers/pp_wb_river_size.txt")


def river_size_trigger(level: int | str) -> str:
    """The trigger a cap row uses for "the location's river has size ``level``" (1-5)."""
    return f"pp_wb_river_size_{int(level)} = yes"


def write_river_size_triggers(mod_root: Path) -> Path:
    """``pp_wb_river_size_1`` .. ``_5``: the river size read from ``modifier:irrigant_cap_modifier`` (see above)."""
    lines = [GENERATED, "# River size N <=> modifier:irrigant_cap_modifier = N (every river_flowing_through_N carries it). Read as a",
             "# modifier value, the engine's own river statics count too (has_location_modifier does not see them)."]
    for n in range(1, 6):
        lines.append(f"pp_wb_river_size_{n} = {{ modifier:{RIVER_SIZE_MODIFIER} > {n - 0.5} modifier:{RIVER_SIZE_MODIFIER} < {n + 0.5} }}")
    path = mod_root / RIVER_SIZE_TRIGGERS_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("﻿" + "\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return path


def _fmt(value: float) -> str:
    text = f"{value:.2f}".rstrip("0").rstrip(".")
    return text if text not in ("", "-0") else "0"


def _game_key(contract: Contract, attribute: str, value: str) -> str:
    rows = contract.attribute_rows.filter((pl.col("attribute") == attribute) & (pl.col("value") == value))
    return str(rows["game_key"][0]) if len(rows) and rows["game_key"][0] else value


def trigger_for(contract: Contract, attribute: str, value: str, *, gate: bool = False) -> str:
    navigation = (contract.root / "navigation/manifest.json").exists()
    if attribute == "river_level" and gate:
        # A gate must hold while the game validates the setup buildings, before the engine applies the river-size
        # modifiers, so it uses the map-native trigger. The World Builder gates only ever ask for "any river"
        # (levels 1-5) or "no river"; the caps' per-size class terms keep the size modifiers below.
        return "has_river = no" if str(value) == "0" else "has_river = yes"
    if attribute == "river_level" and str(value) != "0":
        # cap rows read the river size as a modifier value (river_size_trigger): the engine's own river statics count
        return river_size_trigger(value)
    if attribute == "river_level" and navigation:
        return "pp_navigation_has_river = no"
    if attribute == "is_coastal" and navigation:
        # river banks next to navigable water are coastal to the engine; the sea coast is the setup-placed modifier
        trigger = "has_location_modifier = pp_wb_coastal"
        return trigger if str(value) == "True" else f"NOT = {{ {trigger} }}"
    template = ATTRIBUTE_TRIGGERS[attribute]
    if attribute in ("is_coastal", "is_adjacent_to_lake"):
        return template if str(value) == "True" else f"NOT = {{ {template} }}"
    if attribute == "river_level" and str(value) == "0":
        return "has_river = no"  # river_flowing_through_0 does not exist
    return template.format(key=_game_key(contract, attribute, value), value=value)


def gate_trigger(contract: Contract, rules: list[dict[str, list[str]]]) -> list[str]:
    """OR over rules, AND within a rule, as indented trigger lines (without the location_potential wrapper)."""
    if not rules:
        return ["always = yes"]
    ands: list[list[str]] = []
    for rule in rules:
        conditions: list[str] = []
        for attribute, allowed in rule.items():
            allowed = [str(a) for a in allowed]
            if not allowed:
                conditions.append("always = no")
                continue
            triggers = list(dict.fromkeys(trigger_for(contract, attribute, a, gate=True) for a in allowed))
            if len(triggers) == 1:
                conditions.append(triggers[0])
            else:
                conditions.append("OR = { " + " ".join(triggers) + " }")
        ands.append(conditions)
    if len(ands) == 1:
        return ands[0]
    lines = ["OR = {"]
    for conditions in ands:
        if len(conditions) == 1:
            lines.append(f"\t{conditions[0]}")
        else:
            lines.append("\tAND = {")
            lines.extend(f"\t\t{c}" for c in conditions)
            lines.append("\t}")
    lines.append("}")
    return lines


def cap_script_value(contract: Contract, key: str, equation: Mapping[str, object], scale: float, level_limit: int, *, name: str | None = None) -> str:
    base = float(equation["base_levels"]) * scale
    lines = [f"{name or f'pp_wb_cap_{key}'} = {{", "\tadd = {", '\t\tdesc = "BUILDING_LEVEL_WB_BASE"', f"\t\tvalue = {_fmt(base)}", "\t}"]
    previous = None
    for term in equation["class_terms"]:
        levels = float(term["levels"]) * scale
        if not levels:
            continue
        attribute, value = str(term["attribute"]), str(term["value"])
        # A location has one class per exclusive attribute: its terms chain, so the checks stop at the match.
        branch = "else_if" if attribute == previous and attribute in EXCLUSIVE_ATTRIBUTES else "if"
        previous = attribute
        lines.extend([
            f"\t{branch} = {{",
            f"\t\tlimit = {{ {trigger_for(contract, attribute, value)} }}",
            "\t\tadd = {",
            f'\t\t\tdesc = "BUILDING_LEVEL_WB_{attribute.upper()}_{value.upper()}"',
            f"\t\t\tvalue = {_fmt(levels)}",
            "\t\t}",
            "\t}",
        ])
    gamma = float(equation["levels_per_development_point"]) * scale
    if gamma:
        lines.extend(["\tadd = {", '\t\tdesc = "BUILDING_LEVEL_WB_DEVELOPMENT"', "\t\tvalue = development", f"\t\tmultiply = {gamma:.4f}".rstrip("0").rstrip("."), "\t}"])
    # Every operation needs a desc, or the breakdown tooltip shows a "missing key" line; no floor = yes, the engine
    # floors max_levels to whole levels itself (2026-10-01).
    lines.extend([_clamp("min", "MINIMUM", 0), _clamp("max", "MAXIMUM", int(round(level_limit * scale))), "}"])
    return "\n".join(lines)


def _clamp(op: str, label: str, value: object) -> str:
    """A described min/max line of a cap script value (BUILDING_LEVEL_WB_MINIMUM / _MAXIMUM)."""
    return f'\t{op} = {{ desc = "BUILDING_LEVEL_WB_{label}" value = {value} }}'


def families(cfg: WorldBuilderConfig) -> dict[str, list[str]]:
    """general blueprint key -> niche keys sharing its cap (only families with at least one niche member)."""
    out: dict[str, list[str]] = {}
    for key, spec in cfg.niche.items():
        out.setdefault(str(spec["family"]), []).append(key)
    return out


def lower_tiers(cfg: WorldBuilderConfig, key: str) -> list[str]:
    """The buildings ``key`` upgrades (the ``upgrades`` chain of its niche spec), nearest first."""
    chain: list[str] = []
    current = cfg.niche.get(key, {}).get("upgrades")
    while current and current not in chain:
        chain.append(current)
        current = cfg.niche.get(current, {}).get("upgrades")
    return chain


def shared_cap_value(name: str, source: str, siblings: list[str]) -> str:
    """``name`` = the family's cap equation minus the levels already used by the other family members."""
    lines = [f"{name} = {{", "\tadd = {", '\t\tdesc = "BUILDING_LEVEL_WB_FAMILY"', f"\t\tvalue = {source}", "\t}"]
    for sibling in siblings:
        lines.extend(["\tsubtract = {", f'\t\tdesc = "BUILDING_LEVEL_WB_SHARED_{sibling.upper()}"', f"\t\tvalue = modifier:{LEVELS_MODIFIER.format(key=sibling)}", "\t}"])
    lines.extend([_clamp("min", "MINIMUM", 0), "}"])
    return "\n".join(lines)


def write_level_counters(keys: list[str], mod_root: Path) -> None:
    """Modifier types (with icon and name) for the per-building level counters of shared families."""
    types = [GENERATED, "# Level counters of buildings that share a cap: raw_modifier pp_wb_levels_<key> = 1 per level.", ""]
    icons = [GENERATED, ""]
    loc = ["l_english:"]
    for key in keys:
        modifier = LEVELS_MODIFIER.format(key=key)
        types.extend([f"{modifier} = {{", "\tdecimals = 0", "\tgame_data = {", "\t\tcategory = location", "\t}", "}", ""])
        icons.extend([f"{modifier} = {{", f'\tpositive = "gfx/interface/icons/buildings/{key}.dds"', f'\tnegative = "gfx/interface/icons/buildings/{key}.dds"', "}", ""])
        loc.append(f'  MODIFIER_TYPE_NAME_{modifier}: "${key}$ levels"')
        loc.append(f'  MODIFIER_TYPE_DESC_{modifier}: "Levels of ${key}$ in this location. They count against the shared cap of every building of the same kind."')
    for path, lines in ((LEVELS_TYPES_PATH, types), (LEVELS_ICONS_PATH, icons), (LEVELS_LOC_PATH, loc)):
        target = mod_root / path
        if not keys:
            if target.is_file():
                target.unlink()
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("\ufeff" + "\n".join(lines).rstrip() + "\n", encoding="utf-8", newline="\n")


def write_caps(contract: Contract, cfg: WorldBuilderConfig, mod_root: Path) -> dict[str, dict[str, float]]:
    """Write the cap script values; return per building key {unit_people, unit_units, scale, limit, kind[, family, niche]}."""
    blocks: list[str] = []
    info: dict[str, dict[str, float]] = {}
    shared = families(cfg)
    for row in contract.building_types.iter_rows(named=True):
        kind = str(row["building"])
        key = cfg.building_map.get(kind)
        if key is None:
            raise ValueError(f"[worldbuilder.buildings.map] has no blueprint for World Builder type {kind!r}")
        scale = float(cfg.level_scale.get(key, cfg.level_scale.get(kind, 1.0)))
        equation = json.loads(str(row["cap_equation_json"]))
        limit = int(row.get("level_limit") or cfg.level_limit)
        people = float(row["unit_people_per_level"]) / scale
        info[key] = {"kind": kind, "unit_people": people, "unit_units": units(people), "scale": scale, "limit": int(round(limit * scale))}
        members = shared.get(key, [])
        if not members:
            blocks.append(cap_script_value(contract, key, equation, scale, limit))
            continue
        source = f"pp_wb_cap_{key}_shared"
        blocks.append(cap_script_value(contract, key, equation, scale, limit, name=source))
        blocks.append(shared_cap_value(f"pp_wb_cap_{key}", source, members))
        for niche in members:
            strength = float(cfg.niche[niche]["strength"])
            niche_people = people * strength
            lower = lower_tiers(cfg, niche)
            siblings = [m for m in (key, *members) if m != niche and m not in lower]
            block = shared_cap_value(f"pp_wb_cap_{niche}", source, siblings)
            if cfg.niche[niche].get("maximum_levels"):
                block = block[:-1] + _clamp("max", "MAXIMUM", int(cfg.niche[niche]["maximum_levels"])) + "\n}"
            blocks.append(block)
            info[niche] = {"kind": kind, "unit_people": niche_people, "unit_units": units(niche_people), "scale": scale, "limit": int(round(limit * scale)), "family": key, "strength": strength, "niche": True}
    missing = [n for n, spec in cfg.niche.items() if spec["family"] not in info]
    if missing:
        raise ValueError(f"[worldbuilder.buildings.niche] family is not a mapped general building: {', '.join(missing)}")
    counters = sorted({k for family, members in shared.items() for k in (family, *members)})
    write_level_counters(counters, mod_root)
    text = "\n\n".join([GENERATED, "# Improvement building level caps: base + attribute class terms + levels per development point x development.",
                          "# Families with niche members: <key>_shared is the equation; each member's cap subtracts the other members' levels.", *blocks]) + "\n"
    (mod_root / CAPS_PATH).parent.mkdir(parents=True, exist_ok=True)
    (mod_root / CAPS_PATH).write_text("﻿" + text, encoding="utf-8", newline="\n")
    write_river_size_triggers(mod_root)
    # tooltip rows for the cap values and the farm values
    keys = sorted(set(re.findall(r'desc = "(BUILDING_LEVEL_WB_[A-Z0-9_]+)"', text)))
    loc = ["l_english:", '  BUILDING_LEVEL_WB_BASE: "Base levels"', '  BUILDING_LEVEL_WB_DEVELOPMENT: "From [development|e]"',
           '  BUILDING_LEVEL_WB_FREE_FARMLAND: "Available Subsistence Land"', '  BUILDING_LEVEL_WB_MINIMUM: "Minimum"',
           '  BUILDING_LEVEL_WB_MAXIMUM: "Upper limit"', '  BUILDING_LEVEL_WB_FAMILY: "Capacity shared with related buildings"']
    fixed = ("BUILDING_LEVEL_WB_BASE", "BUILDING_LEVEL_WB_DEVELOPMENT", "BUILDING_LEVEL_WB_FREE_FARMLAND",
             "BUILDING_LEVEL_WB_MINIMUM", "BUILDING_LEVEL_WB_MAXIMUM", "BUILDING_LEVEL_WB_FAMILY")
    for key in keys:
        if key in fixed:
            continue
        rest = key.removeprefix("BUILDING_LEVEL_WB_")
        if rest.startswith("SHARED_"):
            loc.append(f'  {key}: "Levels of ${rest.removeprefix("SHARED_").lower()}$"')
            continue
        attribute, _, value = rest.partition("_")
        if attribute == "SOIL":
            attribute, _, value = rest.partition("_TYPE_")
        if attribute == "RIVER":
            attribute, _, value = rest.partition("_LEVEL_")
        if attribute == "IS":
            attribute, _, value = ("COASTAL", "", "") if "COASTAL" in rest else ("LAKE", "", "")
        label = " ".join(w.capitalize() for w in value.lower().split("_")) if value else ""
        loc.append(f'  {key}: "{(label + " " if label else "") + attribute.capitalize()}"')
    loc_path = mod_root / "main_menu/localization/english/pp_wb_building_caps_l_english.yml"
    loc_path.parent.mkdir(parents=True, exist_ok=True)
    loc_path.write_text("﻿" + "\n".join(loc) + "\n", encoding="utf-8", newline="\n")
    return info


def _raw_modifier_blocks(body: str) -> list[tuple[int, int, str, list[str]]]:
    """(start, end, indent, inner lines) of every raw_modifier block, found by brace matching."""
    blocks = []
    for match in re.finditer(r"^(?P<indent>[ \t]*)raw_modifier\s*=\s*\{", body, re.MULTILINE):
        depth = 0
        i = match.end() - 1
        while i < len(body):
            if body[i] == "{":
                depth += 1
            elif body[i] == "}":
                depth -= 1
                if depth == 0:
                    break
            i += 1
        inner = body[match.end(): i]
        blocks.append((match.start(), i + 1, match.group("indent"), [l.strip() for l in inner.splitlines() if l.strip()]))
    return blocks


def _replace_raw_modifier(body: str, lines: Mapping[str, str], *, drop_prefixes: tuple[str, ...] = ()) -> str:
    """Set lines in the raw_modifier block (merging duplicate blocks), dropping keys with the given prefixes; create it if absent."""
    blocks = _raw_modifier_blocks(body)
    if not blocks:
        indent = re.search(r"^([ \t]*)modifier\s*=\s*\{", body, re.MULTILINE)
        pad = indent.group(1) if indent else "    "
        block = "\n".join([f"{pad}raw_modifier = {{", *[f"{pad}  {k} = {v}" for k, v in lines.items()], f"{pad}}}"])
        anchor = re.search(r"^[ \t]*modifier\s*=\s*\{", body, re.MULTILINE)
        return body[: anchor.start()] + block + "\n\n" + body[anchor.start():] if anchor else body.rstrip("\n") + "\n\n" + block + "\n"
    merged: dict[str, str] = {}
    for _, _, _, inner in blocks:
        for line in inner:
            key, _, value = line.partition("=")
            key, value = key.strip(), value.strip()
            if key and value and key not in lines and not key.startswith(drop_prefixes):
                merged.setdefault(key, value)
    merged.update(lines)
    pad = blocks[0][2]
    new = "\n".join([f"{pad}raw_modifier = {{", *[f"{pad}  {k} = {v}" for k, v in merged.items()], f"{pad}}}"])
    # replace the first block, delete the others (from the end so offsets stay valid)
    for start, end, _, _ in sorted(blocks[1:], key=lambda b: -b[0]):
        body = body[:start].rstrip(" \t") + body[end:].lstrip("\n") if body[end:].startswith("\n\n") else body[:start].rstrip(" \t") + body[end:]
    start, end, _, _ = blocks[0]
    return body[:start] + new + body[end:]


def _set_max_levels(body: str, value: str) -> str:
    match = _MAX_LEVELS_RE.search(body)
    if match is None:
        # no max_levels line yet (vanilla default): add one after the first line of the body
        first = re.match(r"^(?P<indent>[ \t]*)\S", body, re.MULTILINE)
        pad = first.group("indent") if first else "    "
        head, _, tail = body.partition("\n")
        return f"{head}\n{pad}max_levels = {value}\n{tail}"
    return body[: match.start()] + f"{match.group('indent')}max_levels = {value}" + body[match.end():]


def _set_location_potential(body: str, trigger_lines: list[str]) -> str:
    match = _POTENTIAL_RE.search(body)
    pad = match.group("indent") if match else "    "
    block = "\n".join([f"{pad}location_potential = {{", *[f"{pad}  {l}" for l in trigger_lines], f"{pad}}}"])
    if match is None:
        return body.rstrip("\n") + "\n\n" + block + "\n"
    return body[: match.start()] + block + body[match.end():]


def _load_blueprint(repo: Path, key: str) -> tuple[Path, dict]:
    path = repo / BLUEPRINTS / f"{key}.yml"
    if not path.is_file():
        raise FileNotFoundError(f"blueprint missing: {path}")
    return path, yaml_io.safe_load(path.read_text(encoding="utf-8"))


class _Dumper(yaml.SafeDumper):
    pass


def _str_presenter(dumper: yaml.SafeDumper, data: str):  # block style for multi-line bodies
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


_Dumper.add_representer(str, _str_presenter)


def _normalise_body(text: str) -> str:
    """Tabs and trailing spaces keep PyYAML from using a literal block; normalise so bodies stay readable."""
    return "\n".join(line.replace("\t", "  ").rstrip() for line in text.splitlines()) + ("\n" if text.endswith("\n") else "")


def _save_blueprint(path: Path, data: dict) -> None:
    building = data.get("building")
    if isinstance(building, dict) and isinstance(building.get("body"), str):
        building["body"] = _normalise_body(building["body"])
    path.write_text(yaml.dump(data, Dumper=_Dumper, sort_keys=False, allow_unicode=True, width=10_000), encoding="utf-8")


def patch_improvement_blueprints(contract: Contract, cfg: WorldBuilderConfig, repo: Path, caps: Mapping[str, Mapping[str, float]]) -> list[str]:
    """Point each mapped blueprint at its cap value, set its capacity per level and its gate."""
    patched: list[str] = []
    gates = {str(r["building"]): json.loads(str(r["gate_json"])) for r in contract.building_types.iter_rows(named=True)}
    shared = families(cfg)
    counted = {k for family, members in shared.items() for k in (family, *members)}
    for key, info in caps.items():
        kind = str(info["kind"])
        if key == "field_management" and not (repo / BLUEPRINTS / "field_management.yml").is_file():
            create_field_management_blueprint(repo)
        path, data = _load_blueprint(repo, key)
        if info.get("niche") and str(data["building"].get("mode", "")).upper() not in ("REPLACE", "CREATE"):
            raise ValueError(f"niche building {key}: blueprint must be a full REPLACE or CREATE (lock, gate and level formula cannot be injected)")
        body = str(data["building"]["body"])
        body = _set_max_levels(body, f"pp_wb_cap_{key}")
        raw = {"local_population_capacity": _fmt(float(info["unit_units"]))}
        if key in counted:
            raw[LEVELS_MODIFIER.format(key=key)] = "1"
        # The engine's unsupported-level count takes raw levels of every building (decompiled FUN_144612a10). Capacity
        # improvements are farmland units, not buildings that need logistics (62 % of all levels at game start), so each
        # level supports itself (2026-09-30).
        raw["free_building_levels"] = "1"
        body = _replace_raw_modifier(body, raw, drop_prefixes=("farm_capacity_from_", "pp_wb_levels_"))
        lock = [str(l) for l in cfg.niche.get(key, {}).get("lock", [])]
        extra_gate = cfg.niche.get(key, {}).get("gate", [])
        marker = cfg.niche.get(key, {}).get("marker")
        # A setup-placed marker on the gate's locations replaces the tag list in game (one lookup, tested first).
        trigger = [*lock, *([f"has_location_modifier = {marker}"] if marker else []), *gate_trigger(contract, gates[kind])]
        if extra_gate and not marker:
            trigger.extend(gate_trigger(contract, extra_gate))
        body = _set_location_potential(body, trigger)
        data["building"]["body"] = body
        _save_blueprint(path, data)
        patched.append(key)
    for key in OTHER_CAPACITY_BLUEPRINTS:
        path = repo / BLUEPRINTS / f"{key}.yml"
        if not path.is_file():
            continue
        data = yaml_io.safe_load(path.read_text(encoding="utf-8"))
        body = str(data["building"]["body"])
        if "local_population_capacity" in body:
            body = re.sub(r"local_population_capacity\s*=\s*-?\d+(?:\.\d+)?", "local_population_capacity = 0", body)
            data["building"]["body"] = body
            _save_blueprint(path, data)
            patched.append(key)
    return patched


def create_field_management_blueprint(repo: Path) -> Path:
    """Clone land_clearance into field_management (rotations, manuring, terracing on existing fields)."""
    src, data = _load_blueprint(repo, "land_clearance")
    text = yaml.dump(data, Dumper=_Dumper, sort_keys=False, allow_unicode=True, width=10_000)
    text = text.replace("land_clearance", "field_management").replace("Land Clearance", "Field Management")
    data = yaml_io.safe_load(text)
    entries = data.get("localization", {}).get("entries", {})
    entries["field_management"] = "Field Management"
    entries["field_management_desc"] = "Rotations, manuring, marling and terracing raise how many people the existing fields can feed. Each level is a lasting improvement of the land already under the plough."
    entries["field_management_slot_0"] = "Maintenance"
    entries["pp_field_management_maintenance"] = "Field Stewards"
    entries["pp_field_management_price"] = "Field Management Price"
    icon = data.get("icon") or {}
    icon["output_dds"] = "field_management.dds"
    # placeholder art until field_management.png is drawn: a tinted copy of the land clearance icon so the
    # rendered DDS stays distinct from every other building icon
    placeholder = repo / "blueprints/accepted/assets/icons/field_management.png"
    source = repo / "blueprints/accepted/assets/icons/land_clearance.png"
    if not placeholder.is_file() and source.is_file():
        from PIL import Image, ImageEnhance

        with Image.open(source) as image:
            tinted = ImageEnhance.Color(image.convert("RGBA")).enhance(0.35)
            tinted.save(placeholder)
    icon["source_png"] = "../assets/icons/field_management.png"
    icon["prompt"] = "EU5-inspired detailed historic bitmap cutout for Field Management on a perfectly flat magenta chroma-key background. Show strip fields under rotation, a marl pit, manure carts, a plough team and a steward with a tally stick. Material-rich painterly three-quarter-view UI art, no text, no frame, no modern machinery."
    data["icon"] = icon
    path = repo / BLUEPRINTS / "field_management.yml"
    _save_blueprint(path, data)
    manifest_path = repo / MANIFEST
    manifest = yaml_io.safe_load(manifest_path.read_text(encoding="utf-8"))
    manifest.setdefault("enabled", {})["buildings/field_management.yml"] = True
    manifest_path.write_text(yaml.dump(manifest, sort_keys=False, allow_unicode=True), encoding="utf-8")
    # placeholder art until the real icon exists
    icons = repo / "mod/Prosper or Perish (Population Growth & Food Rework)/in_game/gfx/interface/icons/buildings"
    src_icon = icons / "land_clearance.dds"
    if src_icon.is_file() and not (icons / "field_management.dds").is_file():
        (icons / "field_management.dds").write_bytes(src_icon.read_bytes())
    return path


def farm_constants(cfg: WorldBuilderConfig, building: str) -> tuple[float, float]:
    """(land per level, reserve) in capacity units for a farm building, by configured class."""
    for cls, members in cfg.farm_classes.items():
        if building in members:
            values = cfg.farm_land[cls]
            return float(values["land"]), float(values["reserve"])
    values = cfg.farm_land["arable"]
    return float(values["land"]), float(values["reserve"])


def patch_farm_blueprints(cfg: WorldBuilderConfig, repo: Path, farm_buildings: list[str]) -> list[str]:
    """Each farm level takes land: raw_modifier local_population_capacity = -land (kept beside its level counter), and
    records it as local_pp_farmland_used = land, which the farm max-level tooltips read as "Used by other farms"
    (scripts/generate_rural_capacity_values.py; one modifier read instead of a sum over every farm type)."""
    patched: list[str] = []
    for key in farm_buildings:
        path = repo / BLUEPRINTS / f"{key}.yml"
        if not path.is_file():
            continue
        land, _ = farm_constants(cfg, key)
        data = yaml_io.safe_load(path.read_text(encoding="utf-8"))
        body = str(data["building"]["body"])
        new = _replace_raw_modifier(body, {"local_population_capacity": _fmt(-land), "local_pp_farmland_used": _fmt(land)})
        if new != body:
            data["building"]["body"] = new
            _save_blueprint(path, data)
            patched.append(key)
    return patched


def cap_levels(equation: Mapping[str, object], attributes: Mapping[str, object], scale: float, limit: int) -> int:
    """The cap as the game evaluates it: scaled base + matching class terms + development term, floored, clamped."""
    cap = float(equation["base_levels"]) * scale
    for term in equation["class_terms"]:
        if str(attributes.get(str(term["attribute"]))) == str(term["value"]):
            cap += float(term["levels"]) * scale
    cap += float(equation["levels_per_development_point"]) * scale * float(attributes.get("development") or 0.0)
    return min(max(int(math.floor(cap + 1e-9)), 0), int(limit))


def gate_matches(rules: list[dict[str, list[str]]], attributes: Mapping[str, object]) -> bool:
    """Evaluate the same OR-of-ANDs gate used in location_potential (CSV booleans are lowercase)."""
    return not rules or any(all(str(attributes.get(key, "")).lower() in {str(v).lower() for v in values}
                               for key, values in rule.items()) for rule in rules)


def write_setup(contract: Contract, cfg: WorldBuilderConfig, caps: Mapping[str, Mapping[str, float]], owners: Mapping[str, str], mod_root: Path,
                demand: Mapping[str, float] | None = None, cultures: Mapping[str, str] | None = None) -> dict[str, int]:
    """Starting improvement levels for owned locations (levels rescaled with the building's scale, never above the cap).

    ``demand`` (people per location the improvements must house so the pops at game start fit their capacity) raises
    the ledger's levels of the location's eligible buildings up to their caps, largest people per level first. The
    pops are evidence for how far the land had been improved by 1337, never for the caps themselves.
    Opted-in regional variants replace their family's levels when their structured gate matches; opaque
    country or advance locks are not guessed. The highest-capacity eligible member receives the family allocation.
    """
    rows: list[tuple[str, str, str, int]] = []
    skipped = 0
    clamped = 0
    gated = 0
    raised = 0
    navigation_exchanged = 0
    filled: set[str] = set()
    short: set[str] = set()
    kinds = {str(v["kind"]): k for k, v in caps.items() if not v.get("niche")}
    equations = {str(r["building"]): json.loads(str(r["cap_equation_json"])) for r in contract.building_types.iter_rows(named=True)}
    gates = {str(r["building"]): json.loads(str(r["gate_json"])) for r in contract.building_types.iter_rows(named=True)}
    for key, spec in cfg.niche.items():
        if spec.get("place_at_start") and (spec.get("lock") or not spec.get("gate")):
            raise ValueError(f"{key}: starting niche placement requires a structured gate and no opaque lock")
    attributes = contract.location_attributes
    if "development" not in attributes.columns and "development" in contract.location_targets.columns:
        attributes = attributes.join(contract.location_targets.select("location_tag", "development"), on="location_tag", how="left")
    by_tag = {str(r["location_tag"]): r for r in attributes.iter_rows(named=True)}
    eligible: dict[str, dict[str, int]] = {}
    has_cap = "cap_at_start" in contract.location_buildings.columns
    for row in contract.location_buildings.iter_rows(named=True):
        if has_cap and row["cap_at_start"] is None:
            continue
        eligible.setdefault(str(row["location_tag"]), {})[str(row["building"])] = int(row["starting_levels"] or 0)
    for tag in sorted(eligible):
        owner = owners.get(tag, "")
        if not owner:
            skipped += sum(1 for v in eligible[tag].values() if v > 0)
            continue
        levels: dict[str, tuple[int, int]] = {}
        for kind, start in eligible[tag].items():
            key = kinds.get(kind)
            if key is None:
                continue
            scale = float(caps[key]["scale"])
            limit = int(caps[key]["limit"])
            level = min(int(math.floor(start * scale + 1e-9)), limit)
            cap = cap_levels(equations[kind], by_tag.get(tag, {}), scale, limit) if tag in by_tag else level
            if level > cap:
                clamped += 1
                level = cap
            attrs = {**by_tag.get(tag, {}), "culture": (cultures or {}).get(tag, "")}
            if not gate_matches(gates[kind], attrs):
                # the game rejects a setup building whose location_potential fails ("has an invalid building")
                gated += 1
                continue
            candidates = [key] + [n for n, spec in cfg.niche.items()
                                  if spec["family"] == key and spec.get("place_at_start")
                                  and gate_matches(spec.get("gate", []), attrs) and gate_matches(gates[kind], attrs)]
            # A niche replaces the general family's starting levels; it never adds another full cap.
            selected = max(candidates, key=lambda k: float(caps[k]["unit_units"]))
            levels[selected] = (level, cap)
        need = float(demand.get(tag, 0.0)) if demand else 0.0
        need -= sum(level * float(caps[key]["unit_people"]) for key, (level, _) in levels.items())
        while need > 0:
            room = [key for key, (level, cap) in levels.items() if level < cap]
            if not room:
                short.add(tag)
                break
            key = max(room, key=lambda k: float(caps[k]["unit_units"]))
            level, cap = levels[key]
            levels[key] = (level + 1, cap)
            need -= float(caps[key]["unit_people"])
            raised += 1
            filled.add(tag)
        for key, (level, _) in levels.items():
            if level > 0:
                rows.append((key, tag, owner, level))
    # documented starting navigations: one River Navigation Canal at the bank (no capacity, outside the families)
    from .navigation import exchange_levels
    for tag, site in sorted(cfg.raw.get("_navigation", {}).get("sites", {}).items()):
        owner = owners.get(tag, "")
        canal: dict[str, tuple[int, int]] = {}
        if owner and exchange_levels(canal, site):
            navigation_exchanged += 1
            rows.extend((key, tag, owner, level) for key, (level, _) in canal.items())
    rows.sort()
    lines = [f"\t{key} = {{ tag = {owner} level = {level} location = {tag} }}" for key, tag, owner, level in rows]
    text = "\n".join([GENERATED, "building_manager = {", *lines, "}", ""])
    (mod_root / SETUP_PATH).parent.mkdir(parents=True, exist_ok=True)
    (mod_root / SETUP_PATH).write_text("\ufeff" + text, encoding="utf-8", newline="\n")
    for rel in LEGACY_SETUP:
        if (mod_root / rel).is_file():
            (mod_root / rel).unlink()
    return {"rows": len(rows), "navigation_levels_exchanged": navigation_exchanged, "unowned_skipped": skipped, "clamped_to_cap": clamped, "gate_rejected": gated, "levels_raised_for_pops": raised,
            "locations_filled_for_pops": len(filled), "locations_still_short": len(short)}


def vanilla_capacity_buildings(vanilla_root: Path) -> dict[str, str]:
    """Vanilla building keys whose definition carries a population capacity line (flat or percent) -> file name."""
    found: dict[str, str] = {}
    folder = Path(vanilla_root) / "game/in_game/common/building_types"
    for path in sorted(folder.glob("*.txt")):
        text = path.read_text(encoding="utf-8-sig", errors="replace")
        starts = list(_VANILLA_BUILDING_RE.finditer(text))
        for index, match in enumerate(starts):
            end = starts[index + 1].start() if index + 1 < len(starts) else len(text)
            if _CAPACITY_LINE_RE.search(text[match.start(): end]):
                found[match.group("key")] = path.name
    return found


def vanilla_capacity_leaks(repo: Path, vanilla_root: Path) -> dict[str, str]:
    """Vanilla capacity buildings the mod does not fully REPLACE (their vanilla capacity would leak into the flat)."""
    manifest = yaml_io.safe_load((repo / MANIFEST).read_text(encoding="utf-8")) or {}
    enabled = manifest.get("enabled", {}) if isinstance(manifest, dict) else {}
    leaks: dict[str, str] = {}
    for key, source in vanilla_capacity_buildings(vanilla_root).items():
        path = repo / BLUEPRINTS / f"{key}.yml"
        if not path.is_file():
            leaks[key] = f"no blueprint ({source})"
            continue
        if not enabled.get(f"buildings/{key}.yml", False):
            leaks[key] = f"blueprint disabled in manifest ({source})"
            continue
        data = yaml_io.safe_load(path.read_text(encoding="utf-8-sig")) or {}
        mode = str((data.get("building") or {}).get("mode", "")).upper()
        if mode != "REPLACE":
            leaks[key] = f"blueprint mode {mode or 'unset'} keeps the vanilla capacity ({source})"
    return leaks
