"""Widen vanilla attribute tests to the World Builder's new classes.

The World Builder adds climate, vegetation and topography classes as children of vanilla classes (the
``families`` map in the export's ``geography_compatibility.json``: e.g. ``forest`` -> coniferous forest, mixed
forest, swamp). Vanilla scripts that test ``vegetation = forest`` would silently exclude those locations, so the
configured vanilla files (``[worldbuilder.compat] vanilla_files``) are copied into the mod with every test of a
parent class widened to ``OR = { attribute = parent attribute = child ... }``. Nothing else in the copies changes,
and the copies are regenerated from the current vanilla files on every ``ppc worldbuilder apply``.

The same expansion is applied once, in place, to the mod's own hand-authored scripts and blueprints.
"""

from __future__ import annotations

import hashlib
import json
import re
from collections.abc import Mapping
from pathlib import Path

ATTRIBUTES = ("climate", "vegetation", "topography")
COMPAT_JSON = "geography_compatibility.json"
MANIFEST_RELATIVE_PATH = Path("artifacts/data/worldbuilder/compat_patches.json")
HEADER = "# Generated by ppc worldbuilder: vanilla file with every climate/vegetation/topography test widened to the World Builder classes; do not edit by hand."
_TEST_RE = re.compile(r"\b(?P<attr>climate|vegetation|topography)\s*=\s*(?P<value>[a-z_0-9]+)\b")

Families = Mapping[str, Mapping[str, list[str]]]


def load_families(export_dir: Path) -> dict[str, dict[str, list[str]]]:
    data = json.loads((Path(export_dir) / COMPAT_JSON).read_text(encoding="utf-8-sig"))
    families = data.get("families")
    if not isinstance(families, dict):
        raise ValueError(f"{Path(export_dir) / COMPAT_JSON}: missing families map")
    return {str(attr): {str(parent): [str(c) for c in children] for parent, children in parents.items()} for attr, parents in families.items()}


def expand_attribute_tests(text: str, families: Families) -> tuple[str, int]:
    """Widen every ``attribute = parent`` test whose parent has children; returns (text, tests widened).

    Idempotent: a test already followed on its line by the first child is left alone. Comments are not touched.
    """
    out_lines: list[str] = []
    widened = 0
    for line in text.splitlines(keepends=True):
        code, sep, comment = line.partition("#")

        def replace(match: re.Match[str]) -> str:
            nonlocal widened
            attr, value = match.group("attr"), match.group("value")
            children = families.get(attr, {}).get(value)
            if not children:
                return match.group(0)
            rest = code[match.end():]
            if re.search(rf"\b{attr}\s*=\s*{re.escape(children[0])}\b", rest) or re.search(rf"\b{attr}\s*=\s*{re.escape(children[0])}\b", code[: match.start()]):
                return match.group(0)
            widened += 1
            return "OR = { " + " ".join(f"{attr} = {v}" for v in (value, *children)) + " }"

        out_lines.append(_TEST_RE.sub(replace, code) + sep + comment)
    return "".join(out_lines), widened


def _sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def write_compat_patches(vanilla_root: Path, mod_root: Path, repo: Path, families: Families, relative_files: list[str]) -> dict[str, object]:
    """Copy the configured vanilla files into the mod with widened tests; drop copies no longer produced."""
    manifest_path = repo / MANIFEST_RELATIVE_PATH
    previous = json.loads(manifest_path.read_text(encoding="utf-8")).get("files", {}) if manifest_path.is_file() else {}
    files: dict[str, dict[str, object]] = {}
    unchanged: list[str] = []
    for rel in relative_files:
        source = Path(vanilla_root) / "game" / rel
        if not source.is_file():
            raise FileNotFoundError(f"[worldbuilder.compat] vanilla file not found: {source}")
        original = source.read_text(encoding="utf-8-sig")
        expanded, widened = expand_attribute_tests(original, families)
        target = mod_root / rel
        if widened == 0:
            unchanged.append(rel)
            if target.is_file() and rel in previous:
                target.unlink()
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("﻿" + HEADER + "\n" + expanded, encoding="utf-8", newline="\n")
        files[rel] = {"vanilla_sha256": _sha(original), "tests_widened": widened}
    for rel in previous:
        if rel not in files and (mod_root / rel).is_file():
            (mod_root / rel).unlink()
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps({"files": files, "unchanged": unchanged}, indent=2) + "\n", encoding="utf-8")
    return {"files": len(files), "tests_widened": sum(int(v["tests_widened"]) for v in files.values()), "unchanged": unchanged}


def expand_file_in_place(path: Path, families: Families) -> int:
    """Widen the tests of one of the mod's own scripts; returns the number of tests widened."""
    raw = path.read_bytes()
    bom = raw.startswith(b"\xef\xbb\xbf")
    text = raw.decode("utf-8-sig")
    expanded, widened = expand_attribute_tests(text, families)
    if widened:
        path.write_bytes(("﻿" if bom else "").encode("utf-8") + expanded.encode("utf-8"))
    return widened
