"""Vanilla game-start development per location.

EU5 ships development as ~300 additive rules (``main_menu/setup/start/14_development.txt``: base,
region/area/province/location, rank, climate/topography/vegetation, coast x harbour, river x size,
road). The mod replaces climate/vegetation/topography classes with the World Builder geography, which
would silently change what those rules add up to, so the constructor evaluates the vanilla rules once
against the vanilla location table and writes explicit per-location values. The same table is exported
for the World Builder, which uses it as its development input.
"""

from __future__ import annotations

import csv
from pathlib import Path

import polars as pl

from prosper_or_perish_constructor.location_baseline import load_vanilla_location_frame

GENERATED_MARKER = "# Generated by ppc worldbuilder from the vanilla development rules; do not edit by hand."
SETUP_RELATIVE_PATH = Path("main_menu/setup/start/14_development.txt")
EXPORT_RELATIVE_PATH = Path("artifacts/data/worldbuilder/vanilla_start_development.csv")


def compute_vanilla_development(repo: Path, project: Path) -> pl.DataFrame:
    """location_tag, development (vanilla rules evaluated on vanilla attributes)."""
    from eu5gameparser.load_order import LoadOrderConfig

    from prosper_or_perish_constructor.free_building_levels import build_game_start_location_frame, resolve_parser_config

    parser_config = resolve_parser_config(repo, project)
    load_order_path = repo / str(parser_config.get("load_order") or "constructor.load_order.toml")
    # Vanilla layer only: the mod itself writes 14_development.txt and setup corrections, which must not feed back.
    profile = LoadOrderConfig.load(load_order_path).profile(str(parser_config.get("vanilla_profile") or "vanilla"))
    base = load_vanilla_location_frame(repo, project, profile=str(parser_config.get("profile") or "constructor"))
    enriched = build_game_start_location_frame(base, profile=profile)
    return (
        enriched.select(
            pl.col("location_tag").cast(pl.String),
            pl.col("development").cast(pl.Float64).fill_null(0.0).clip(0.0, None).round(3).alias("development"),
        )
        .unique("location_tag")
        .sort("location_tag")
    )


def render_development_setup(frame: pl.DataFrame) -> str:
    lines = [GENERATED_MARKER, "development = {", "\tbase = 0"]
    for tag, value in frame.select("location_tag", "development").iter_rows():
        lines.append(f"\t{tag} = {value:.3f}")
    lines.extend(("}", ""))
    return "\n".join(lines)


def write_development_export(frame: pl.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["location_tag", "development"])
        for tag, value in frame.select("location_tag", "development").iter_rows():
            writer.writerow([tag, f"{value:.3f}"])
