"""Game-start development per location: vanilla's rules on the mod's map.

EU5 places game-start development with ~300 additive rules (``main_menu/setup/1337/14_development.txt``: base,
region/area/province/location, rank, climate/topography/vegetation, coast x harbour, river x size). The mod changes what
those rules read: the World Builder geography brings its own climate/vegetation/topography classes (children of vanilla
classes, which vanilla's rules do not list and would score 0), its own rivers and its own harbours. The constructor
therefore evaluates vanilla's rules itself, in the spirit of vanilla: on the mod's map (``[worldbuilder]
development_geography = "mod"``, the default) with every World Builder class scored like its vanilla parent (the
``families`` of the export's ``geography_compatibility.json``, as ``compat.py`` widens vanilla's attribute tests). The
values are written per location into the mod's ``14_development.txt`` (the engine takes setup development as written:
1.3.11 PP start saves 12,848 of 12,853 exact) and are the development the start placement and the capacity model use.
``development_geography = "vanilla"`` evaluates the rules on the vanilla map instead (the 1.3.11 behaviour: vanilla
classes, rivers and harbours, so the mod's geography leaves development as in a vanilla game).

The evaluator reproduces the engine (``_development_expr`` in free_building_levels.py: own terms floored at 0, then
base + coast + river, floored at 0; river size from the rivers.png width level, junctions largest; no road term at
game start; duplicate keys add up). It is checked against the development of a vanilla game-start save
(``config/validation/``, read with the eu5save engine): ``ppc worldbuilder development-check``. The save values are
validation data only and never written into the mod.
"""

from __future__ import annotations

import csv
from pathlib import Path

import polars as pl

from prosper_or_perish_constructor.setup_layout import SETUP_DIR

GENERATED_MARKER = "# Generated by ppc worldbuilder: vanilla's development rules evaluated on the mod's map; do not edit by hand."
SETUP_RELATIVE_PATH = SETUP_DIR / "14_development.txt"
# the development the mod ships (= what the start placement and the capacity model use), for the World Builder
EXPORT_RELATIVE_PATH = Path("artifacts/data/worldbuilder/start_development.csv")
CHECK_RELATIVE_PATH = Path("artifacts/data/worldbuilder/development_check.csv")
# location_tag, development of the owned locations of a vanilla game-start save; validation of the evaluator only
REFERENCE_RELATIVE_PATH = Path("config/validation/vanilla_start_development_eu5_1.4.csv")
GEOGRAPHIES = ("mod", "vanilla")
TOLERANCE = 1e-3


def configured_geography(repo: Path, project: Path) -> str:
    from .contract import load_config

    geography = str(load_config(repo, project).raw.get("development_geography") or "mod")
    if geography not in GEOGRAPHIES:
        raise ValueError(f"[worldbuilder].development_geography must be one of {GEOGRAPHIES}, not {geography!r}")
    return geography


def load_families(repo: Path, project: Path) -> dict[str, dict[str, list[str]]]:
    """World Builder class families (attribute -> vanilla parent -> children); empty without a geography export."""
    from .compat import COMPAT_JSON
    from .compat import load_families as load_compat_families
    from .contract import load_config

    export = load_config(repo, project).geography_export
    return load_compat_families(export) if (export / COMPAT_JSON).is_file() else {}


def rules_with_families(weights: dict[str, float], families: dict[str, dict[str, list[str]]]) -> dict[str, float]:
    """Vanilla's rules plus every World Builder child class scored like its vanilla parent (a key vanilla lists
    itself keeps vanilla's value)."""
    out = dict(weights)
    for parents in families.values():
        for parent, children in parents.items():
            for child in children:
                if child not in weights and parent in weights:
                    out[child] = weights[parent]
    return out


def evaluate_development(repo: Path, project: Path, geography: str) -> pl.DataFrame:
    """Per location: the development vanilla's rules give on ``geography`` ("mod" or "vanilla"), with components."""
    from eu5gameparser.load_order import LoadOrderConfig

    from prosper_or_perish_constructor.free_building_levels import (
        build_game_start_location_frame,
        explain_development_components,
        load_development_weights,
        resolve_parser_config,
    )
    from prosper_or_perish_constructor.location_baseline import load_current_location_frame, load_vanilla_location_frame

    if geography not in GEOGRAPHIES:
        raise ValueError(f"unknown development geography {geography!r}")
    parser_config = resolve_parser_config(repo, project)
    load_order = LoadOrderConfig.load(repo / str(parser_config.get("load_order") or "constructor.load_order.toml"))
    # the rules always come from vanilla alone: the mod's own 14_development.txt is this module's output
    vanilla = load_order.profile(str(parser_config.get("vanilla_profile") or "vanilla"))
    weights = load_development_weights(vanilla)
    if geography == "vanilla":
        base = load_vanilla_location_frame(repo, project, profile=str(parser_config.get("profile") or "constructor"))
        enriched = build_game_start_location_frame(base, profile=vanilla, development_weights=weights)
    else:
        weights = rules_with_families(weights, load_families(repo, project))
        mod_profile = load_order.profile(str(parser_config.get("profile") or "constructor"))
        base = load_current_location_frame(repo, project)
        enriched = build_game_start_location_frame(base, profile=mod_profile, development_weights=weights)
    components = explain_development_components(enriched.with_columns(pl.col("development").round(3)), weights)
    return components.unique("location_tag").sort("location_tag")


def compute_start_development(repo: Path, project: Path, geography: str | None = None) -> pl.DataFrame:
    """location_tag, development: what the mod writes into its setup (the configured geography)."""
    frame = evaluate_development(repo, project, geography or configured_geography(repo, project))
    return frame.select(
        pl.col("location_tag").cast(pl.String),
        pl.col("development").cast(pl.Float64).fill_null(0.0).clip(0.0, None).round(3).alias("development"),
    )


def with_development(contract, development: pl.DataFrame):
    """The contract with the handover's development replaced by the mod's game-start development."""
    from dataclasses import replace

    targets = (
        contract.location_targets.drop("development", strict=False)
        .join(development.select("location_tag", "development"), on="location_tag", how="left")
        .with_columns(pl.col("development").fill_null(0.0))
    )
    return replace(contract, location_targets=targets)


def handover_difference(contract, development: pl.DataFrame) -> dict[str, object]:
    """How far the handover's development (the World Builder's input) is from the development the mod ships."""
    if "development" not in contract.location_targets.columns:
        return {"handover_development": "missing"}
    joined = (
        contract.location_targets.select("location_tag", pl.col("development").cast(pl.Float64).fill_null(0.0).alias("handover"))
        .join(development.select("location_tag", "development"), on="location_tag", how="left")
        .with_columns(pl.col("development").fill_null(0.0), (pl.col("development").fill_null(0.0) - pl.col("handover")).alias("diff"))
    )
    nonzero = joined.filter((pl.col("handover") > 0) | (pl.col("development") > 0))
    return {
        "locations": int(joined.height),
        "differ": int(joined.filter(pl.col("diff").abs() > TOLERANCE).height),
        "differ_where_either_positive": int(nonzero.filter(pl.col("diff").abs() > TOLERANCE).height),
        "higher_in_mod": int(joined.filter(pl.col("diff") > TOLERANCE).height),
        "lower_in_mod": int(joined.filter(pl.col("diff") < -TOLERANCE).height),
        "mean_abs_diff": round(float(joined["diff"].abs().mean() or 0.0), 3),
        "sum_handover": round(float(joined["handover"].sum()), 1),
        "sum_mod": round(float(joined["development"].sum()), 1),
    }


def load_reference(repo: Path) -> pl.DataFrame | None:
    path = repo / REFERENCE_RELATIVE_PATH
    if not path.is_file():
        return None
    return pl.read_csv(path, comment_prefix="#", schema={"location_tag": pl.String, "development": pl.Float64})


def compare_with_reference(evaluated: pl.DataFrame, reference: pl.DataFrame) -> tuple[dict[str, object], pl.DataFrame]:
    """Match rate of the evaluation on the reference's (owned) locations, both error sides and the mismatches."""
    joined = evaluated.join(reference.rename({"development": "engine"}), on="location_tag", how="inner").with_columns(
        (pl.col("development") - pl.col("engine")).round(3).alias("error")
    )
    high = joined.filter(pl.col("error") > TOLERANCE)
    low = joined.filter(pl.col("error") < -TOLERANCE)
    has = lambda name: name in joined.columns  # noqa: E731
    river = (pl.col("development_river_size") > 0) if has("development_river_size") else pl.lit(False)
    summary: dict[str, object] = {
        "locations": int(joined.height),
        "missing_from_evaluation": int(reference.join(evaluated, on="location_tag", how="anti").height),
        "exact": int(joined.height - high.height - low.height),
        "match_rate": round((joined.height - high.height - low.height) / joined.height, 4) if joined.height else None,
        "evaluator_too_high": int(high.height),
        "evaluator_too_low": int(low.height),
        "river_locations": int(joined.filter(river).height),
        "river_exact": int(joined.filter(river, pl.col("error").abs() <= TOLERANCE).height),
        "sum_engine": round(float(joined["engine"].sum()), 2),
        "sum_evaluated": round(float(joined["development"].sum()), 2),
        "errors": {str(k): int(v) for k, v in joined.filter(pl.col("error").abs() > TOLERANCE)["error"].value_counts().iter_rows()},
    }
    return summary, joined.filter(pl.col("error").abs() > TOLERANCE).sort("location_tag")


def check(repo: Path, project: Path) -> dict[str, object]:
    """Evaluate vanilla's rules on the vanilla map, compare with the vanilla start save, and size the mod's change."""
    reference = load_reference(repo)
    if reference is None:
        raise FileNotFoundError(f"validation table missing: {repo / REFERENCE_RELATIVE_PATH}")
    vanilla_map = evaluate_development(repo, project, "vanilla")
    summary, mismatches = compare_with_reference(vanilla_map, reference)
    out = repo / CHECK_RELATIVE_PATH
    out.parent.mkdir(parents=True, exist_ok=True)
    mismatches.write_csv(out)
    mod_map = compute_start_development(repo, project, "mod")
    both = (
        vanilla_map.select("location_tag", pl.col("development").alias("vanilla_map"))
        .join(mod_map.rename({"development": "mod_map"}), on="location_tag")
        .join(reference.select("location_tag", pl.lit(True).alias("owned")), on="location_tag", how="left")
        .with_columns(pl.col("owned").fill_null(False), (pl.col("mod_map") - pl.col("vanilla_map")).round(3).alias("change"))
    )
    owned = both.filter(pl.col("owned"))
    from .contract import load_config, load_contract

    geography = configured_geography(repo, project)
    shipped = mod_map if geography == "mod" else vanilla_map.select("location_tag", "development")
    return {
        "vanilla_map_vs_start_save": summary,
        "mismatches": str(out),
        "configured_geography": geography,
        "handover_vs_shipped": handover_difference(load_contract(load_config(repo, project).handover), shipped),
        "mod_map_vs_vanilla_map": {
            "locations": int(both.height),
            "owned": int(owned.height),
            "owned_changed": int(owned.filter(pl.col("change").abs() > TOLERANCE).height),
            "owned_up": int(owned.filter(pl.col("change") > TOLERANCE).height),
            "owned_down": int(owned.filter(pl.col("change") < -TOLERANCE).height),
            "owned_mean_abs_change": round(float(owned["change"].abs().mean() or 0.0), 3),
            "owned_sum_vanilla_map": round(float(owned["vanilla_map"].sum()), 1),
            "owned_sum_mod_map": round(float(owned["mod_map"].sum()), 1),
        },
    }


def render_development_setup(frame: pl.DataFrame) -> str:
    lines = [GENERATED_MARKER, "development = {", "\tbase = 0"]
    for tag, value in frame.select("location_tag", "development").iter_rows():
        lines.append(f"\t{tag} = {value:.3f}")
    lines.extend(("}", ""))
    return "\n".join(lines)


def write_development_export(frame: pl.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["location_tag", "development"])
        for tag, value in frame.select("location_tag", "development").iter_rows():
            writer.writerow([tag, f"{value:.3f}"])
