"""Attribute rows from the World Builder contract as in-game modifiers.

- climate / vegetation / topography classes: ``TRY_INJECT`` into the World Builder class definitions with
  the flat capacity row, the goods output rows, and the exact cancellation of the vanilla capacity values
  those definitions still carry (percentages and vegetation flats). The fit intercept is folded into the
  climate rows, because every location has exactly one climate.
- fertility / soil type: one static modifier per class (``pp_wb_fertility_<class>``, ``pp_wb_soil_<class>``),
  applied per location at game start by an on_action.
- river level: ``TRY_REPLACE`` of vanilla ``river_flowing_through_<n>`` without its capacity percentage and
  with the level's rows (World Builder levels 1..5 are the engine's five river sizes).
- coast / lake: static modifiers placed on every shore location, carrying the fit's rows plus the hand-set
  ``[worldbuilder.flavour.<key>]`` effects from constructor.toml.
- goods floor: per-location lift for the game's RGO where the rows would leave it under the floor.
- overpopulation: peasant unrest injected into vanilla's ``overpopulation`` modifier.
- legacy class effects: the mod's former climate/vegetation/topography injects (construction, food decay,
  free building levels) re-keyed onto every World Builder class through its dominant vanilla parent, with the
  capacity lines dropped.
"""

from __future__ import annotations

import csv
import re
from collections import Counter, defaultdict
from collections.abc import Iterable, Mapping
from pathlib import Path

import polars as pl

from prosper_or_perish_constructor.worldbuilder.contract import Contract, WorldBuilderConfig, units

CAPACITY_KEYS = ("local_population_capacity", "local_population_capacity_modifier")
FOOD_KEY = "local_monthly_food_modifier"   # the mod has no food production on attributes: cancelled exactly, never inherited
CLASS_DIRS = {"climate": "climates", "vegetation": "vegetation", "topography": "topography"}
ASSIGNMENT_FILES = {
    "climate": ("climate_assignments.csv", "vanilla_climate", "game_climate"),
    "vegetation": ("vegetation_assignments.csv", "vanilla_vegetation", "applied_game_vegetation"),
    "topography": ("topography_assignments.csv", "vanilla_topography", "game_topography"),
}
LEGACY_EFFECTS_DIR = Path("data/worldbuilder/legacy_class_effects")
STATIC_MODIFIERS_PATH = Path("main_menu/common/static_modifiers/pp_wb_attribute_modifiers.txt")
RIVER_MODIFIERS_PATH = Path("main_menu/common/static_modifiers/pp_00_wb_river_modifiers.txt")   # sorts before the hand-authored injects into the same blocks
FLOOR_MODIFIERS_PATH = Path("main_menu/common/static_modifiers/pp_wb_rgo_floor_modifiers.txt")
ON_ACTION_PATH = Path("in_game/common/on_action/pp_wb_apply_attribute_modifiers.txt")
SETUP_MODIFIERS_PATH = Path("main_menu/setup/start/21_pp_wb_attribute_modifiers.txt")
ADJUSTMENTS_PATH = Path("main_menu/common/static_modifiers/pp_location_modifier_adjustments.txt")   # hand-authored; carries TRY_REPLACE:development
DEVELOPMENT_MARK = "# generated by ppc worldbuilder: flat people of capacity per development point (x1,000); the World Builder fit knows this term"
LOCALIZATION_PATH = Path("main_menu/localization/english/pp_wb_attribute_modifiers_l_english.yml")
GENERATED = "# Generated by ppc worldbuilder from the World Builder handover; do not edit by hand."
LEGACY_OUTPUTS = (
    "main_menu/common/static_modifiers/pp_wb_development.txt",
    "main_menu/common/static_modifiers/pp_wb_river_modifiers.txt",
    "main_menu/common/static_modifiers/pp_wb_overpopulation.txt",
    "main_menu/common/static_modifiers/pp_location_modifiers.txt",
    "main_menu/common/static_modifiers/pp_nile_delta_base_adjustments.txt",
    "main_menu/localization/english/pp_location_modifiers_l_english.yml",
    "in_game/common/on_action/pp_apply_location_modifiers.txt",
)
_BLOCK_RE = re.compile(r"^(?:TRY_INJECT:|TRY_REPLACE:)?(?P<key>[A-Za-z0-9_]+)\s*=\s*\{")
_NUM_RE = re.compile(r"^\s*(?P<key>[a-z_]+)\s*=\s*(?P<value>-?\d+(?:\.\d+)?)\s*(?:#.*)?$")


def _fmt(value: float) -> str:
    text = f"{value:.2f}".rstrip("0").rstrip(".")
    return text if text not in ("", "-0") else "0"


def pretty(name: str) -> str:
    return " ".join(w.capitalize() for w in str(name).replace("ha1300_", "").replace("climate_", "").replace("veg_", "").replace("topo_", "").split("_"))


def effective_class_files(directory: Path, export_dir: Path | None, vanilla_root: Path | None) -> list[Path]:
    """The definition files the game will load for a class directory: vanilla's files, each replaced by the export's
    file of the same name, plus the export's new files; sorted by name (the game's load order)."""
    files: dict[str, Path] = {}
    if vanilla_root is not None:
        for path in sorted((Path(vanilla_root) / "game/in_game/common" / directory).glob("*.txt")):
            files[path.name] = path
    if export_dir is not None:
        for path in sorted((Path(export_dir) / "in_game/common" / directory).glob("*.txt")):
            files[path.name] = path
    return [files[name] for name in sorted(files)]


def parse_class_capacity(paths: Iterable[Path]) -> dict[str, dict[str, float]]:
    """{class key: {capacity key: value}} for every top-level block in the given definition files.

    Files are read in the given order and a later file's definition of a class replaces an earlier one (the game's
    override rule); inside one definition the first value of a key wins."""
    found: dict[str, dict[str, float]] = {}
    for path in paths:
        current: str | None = None
        depth = 0
        for raw in path.read_text(encoding="utf-8-sig").splitlines():
            line = raw.split("#", 1)[0]
            if depth == 0:
                match = _BLOCK_RE.match(line.strip())
                if match:
                    current = match.group("key")
                    found[current] = {}
            if current is not None and depth >= 1:
                for key, value in re.findall(r"\b(local_population_capacity(?:_modifier)?|local_[a-z_]+_output_modifier|local_monthly_food_modifier)\s*=\s*(-?\d+(?:\.\d+)?)", line):
                    if key not in found[current]:
                        found[current][key] = float(value)
            depth += line.count("{") - line.count("}")
            if depth <= 0:
                depth = 0
                current = None
    return found


def parse_legacy_effects(path: Path) -> dict[str, dict[str, str]]:
    """{vanilla class: {modifier: value}} from a legacy TRY_INJECT file, capacity and food lines removed."""
    effects: dict[str, dict[str, str]] = {}
    current: str | None = None
    for raw in path.read_text(encoding="utf-8-sig").splitlines():
        line = raw.split("#", 1)[0].strip()
        match = _BLOCK_RE.match(line)
        if match and line.startswith("TRY_INJECT:"):
            current = match.group("key")
            effects.setdefault(current, {})
            continue
        if current and "=" in line and not line.endswith("{") and line != "}":
            key, _, value = line.partition("=")
            key, value = key.strip(), value.strip()
            if key and value and key not in CAPACITY_KEYS and key != FOOD_KEY:
                effects[current][key] = value
        if line == "}" and current and raw.startswith("}"):
            current = None
    return effects


def dominant_parents(export_dir: Path, attribute: str) -> dict[str, str]:
    """World Builder game key -> most common vanilla class among its locations."""
    name, vanilla_col, game_col = ASSIGNMENT_FILES[attribute]
    counts: dict[str, Counter] = defaultdict(Counter)
    with (export_dir / name).open("r", encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle):
            game = (row.get(game_col) or "").strip()
            vanilla = (row.get(vanilla_col) or "").strip()
            if game and vanilla:
                counts[game][vanilla] += 1
    return {game: counter.most_common(1)[0][0] for game, counter in counts.items()}


def class_rows(contract: Contract) -> dict[tuple[str, str], dict[str, float]]:
    """(attribute, class) -> {modifier: value} from attribute_rows.csv, intercepts (capacity and goods output)
    folded into the climate rows: every location has exactly one climate, so a climate row reads as the
    absolute value for that climate and no per-good base modifier is needed."""
    rows = contract.attribute_rows
    goods = contract.goods
    intercept = rows.filter(pl.col("attribute") == "reference").row(0, named=True)

    def num(v) -> float:
        return float(v) if v not in (None, "") else 0.0

    def modifiers(row, fold: bool) -> dict[str, float]:
        mods: dict[str, float] = {}
        cap = num(row.get("capacity_people")) + (num(intercept["capacity_people"]) if fold else 0.0)
        if cap:
            mods["local_population_capacity"] = units(cap)
        for good in goods:
            v = num(row.get(f"output_{good}")) + (num(intercept.get(f"output_{good}")) if fold else 0.0)
            if abs(v) >= 0.005:
                mods[f"local_{good}_output_modifier"] = round(v, 2)
        return mods

    out: dict[tuple[str, str], dict[str, float]] = {}
    for row in rows.filter(pl.col("attribute") != "reference").iter_rows(named=True):
        attr, value = str(row["attribute"]), str(row["value"])
        out[(attr, value)] = modifiers(row, attr == "climate")
    # the climate reference (and any climate without a fit row) is the intercept alone
    ref = {f: str(v) for f, v in contract.meta["attributes"]["reference_classes"].items()}
    climates = {ref["climate"]}
    if "climate" in contract.location_attributes.columns:
        climates |= {str(c) for c in contract.location_attributes["climate"].unique().to_list() if c}
    for climate in climates:
        if ("climate", climate) not in out:
            out[("climate", climate)] = modifiers({}, True)
    return out


def rgo_row_predictions(contract: Contract, rgo_by_location: Mapping[str, str]) -> dict[str, tuple[str, float]]:
    """location tag -> (RGO good, sum of that good's attribute output rows over the location's classes), for
    every location whose RGO has fitted rows. The fit intercept is not part of it (not written to the mod)."""
    rows = class_rows(contract)
    goods = set(contract.goods)
    attrs = contract.location_attributes
    columns = [a for a in {attr for attr, _ in rows} if a in attrs.columns]
    out: dict[str, tuple[str, float]] = {}
    for row in attrs.select("location_tag", *columns).iter_rows(named=True):
        tag = str(row["location_tag"])
        good = rgo_by_location.get(tag)
        if good not in goods:
            continue
        key = f"local_{good}_output_modifier"
        out[tag] = (good, round(sum(rows.get((a, str(row[a])), {}).get(key, 0.0) for a in columns), 2))
    return out


def game_key_of(contract: Contract, attribute: str, value: str) -> str:
    rows = contract.attribute_rows.filter((pl.col("attribute") == attribute) & (pl.col("value") == value))
    if len(rows) and rows["game_key"][0]:
        return str(rows["game_key"][0])
    return value


def render_block(header: str, lines: Mapping[str, str], *, nested: str | None = None, extra: Iterable[str] = ()) -> str:
    body = [f"\t\t{k} = {v}" if nested else f"\t{k} = {v}" for k, v in lines.items()]
    body.extend(extra)
    if nested:
        return "\n".join([f"{header} = {{", f"\t{nested} = {{", *body, "\t}", "}"])
    return "\n".join([f"{header} = {{", *body, "}"])


def write_class_injects(contract: Contract, export_dir: Path, mod_root: Path, repo: Path, vanilla_root: Path | None = None) -> dict[str, int]:
    """One inject file per class directory, cancelling the effective vanilla capacity and food values and adding the rows."""
    rows = class_rows(contract)
    written: dict[str, int] = {}
    for attribute, directory in CLASS_DIRS.items():
        defs = parse_class_capacity(effective_class_files(Path(directory), export_dir, vanilla_root))
        legacy_path = repo / LEGACY_EFFECTS_DIR / f"{directory}.txt"
        legacy = parse_legacy_effects(legacy_path) if legacy_path.is_file() else {}
        parents = dominant_parents(export_dir, attribute) if legacy else {}
        blocks: list[str] = []
        keys: set[str] = set()
        for (attr, value), mods in sorted(rows.items()):
            if attr != attribute:
                continue
            key = game_key_of(contract, attr, value)
            keys.add(key)
            lines: dict[str, str] = {}
            vanilla = defs.get(key, {})
            flat = mods.get("local_population_capacity", 0.0) - vanilla.get("local_population_capacity", 0.0)
            if abs(flat) >= 0.005:
                lines["local_population_capacity"] = _fmt(flat)
            pct = -vanilla.get("local_population_capacity_modifier", 0.0)
            if abs(pct) >= 0.005:
                lines["local_population_capacity_modifier"] = _fmt(pct)
            # goods rows replace whatever output modifiers the vanilla definition carried
            for name, v in mods.items():
                if name != "local_population_capacity":
                    lines[name] = _fmt(v - vanilla.get(name, 0.0))
            for name, v in vanilla.items():
                if (name.endswith("_output_modifier") or name == FOOD_KEY) and name not in lines and abs(v) >= 0.005:
                    lines[name] = _fmt(-v)
            for name, v in legacy.get(parents.get(key, key), {}).items():
                lines.setdefault(name, v)
            if lines:
                blocks.append(render_block(f"TRY_INJECT:{key}", lines, nested="location_modifier"))
        # classes the fit never saw (no ownable location) still need their vanilla capacity and food cancelled
        for key, vanilla in sorted(defs.items()):
            if key in keys or not vanilla:
                continue
            lines = {}
            if vanilla.get("local_population_capacity"):
                lines["local_population_capacity"] = _fmt(-vanilla["local_population_capacity"])
            if vanilla.get("local_population_capacity_modifier"):
                lines["local_population_capacity_modifier"] = _fmt(-vanilla["local_population_capacity_modifier"])
            if vanilla.get(FOOD_KEY):
                lines[FOOD_KEY] = _fmt(-vanilla[FOOD_KEY])
            for name, v in legacy.get(parents.get(key, key), {}).items():
                lines.setdefault(name, v)
            if lines:
                blocks.append(render_block(f"TRY_INJECT:{key}", lines, nested="location_modifier"))
        text = "\n\n".join([GENERATED, f"# {attribute}: flat capacity rows (people / 1000) and goods output rows from the World Builder fit,", "# vanilla capacity and food values of each class cancelled exactly, legacy balance effects re-keyed by dominant vanilla parent.", *blocks]) + "\n"
        path = mod_root / "in_game/common" / directory / "pp_wb_attribute_rows.txt"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("﻿" + text, encoding="utf-8", newline="\n")
        written[attribute] = len(blocks)
    return written


def static_modifier_bodies(vanilla_root: Path, pattern: str) -> dict[str, list[str]]:
    """Vanilla location static-modifier block lines (inside the braces) for names matching ``pattern``,
    without their population-capacity and food lines."""
    path = vanilla_root / "game/main_menu/common/static_modifiers/location.txt"
    bodies: dict[str, list[str]] = {}
    current: str | None = None
    depth = 0
    for raw in path.read_text(encoding="utf-8-sig").splitlines():
        line = raw.split("#", 1)[0]
        stripped = line.strip()
        if depth == 0:
            match = re.match(rf"^({pattern})\s*=\s*\{{", stripped)
            if match:
                current = match.group(1)
                bodies[current] = []
                depth = 1
                continue
        elif current is not None:
            depth += line.count("{") - line.count("}")
            if depth <= 0:
                current = None
                depth = 0
                continue
            if stripped and "local_population_capacity" not in stripped and FOOD_KEY not in stripped:
                bodies[current].append(stripped)
    return bodies


def river_bodies(vanilla_root: Path) -> dict[int, list[str]]:
    """Vanilla river_flowing_through_<n> block lines without the capacity percentage."""
    return {int(name.rsplit("_", 1)[1]): body for name, body in static_modifier_bodies(vanilla_root, r"river_flowing_through_\d+").items()}


# Note: vanilla's `development` static modifier (+2.5% capacity per point) is already replaced without its
# capacity line by the mod's hand-authored pp_location_modifier_adjustments.txt, so no percentage remains.


def setup_modifier_keys(contract: Contract, navigation: Mapping[str, object] | None = None) -> dict[str, list[str]]:
    """Location tag -> the attribute modifiers the setup places: fertility, soil, sea coast, lake shore, and the
    navigation site markers when ``navigation`` (the prepared navigation state) is given.

    The starting-building caps and gates read them with has_location_modifier, so the offline start placement needs
    the same list the setup file gets."""
    per_location: dict[str, list[str]] = defaultdict(list)
    attrs = contract.location_attributes
    tags = [str(t) for t in attrs["location_tag"].to_list()]
    for attribute, prefix in (("fertility", "pp_wb_fertility_"), ("soil_type", "pp_wb_soil_")):
        if attribute in attrs.columns:
            for tag, value in zip(tags, attrs[attribute].to_list()):
                if value and str(value) != "None":
                    per_location[tag].append(f"{prefix}{value}")
    for attribute, key in (("is_coastal", "pp_wb_coastal"), ("is_adjacent_to_lake", "pp_wb_lake")):
        if attribute in attrs.columns:
            for tag, flag in zip(tags, attrs[attribute].to_list()):
                if str(flag).lower() == "true":   # the handover CSV writes lowercase booleans
                    per_location[tag].append(key)
    if navigation:
        from .navigation import site_markers
        for tag, keys in site_markers(navigation).items():
            per_location[tag].extend(keys)
    return per_location


def write_static_modifiers(contract: Contract, cfg: WorldBuilderConfig, mod_root: Path, vanilla_root: Path, rgo_by_location: Mapping[str, str] | None = None) -> dict[str, object]:
    rows = class_rows(contract)
    names: dict[str, str] = {}
    blocks: list[str] = []
    per_location = setup_modifier_keys(contract, cfg.raw.get("_navigation"))   # location tag -> modifier keys
    attrs = contract.location_attributes
    for attribute, prefix in (("fertility", "pp_wb_fertility_"), ("soil_type", "pp_wb_soil_")):
        if attribute not in attrs.columns:
            continue
        column = [str(v) for v in attrs[attribute].to_list()]
        tags = attrs["location_tag"].to_list()
        # one modifier per class that occurs on the map, reference classes included (they carry no rows but the
        # building caps and gates test for them with has_location_modifier)
        classes = sorted({v for v in column if v and v != "None"} | {value for (attr, value), mods in rows.items() if attr == attribute and mods})
        for value in classes:
            mods = rows.get((attribute, value), {})
            key = f"{prefix}{value}"
            names[key] = f"{pretty(value)} {'Fertility' if attribute == 'fertility' else 'Soil'}"
            blocks.append(render_block(key, {"game_data": "{ category = location }", **{k: _fmt(v) for k, v in mods.items()}}))
    flavour = cfg.raw.get("flavour") if isinstance(cfg.raw.get("flavour"), dict) else {}
    for attribute, key, label in (("is_coastal", "pp_wb_coastal", "Coastal Land"), ("is_adjacent_to_lake", "pp_wb_lake", "Lakeside Land")):
        mods = rows.get((attribute, "True"), {})
        # hand-set flavour effects ([worldbuilder.flavour.<key>]) sit next to the fitted rows, never on capacity or goods output
        extra = {str(k): float(v) for k, v in (flavour.get(key) or {}).items()}
        clash = sorted(k for k in extra if k in mods or k in CAPACITY_KEYS or k.endswith("_output_modifier"))
        if clash:
            raise ValueError(f"[worldbuilder.flavour.{key}] must not set fitted keys: {clash}")
        # always defined (possibly empty): the location window shows the modifier's effects
        names[key] = label
        blocks.append(render_block(key, {"game_data": "{ category = location }", **{k: _fmt(v) for k, v in {**mods, **extra}.items()}}))
    # vanilla's hidden flat capacity by closeness to the equator: cancelled, capacity is farmland only
    blocks.append(render_block("TRY_REPLACE:location_closeness_to_equator_impact", {"game_data": "{ category = location }"}))
    static_path = mod_root / STATIC_MODIFIERS_PATH
    static_path.parent.mkdir(parents=True, exist_ok=True)
    static_path.write_text("﻿" + "\n\n".join([GENERATED, *blocks]) + "\n", encoding="utf-8", newline="\n")

    # rivers: vanilla body minus the capacity percentage, plus the level's rows
    bodies = river_bodies(vanilla_root)
    legacy_rivers = legacy_river_lines(mod_root)
    river_blocks: list[str] = []
    for level, body in sorted(bodies.items()):
        mods = rows.get(("river_level", str(level)), {})
        merged = merge_modifier_lines(body, legacy_rivers.get(level, []))
        extra = [f"\t{k} = {_fmt(v)}" for k, v in mods.items()]
        river_blocks.append("\n".join([f"TRY_REPLACE:river_flowing_through_{level} = {{", *[f"\t{l}" for l in merged], *extra, "}"]))
    (mod_root / RIVER_MODIFIERS_PATH).parent.mkdir(parents=True, exist_ok=True)
    (mod_root / RIVER_MODIFIERS_PATH).write_text("﻿" + "\n\n".join([GENERATED, "# River capacity percentages and food modifiers removed; World Builder river-level rows added (levels 1..5 = engine river sizes); the mod's hand-authored river injects are folded in (an inject into a replaced block is ignored by the engine).", *river_blocks]) + "\n", encoding="utf-8", newline="\n")

    # no goods intercept modifier: the per-good base output at the RGO is the hand-authored raw-material bonus
    # (pp_rgo_bonus_<good>, re-applied when the raw material changes); the fit intercept is dropped

    # goods floor for the game's RGO, on the attribute rows alone (the raw-material bonus comes on top)
    floor_blocks: list[str] = []
    floor_names: dict[str, str] = {}
    lifted = 0
    predicted_rows = rgo_row_predictions(contract, rgo_by_location) if rgo_by_location is not None else {}
    for tag, (good, predicted) in sorted(predicted_rows.items()):
        lift = round(cfg.goods_floor - predicted, 2)
        if lift < 0.005:
            continue
        key = f"pp_wb_rgo_floor_{tag}"
        floor_blocks.append(render_block(key, {"game_data": "{ category = location }", f"local_{good}_output_modifier": _fmt(lift)}))
        floor_names[key] = "Established Local Produce"
        per_location[tag].append(key)
        lifted += 1
    (mod_root / FLOOR_MODIFIERS_PATH).parent.mkdir(parents=True, exist_ok=True)
    (mod_root / FLOOR_MODIFIERS_PATH).write_text("﻿" + "\n\n".join([GENERATED, f"# Lifts the game's own RGO to at least {_fmt(cfg.goods_floor)} output where the attribute rows would leave it lower (the raw-material bonus comes on top).", *floor_blocks]) + "\n", encoding="utf-8", newline="\n")

    # flat capacity per development point (the handover's known term), written INTO the hand-authored
    # TRY_REPLACE:development block: the engine ignores a TRY_INJECT into a block the mod itself replaces
    write_development_capacity(mod_root, contract.people_per_development_point)
    # overpopulation effects live in the hand-authored pp_capacity_pressure_effects.txt
    legacy = mod_root / "main_menu/common/static_modifiers/pp_wb_overpopulation.txt"
    if legacy.is_file():
        legacy.unlink()

    # on_action applying the per-location static modifiers
    if cfg.raw.get("_navigation"):
        from .navigation import write_bonus_compensation
        for tag, keys in write_bonus_compensation(cfg.raw['_navigation'], mod_root, vanilla_root).items():
            per_location[tag].extend(keys)
    lines = [GENERATED, "", "on_game_start = {", "\ton_actions = {", "\t\tpp_wb_apply_attribute_modifiers", "\t}", "}", "", "pp_wb_apply_attribute_modifiers = {", "\teffect = {"]
    for tag in sorted(per_location):
        keys = per_location[tag]
        lines.append(f"\t\tlocation:{tag} = {{")
        for key in keys:
            lines.append(f"\t\t\tadd_location_modifier = {{ modifier = {key} months = -1 mode = replace }}")
        lines.append("\t\t}")
    lines.extend(["\t}", "}", ""])
    (mod_root / ON_ACTION_PATH).parent.mkdir(parents=True, exist_ok=True)
    (mod_root / ON_ACTION_PATH).write_text("﻿" + "\n".join(lines), encoding="utf-8", newline="\n")
    # the same modifiers in the game-start setup: the building caps are validated during bookmark
    # instantiation, before on_game_start, so the modifiers must already be on the location then
    write_setup_modifiers(per_location, mod_root)

    # localization
    loc = ["l_english:"]
    for key, label in {**names, **floor_names}.items():
        loc.append(f'  STATIC_MODIFIER_NAME_{key}: "{label}"')
    loc.append('  STATIC_MODIFIER_DESC_pp_wb_rgo_floor: "The people here have always produced this; the established trade keeps its output up even where the land is poor for it."')
    for key in names:
        loc.append(f'  STATIC_MODIFIER_DESC_{key}: "Subsistence land and goods output from this attribute, fitted from geography and historical land use."')
    (mod_root / LOCALIZATION_PATH).parent.mkdir(parents=True, exist_ok=True)
    (mod_root / LOCALIZATION_PATH).write_text("﻿" + "\n".join(loc) + "\n", encoding="utf-8", newline="\n")

    for rel in LEGACY_OUTPUTS:
        path = mod_root / rel
        if path.is_file():
            path.unlink()
    return {"static_modifiers": len(blocks), "river_levels": len(river_blocks), "floor_lifts": lifted, "locations_with_modifiers": len(per_location)}


GOODS_TRIGGERS_PATH = Path("in_game/common/scripted_triggers/goods_triggers.txt")
SETUP_RGO_TRIGGERS_PATH = Path("in_game/common/scripted_triggers/pp_wb_setup_rgos.txt")
# goods whose RGO potential tests vegetation only: vanilla's setup RGO must survive the World Builder vegetation
SETUP_RGO_GOODS = {"lumber": "location_wants_lumber_trigger"}


def write_setup_rgo_keepers(mod_root: Path, rgo_by_location: Mapping[str, str]) -> dict[str, int]:
    """Keep the game's setup RGOs whose goods potential no longer matches the World Builder vegetation.

    The game validates each setup RGO against its goods ``location_potential`` and drops the RGO when it fails
    (``setup to have 'raw_material = lumber' but it failed the 'location_potential' trigger``). The design keeps
    the game's RGOs, so ``pp_wb_setup_<good>_location`` lists those locations by tag (valid during setup) and is
    ORed into the goods trigger that the compat patches wrote into goods_triggers.txt.
    """
    templates = (mod_root / "in_game/map_data/location_templates.txt").read_text(encoding="utf-8-sig")
    vegetation = {m[1]: m[2] for m in re.finditer(r"(?m)^(\w+)\s*=\s*\{[^}\n]*?\bvegetation\s*=\s*(\w+)", templates)}
    triggers_path = mod_root / GOODS_TRIGGERS_PATH
    goods_triggers = triggers_path.read_text(encoding="utf-8-sig")
    lines = [GENERATED]
    kept: dict[str, int] = {}
    for good, trigger in SETUP_RGO_GOODS.items():
        body = re.search(rf"(?ms)^{trigger}\s*=\s*\{{\s*\n(\s*)OR\s*=\s*\{{\n(.*?)^\}}", goods_triggers)
        if not body:
            raise ValueError(f"{GOODS_TRIGGERS_PATH}: {trigger} is not a single top-level OR")
        branch = f"pp_wb_setup_{good}_location = yes"
        if branch not in body[2]:
            goods_triggers = goods_triggers[:body.start(2)] + f"{body[1]}\t{branch}\n" + goods_triggers[body.start(2):]
        allowed = set(re.findall(r"vegetation\s*=\s*(\w+)", body[2]))
        tags = sorted(tag for tag, rgo in rgo_by_location.items() if rgo == good and vegetation.get(tag) not in allowed)
        kept[good] = len(tags)
        lines.append(f"pp_wb_setup_{good}_location = {{")
        lines.append("\tOR = { " + " ".join(f"this = location:{t}" for t in tags) + " }" if tags else "\talways = no")
        lines.append("}")
    triggers_path.write_text("﻿" + goods_triggers, encoding="utf-8", newline="\n")
    path = mod_root / SETUP_RGO_TRIGGERS_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("﻿" + "\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return kept


def write_setup_modifiers(per_location: Mapping[str, list[str]], mod_root: Path) -> int:
    """Permanent per-location modifiers in the setup so they exist when starting buildings are validated."""
    lines = [GENERATED, "# Permanent attribute modifiers placed at game start; on_game_start re-applies the same keys (mode = replace).", "locations = {"]
    for tag in sorted(per_location):
        keys = per_location[tag]
        if not keys:
            continue
        lines.append(f"\t{tag} = {{")
        lines.append("\t\ttimed_modifiers = {")
        lines.append("\t\t\ttimed_modifiers = {")
        for key in keys:
            lines.append(f"\t\t\t\t{{ modifier = \"{key}\" start_date = 1111.1.1 date = 9999.1.1 size = 1 }}")
        lines.append("\t\t\t}")
        lines.append("\t\t}")
        lines.append("\t}")
    lines.append("}")
    path = mod_root / SETUP_MODIFIERS_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\ufeff" + "\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return sum(1 for keys in per_location.values() if keys)


def write_development_capacity(mod_root: Path, people_per_point: float) -> bool:
    """Set (or remove) the flat capacity line inside the mod's TRY_REPLACE:development block; idempotent."""
    path = mod_root / ADJUSTMENTS_PATH
    if not path.is_file():
        if not people_per_point:
            return False
        raise FileNotFoundError(f"{path}: the hand-authored development replacement is missing")
    raw = path.read_bytes()
    bom = raw.startswith(b"\xef\xbb\xbf")
    text = raw.decode("utf-8-sig")
    match = re.search(r"^TRY_REPLACE:development = \{\n(?P<body>.*?)^\}", text, re.M | re.S)
    if match is None:
        raise ValueError(f"{path}: no TRY_REPLACE:development block")
    body = match.group("body")
    lines = [l for l in body.splitlines() if "local_population_capacity" not in l and DEVELOPMENT_MARK not in l and "no population capacity from development" not in l]
    if people_per_point:
        lines.append(f"\t{DEVELOPMENT_MARK}")
        lines.append(f"\tlocal_population_capacity = {_fmt(people_per_point / 1000.0)}")
    else:
        lines.append("\t# no population capacity from development: capacity is farmland (World Builder attribute rows + improvement buildings)")
    new_body = "\n".join(lines).rstrip("\n") + "\n"
    if new_body == body:
        return False
    text = text[: match.start("body")] + new_body + text[match.end("body"):]
    path.write_bytes((b"\xef\xbb\xbf" if bom else b"") + text.encode("utf-8"))
    return True


def legacy_river_lines(mod_root: Path) -> dict[int, list[str]]:
    """Lines of the hand-authored ``TRY_INJECT:river_flowing_through_<n>`` blocks (capacity and food lines dropped)."""
    path = mod_root / ADJUSTMENTS_PATH
    if not path.is_file():
        return {}
    text = path.read_text(encoding="utf-8-sig")
    out: dict[int, list[str]] = {}
    for match in re.finditer(r"^TRY_INJECT:river_flowing_through_(\d)\s*=\s*\{\n(?P<body>.*?)^\}", text, re.M | re.S):
        lines = []
        for raw in match.group("body").splitlines():
            line = raw.split("#", 1)[0].strip()
            if not line or "=" not in line:
                continue
            key = line.split("=", 1)[0].strip()
            if key in CAPACITY_KEYS or key == FOOD_KEY:
                continue
            lines.append(line)
        out[int(match.group(1))] = lines
    return out


def merge_modifier_lines(body: list[str], extra: list[str]) -> list[str]:
    """Vanilla block lines plus the mod's inject lines; a key present in both is summed (injects were additive)."""
    merged = list(body)
    for line in extra:
        key, _, value = line.partition("=")
        key, value = key.strip(), value.strip()
        for i, existing in enumerate(merged):
            ek, _, ev = existing.partition("=")
            if ek.strip() == key:
                try:
                    merged[i] = f"{key} = {_fmt(float(ev.strip()) + float(value))}"
                except ValueError:
                    merged[i] = f"{key} = {value}"
                break
        else:
            merged.append(f"{key} = {value}")
    return merged
