"""Keep vanilla scripts that send fleets over the open sea away from the navigable river channels.

The World Builder's navigable rivers are sea zones (all in region ``pp_navigation_region``). A river-bank location
is therefore ``is_coastal`` and can hold a port, but most channel groups never reach the open sea. A vanilla script
that picks a coastal location or a port and then routes a fleet there over water (``find_route``) finds no route
when it picks a river bank, leaves its route variables unset and fails at run time, e.g. the Chinese treasure
voyage: "Failed to fetch variable for 'chinese_treasure_next_location' due to not being set".

``[worldbuilder.navigation_scripts]`` lists every vanilla file that routes fleets (``ROUTING``) or spawns navies
(``NAVAL_SPAWNS``): ``patches`` are copied from the current vanilla file with exact text replacements (a replacement
whose text no longer occurs the configured number of times fails the build), ``reviewed`` need no patch and say
why. ``unlisted`` finds vanilla files that use these effects and are in neither list, so a game update that adds one
fails ``ppc worldbuilder apply`` and the tests instead of failing in a campaign.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

NAVIGATION_REGION = "pp_navigation_region"
TRIGGER_RELATIVE_PATH = Path("in_game/common/scripted_triggers/pp_navigation_sea_triggers.txt")
MANIFEST_RELATIVE_PATH = Path("artifacts/data/worldbuilder/navigation_script_patches.json")
HEADER = "# Generated by ppc worldbuilder: vanilla file patched so fleets sent over the open sea never target a river channel; do not edit by hand."
# effects that need a water route between two locations
ROUTING = ("find_route",)
# effects that put ships on the map at a scripted location (no route needed; a river channel is a legal place)
NAVAL_SPAWNS = ("sub_unit_category:navy_", "spawn_navy_levy_unit", "create_navy")
SCANNED_DIRS = ("in_game/events", "in_game/common")
TRIGGERS = f"""﻿# Generated by ppc worldbuilder (navigation_scripts.py); do not edit by hand.
# The vanilla sense of "coastal": the location borders water that is not a navigable river channel. The channels
# are sea zones in region {NAVIGATION_REGION}, so is_coastal alone is also true on every river bank.
pp_is_sea_coast = {{
\tis_coastal = yes
\tany_neighbor_location = {{
\t\tis_land = no
\t\tNOT = {{ region = region:{NAVIGATION_REGION} }}
\t}}
}}
"""


@dataclass(frozen=True)
class Replacement:
    find: str
    replace: str
    count: int


@dataclass(frozen=True)
class ScriptsConfig:
    patches: dict[str, list[Replacement]]
    reviewed: dict[str, str]

    @property
    def listed(self) -> set[str]:
        return set(self.patches) | set(self.reviewed)


def load(raw: dict[str, Any] | None) -> ScriptsConfig:
    section = raw or {}
    patches: dict[str, list[Replacement]] = {}
    for entry in section.get("patches") or []:
        rel = str(entry["file"])
        patches[rel] = [Replacement(str(r["find"]), str(r["with"]), int(r.get("count", 1))) for r in entry.get("replace") or []]
        if not patches[rel]:
            raise ValueError(f"[worldbuilder.navigation_scripts] patch for {rel} has no replacements")
    reviewed = {str(k): str(v) for k, v in (section.get("reviewed") or {}).items()}
    both = set(patches) & set(reviewed)
    if both:
        raise ValueError(f"[worldbuilder.navigation_scripts] files both patched and reviewed: {sorted(both)}")
    return ScriptsConfig(patches, reviewed)


def _code(text: str) -> str:
    return "\n".join(line.split("#", 1)[0] for line in text.splitlines())


def scan(vanilla_root: Path) -> dict[str, list[str]]:
    """Vanilla files (paths relative to ``game/``) that use a routing or naval spawn effect outside comments."""
    game = Path(vanilla_root) / "game"
    found: dict[str, list[str]] = {}
    for top in SCANNED_DIRS:
        for path in sorted((game / top).rglob("*.txt")):
            code = _code(path.read_text(encoding="utf-8-sig", errors="replace"))
            hits = [p for p in (*ROUTING, *NAVAL_SPAWNS) if re.search(re.escape(p), code)]
            if hits:
                found[path.relative_to(game).as_posix()] = hits
    return found


def unlisted(vanilla_root: Path, cfg: ScriptsConfig) -> dict[str, list[str]]:
    """Vanilla files that route or spawn fleets and are neither patched nor reviewed."""
    return {rel: hits for rel, hits in scan(vanilla_root).items() if rel not in cfg.listed}


def unpatched_routing(vanilla_root: Path, cfg: ScriptsConfig) -> dict[str, list[str]]:
    """Reviewed-only files that route fleets; each needs its review reason to say why no patch is needed."""
    return {rel: [h for h in hits if h in ROUTING] for rel, hits in scan(vanilla_root).items()
            if rel in cfg.reviewed and any(h in ROUTING for h in hits)}


def patch_text(text: str, replacements: list[Replacement], rel: str) -> str:
    for r in replacements:
        found = text.count(r.find)
        if found != r.count:
            raise ValueError(f"{rel}: expected {r.count} occurrence(s) of {r.find!r}, found {found}; vanilla changed, review the patch")
        text = text.replace(r.find, r.replace)
    return text


def write(vanilla_root: Path, mod_root: Path, repo: Path, cfg: ScriptsConfig, compat_files: list[str] = ()) -> dict[str, object]:
    """Write the trigger and the patched copies. Runs after the class-test widening (compat.py): a file on both lists
    is patched on top of its widened copy."""
    from . import compat as wb_compat
    missing = unlisted(vanilla_root, cfg)
    if missing:
        raise ValueError("vanilla scripts route or spawn fleets but are not in [worldbuilder.navigation_scripts] "
                         "(patch them or list them as reviewed): " + "; ".join(f"{k} ({', '.join(v)})" for k, v in missing.items()))
    trigger = mod_root / TRIGGER_RELATIVE_PATH
    trigger.parent.mkdir(parents=True, exist_ok=True)
    trigger.write_text(TRIGGERS, encoding="utf-8", newline="\n")
    manifest_path = repo / MANIFEST_RELATIVE_PATH
    previous = json.loads(manifest_path.read_text(encoding="utf-8")).get("files", {}) if manifest_path.is_file() else {}
    files: dict[str, dict[str, object]] = {}
    for rel, replacements in cfg.patches.items():
        source = Path(vanilla_root) / "game" / rel
        if not source.is_file():
            raise FileNotFoundError(f"[worldbuilder.navigation_scripts] vanilla file not found: {source}")
        original = source.read_text(encoding="utf-8-sig")
        target = mod_root / rel
        base = original
        if rel in compat_files and target.is_file():
            widened = target.read_text(encoding="utf-8-sig")
            if widened.startswith(wb_compat.HEADER + "\n"):
                base = widened
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("﻿" + HEADER + "\n" + patch_text(base, replacements, rel), encoding="utf-8", newline="\n")
        files[rel] = {"vanilla_sha256": hashlib.sha256(original.encode("utf-8")).hexdigest(), "replacements": len(replacements)}
    for rel in previous:
        if rel not in files and (mod_root / rel).is_file():
            (mod_root / rel).unlink()
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps({"files": files, "reviewed": sorted(cfg.reviewed)}, indent=2) + "\n", encoding="utf-8")
    return {"patched": sorted(files), "reviewed": len(cfg.reviewed)}
