"""Keep vanilla scripts that send fleets over the open sea away from the navigable river channels.

The World Builder's navigable rivers are sea zones (all in region ``pp_navigation_region``). A river-bank location
is therefore ``is_coastal`` and can hold a port, but most channel groups never reach the open sea. A vanilla script
that picks a coastal location or a port and then routes a fleet there over water (``find_route``) finds no route
when it picks a river bank, leaves its route variables unset and fails at run time, e.g. the Chinese treasure
voyage: "Failed to fetch variable for 'chinese_treasure_next_location' due to not being set".

``[worldbuilder.navigation_scripts]`` lists every vanilla file that routes fleets (``ROUTING``), spawns navies
(``NAVAL_SPAWNS``) or sends an expedition along waypoints (``WAYPOINTS``, EU5 1.4): ``patches`` are copied from the
current vanilla file with exact text replacements (a replacement whose text no longer occurs the configured number of
times fails the build), ``reviewed`` need no patch and say why. ``unlisted`` finds vanilla files that use these effects
and are in neither list, so a game update that adds one fails ``ppc worldbuilder apply`` and the tests instead of
failing in a campaign.

EU5 1.4 expeditions (``common/expedition_types``): a ``travel_mode = sea`` expedition paths each leg over open water
only (the leg's end may be a port), so a leg to a river port whose channel group never reaches the sea fails
("failed expedition path"). Scripted departure ports of sea expeditions are patched to the sea coast; their static
waypoints (``sea_expedition_waypoints``) must be sea tiles or sea-coast land, which the tests check on the mod map.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

NAVIGATION_REGION = "pp_navigation_region"
TRIGGER_RELATIVE_PATH = Path("in_game/common/scripted_triggers/pp_navigation_sea_triggers.txt")
MANIFEST_RELATIVE_PATH = Path("artifacts/data/worldbuilder/navigation_script_patches.json")
HEADER = "# Generated by ppc worldbuilder: vanilla file patched so fleets sent over the open sea never target a river channel; do not edit by hand."
# effects that need a water route between two locations (find_route until 1.3, create_route from 1.4)
ROUTING = ("find_route", "create_route")
# effects that put ships on the map at a scripted location (no route needed; a river channel is a legal place)
NAVAL_SPAWNS = ("sub_unit_category:navy_", "spawn_navy_levy_unit", "create_navy")
# expedition legs (EU5 1.4): pathfound by the engine in the expedition type's travel_mode; harmless for land/both
WAYPOINTS = ("add_new_waypoint",)
SCANNED_DIRS = ("in_game/events", "in_game/common")
TRIGGERS = f"""﻿# Generated by ppc worldbuilder (navigation_scripts.py); do not edit by hand.
# Water access, three exclusive states (worldbuilder/coast.py computes the same sets from the map offline):
# sea coast: borders passable sea that is neither a navigable river channel (region {NAVIGATION_REGION}) nor lake
# water; waterway: coastal only through river channels or navigable lakes; inland: is_coastal = no. The channels are
# sea zones, so is_coastal alone is also true on every river bank.
pp_is_sea_coast = {{
\tis_coastal = yes
\tany_neighbor_location = {{
\t\tis_land = no
\t\tNOT = {{ region = region:{NAVIGATION_REGION} }}
\t\tNOT = {{ topography = lakes }}
\t\tNOT = {{ topography = high_lakes }}
\t\tNOT = {{ topography = salt_pans }}
\t\tNOT = {{ topography = ocean_wasteland }}
\t}}
}}
pp_is_waterway = {{
\tis_coastal = yes
\tNOT = {{ pp_is_sea_coast = yes }}
}}
"""


@dataclass(frozen=True)
class Replacement:
    find: str
    replace: str
    count: int


@dataclass(frozen=True)
class ScriptsConfig:
    patches: dict[str, list[Replacement]]
    reviewed: dict[str, str]
    # vanilla files that test is_coastal / is_port and need no patch: why "any navigable water" (or nothing) is right
    water_reviewed: dict[str, str] = None
    sea_only_buildings: tuple[str, ...] = ()

    @property
    def listed(self) -> set[str]:
        return set(self.patches) | set(self.reviewed)

    @property
    def water_listed(self) -> set[str]:
        return set(self.patches) | set(self.water_reviewed or {})


def load(raw: dict[str, Any] | None) -> ScriptsConfig:
    section = raw or {}
    patches: dict[str, list[Replacement]] = {}
    for entry in section.get("patches") or []:
        rel = str(entry["file"])
        patches[rel] = [Replacement(str(r["find"]), str(r["with"]), int(r.get("count", 1))) for r in entry.get("replace") or []]
        if not patches[rel]:
            raise ValueError(f"[worldbuilder.navigation_scripts] patch for {rel} has no replacements")
    reviewed = {str(k): str(v) for k, v in (section.get("reviewed") or {}).items()}
    both = set(patches) & set(reviewed)
    if both:
        raise ValueError(f"[worldbuilder.navigation_scripts] files both patched and reviewed: {sorted(both)}")
    water = {str(k): str(v) for k, v in (section.get("water_access_reviewed") or {}).items()}
    both = set(patches) & set(water)
    if both:
        raise ValueError(f"[worldbuilder.navigation_scripts] files both patched and water-reviewed: {sorted(both)}")
    return ScriptsConfig(patches, reviewed, water, tuple(str(k) for k in section.get("sea_only_buildings") or ()))


def _code(text: str) -> str:
    return "\n".join(line.split("#", 1)[0] for line in text.splitlines())


def scan(vanilla_root: Path) -> dict[str, list[str]]:
    """Vanilla files (paths relative to ``game/``) that use a routing or naval spawn effect outside comments."""
    game = Path(vanilla_root) / "game"
    found: dict[str, list[str]] = {}
    for top in SCANNED_DIRS:
        for path in sorted((game / top).rglob("*.txt")):
            code = _code(path.read_text(encoding="utf-8-sig", errors="replace"))
            hits = [p for p in (*ROUTING, *NAVAL_SPAWNS, *WAYPOINTS) if re.search(re.escape(p), code)]
            if hits:
                found[path.relative_to(game).as_posix()] = hits
    return found


EXPEDITION_TYPES_DIR = "in_game/common/expedition_types"
EXPEDITION_EVENTS_DIR = "in_game/events/expeditions"


def sea_expedition_waypoints(vanilla_root: Path) -> dict[str, list[str]]:
    """Named locations an open-sea expedition (``travel_mode = sea``) sails to: its static ``waypoints`` and every
    ``add_new_waypoint = location:x`` in its type file and in its events file (``<type file>_events.txt``).
    Location -> files naming it."""
    game = Path(vanilla_root) / "game"
    found: dict[str, list[str]] = {}
    for path in sorted((game / EXPEDITION_TYPES_DIR).glob("*.txt")):
        code = _code(path.read_text(encoding="utf-8-sig", errors="replace"))
        if not re.search(r"\btravel_mode\s*=\s*sea\b", code):
            continue
        sources = [path, game / EXPEDITION_EVENTS_DIR / f"{path.stem}_events.txt"]
        for source in sources:
            if not source.is_file():
                continue
            text = _code(source.read_text(encoding="utf-8-sig", errors="replace"))
            names = re.findall(r"\badd_new_waypoint\s*=\s*location:([A-Za-z0-9_]+)", text)
            for m in re.finditer(r"\bwaypoints\s*=\s*\{([^}]*)\}", text):
                names += re.findall(r"[A-Za-z0-9_]+", m.group(1))
            for name in names:
                rel = source.relative_to(game).as_posix()
                if rel not in found.setdefault(name, []):
                    found[name].append(rel)
    return found


# Water access review: the channels made every river bank is_coastal (and many of them ports). Vanilla wrote its tests
# before there were channels, so "sea coast" reproduces vanilla and "any navigable water" is the deliberate extension.
# Every vanilla file that tests is_coastal / is_port is patched (sea only, pp_is_sea_coast) or reviewed with a reason.
WATER_TOKENS = ("is_coastal", "is_port")
WATER_SCANNED_DIRS = ("in_game", "main_menu")


def scan_water(vanilla_root: Path) -> dict[str, list[str]]:
    game = Path(vanilla_root) / "game"
    found: dict[str, list[str]] = {}
    for top in WATER_SCANNED_DIRS:
        for path in sorted((game / top).rglob("*.txt")):
            code = _code(path.read_text(encoding="utf-8-sig", errors="replace"))
            hits = [t for t in WATER_TOKENS if re.search(rf"\b{t}\b", code)]
            if hits:
                found[path.relative_to(game).as_posix()] = hits
    return found


def unlisted_water(vanilla_root: Path, cfg: ScriptsConfig) -> dict[str, list[str]]:
    """Vanilla files that test is_coastal / is_port and are neither patched nor water-reviewed."""
    return {rel: hits for rel, hits in scan_water(vanilla_root).items() if rel not in cfg.water_listed}


SEA_BUILDINGS_RELATIVE_PATH = Path("in_game/common/building_types/zzzz_pp_water_access_buildings.txt")


def _block(text: str, start: int) -> tuple[int, int]:
    """(open, close) index of the brace block that starts at or after ``start``."""
    open_ = text.index("{", start)
    depth = 0
    for i in range(open_, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return open_, i
    raise ValueError("unbalanced braces")


def sea_only_potential(body: str) -> str:
    """The building's location_potential with its water tests narrowed to the sea coast."""
    code = _code(body)
    m = re.search(r"(?m)^\s*location_potential\s*=\s*\{", code)
    if not m:
        return "pp_is_sea_coast = yes"
    open_, close = _block(code, m.start())
    inner = code[open_ + 1:close]
    narrowed = re.sub(r"\bis_coastal\s*=\s*yes\b", "pp_is_sea_coast = yes", inner)
    narrowed = re.sub(r"\bis_port\s*=\s*yes\b", "is_port = yes pp_is_sea_coast = yes", narrowed)
    if narrowed == inner:
        narrowed = inner.rstrip() + "\n\tpp_is_sea_coast = yes\n"
    return narrowed.strip()


SEA_BUILDINGS_LOCALIZATION_RELATIVE_PATH = Path("main_menu/localization/english/pp_water_access_buildings_l_english.yml")


def sea_only_building(key: str, body: str) -> tuple[str, dict[str, str]]:
    """``REPLACE:<key>`` of a vanilla building body with its location_potential narrowed to the sea coast (added when it
    has none) and its unique methods renamed ``pp_<key>_<method>`` (a REPLACE leaves the vanilla methods registered, so
    the old names would be duplicates). Returns the block and new method name -> vanilla method name."""
    code = _code(body)
    potential = sea_only_potential(code).replace("\n", "\n\t")
    m = re.search(r"(?m)^\s*location_potential\s*=\s*\{", code)
    if m:
        open_, close = _block(code, m.start())
        code = code[:open_ + 1] + "\n\t\t" + potential + "\n\t" + code[close:]
    else:
        code = code.rstrip() + "\n\tlocation_potential = {\n\t\t" + potential + "\n\t}\n"
    renamed: dict[str, str] = {}
    for m in reversed(list(re.finditer(r"\bunique_production_methods\s*=\s*\{", code))):
        open_, close = _block(code, m.start())
        inner, depth, out, i = code[open_ + 1:close], 0, [], 0
        for tm in re.finditer(r"[{}]|\b([A-Za-z_][A-Za-z_0-9]*)(\s*=\s*\{)", inner):
            if tm.group(0) == "{":
                depth += 1
            elif tm.group(0) == "}":
                depth -= 1
            elif tm.group(1) and depth == 0:
                new = f"pp_{key}_{tm.group(1)}"
                renamed[new] = tm.group(1)
                out.append(inner[i:tm.start()] + new + tm.group(2))
                i = tm.end()
                depth += 1
        code = code[:open_ + 1] + "".join(out) + inner[i:] + code[close:]
    return f"REPLACE:{key} = {{{code.rstrip()}\n}}", renamed


def write_sea_only_buildings(vanilla_root: Path, mod_root: Path, keys: list[str]) -> list[str]:
    """REPLACE vanilla buildings that belong on the open sea (pirates, sea salt, overseas trade, regional sea
    institutions) with their own definition whose is_coastal / is_port tests are narrowed to the sea coast. EU5 1.4
    reads a building's location_potential once: a second one in an INJECT is dropped ("Trigger section already read
    earlier"), so the whole building is replaced. The body comes from the mod's copy of the vanilla file when the
    compat step wrote one (widened class tests), else from vanilla; the file loads after the buildings' footprint
    INJECTs and is their footprint owner (building_footprint.owner_blocks)."""
    folder = Path(vanilla_root) / "game/in_game/common/building_types"
    found: dict[str, str] = {}
    for path in sorted(folder.glob("*.txt")):
        copy = Path(mod_root) / "in_game/common/building_types" / path.name
        text = (copy if copy.is_file() else path).read_text(encoding="utf-8-sig", errors="replace")
        for key in keys:
            m = re.search(rf"(?m)^{re.escape(key)}\s*=\s*\{{", text)
            if m and key not in found:
                open_, close = _block(text, m.start())
                found[key] = text[open_ + 1:close]
    missing = sorted(set(keys) - set(found))
    if missing:
        raise ValueError(f"[worldbuilder.navigation_scripts] sea_only_buildings not in vanilla: {missing}")
    blocks, loc = [], ["﻿l_english:"]
    for key in keys:
        block, renamed = sea_only_building(key, found[key])
        blocks.append(block)
        loc += [f' {new}: "${old}$"' for new, old in renamed.items()]
    target = Path(mod_root) / SEA_BUILDINGS_RELATIVE_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("﻿" + HEADER.replace("fleets sent over the open sea never target a river channel",
                                                 "these buildings stay on the open sea coast") + "\n" + "\n\n".join(blocks) + "\n",
                      encoding="utf-8", newline="\n")
    path = Path(mod_root) / SEA_BUILDINGS_LOCALIZATION_RELATIVE_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(loc) + "\n", encoding="utf-8", newline="\n")
    return keys


def unlisted(vanilla_root: Path, cfg: ScriptsConfig) -> dict[str, list[str]]:
    """Vanilla files that route or spawn fleets and are neither patched nor reviewed."""
    return {rel: hits for rel, hits in scan(vanilla_root).items() if rel not in cfg.listed}


def unpatched_routing(vanilla_root: Path, cfg: ScriptsConfig) -> dict[str, list[str]]:
    """Reviewed-only files that route fleets; each needs its review reason to say why no patch is needed."""
    return {rel: [h for h in hits if h in ROUTING] for rel, hits in scan(vanilla_root).items()
            if rel in cfg.reviewed and any(h in ROUTING for h in hits)}


def patch_text(text: str, replacements: list[Replacement], rel: str) -> str:
    for r in replacements:
        found = text.count(r.find)
        if found != r.count:
            raise ValueError(f"{rel}: expected {r.count} occurrence(s) of {r.find!r}, found {found}; vanilla changed, review the patch")
        text = text.replace(r.find, r.replace)
    return text


def write(vanilla_root: Path, mod_root: Path, repo: Path, cfg: ScriptsConfig, compat_files: list[str] = ()) -> dict[str, object]:
    """Write the trigger and the patched copies. Runs after the class-test widening (compat.py): a file on both lists
    is patched on top of its widened copy."""
    from . import compat as wb_compat
    missing = unlisted(vanilla_root, cfg)
    if missing:
        raise ValueError("vanilla scripts route or spawn fleets but are not in [worldbuilder.navigation_scripts] "
                         "(patch them or list them as reviewed): " + "; ".join(f"{k} ({', '.join(v)})" for k, v in missing.items()))
    water = unlisted_water(vanilla_root, cfg)
    if water:
        raise ValueError("vanilla scripts test is_coastal / is_port but are not in [worldbuilder.navigation_scripts] "
                         "(patch them to pp_is_sea_coast or list them in water_access_reviewed): " + "; ".join(sorted(water)))
    trigger = mod_root / TRIGGER_RELATIVE_PATH
    trigger.parent.mkdir(parents=True, exist_ok=True)
    trigger.write_text(TRIGGERS, encoding="utf-8", newline="\n")
    if cfg.sea_only_buildings:
        write_sea_only_buildings(vanilla_root, mod_root, list(cfg.sea_only_buildings))
    manifest_path = repo / MANIFEST_RELATIVE_PATH
    previous = json.loads(manifest_path.read_text(encoding="utf-8")).get("files", {}) if manifest_path.is_file() else {}
    files: dict[str, dict[str, object]] = {}
    for rel, replacements in cfg.patches.items():
        source = Path(vanilla_root) / "game" / rel
        if not source.is_file():
            raise FileNotFoundError(f"[worldbuilder.navigation_scripts] vanilla file not found: {source}")
        original = source.read_text(encoding="utf-8-sig")
        target = mod_root / rel
        current = target.read_text(encoding="utf-8-sig", errors="replace") if target.is_file() else ""
        if current and not current.startswith("# Generated by ppc worldbuilder"):
            # A hand-authored override of the vanilla file (e.g. the event RGO fixes): the patch goes into that file
            # instead of replacing it with a patched vanilla copy. Idempotent: a find that is gone because its
            # replacement is already in the file is skipped.
            text = current
            for r in replacements:
                if r.find in r.replace:   # e.g. is_port = yes -> is_port = yes pp_is_sea_coast = yes: patch only the bare ones
                    text = text.replace(r.replace, "\0PP\0").replace(r.find, r.replace).replace("\0PP\0", r.replace)
                elif text.count(r.find):
                    text = text.replace(r.find, r.replace)
                elif r.replace not in text:
                    raise ValueError(f"{rel}: hand-authored override has neither {r.find!r} nor its replacement")
            if text != current:
                target.write_text("﻿" + text, encoding="utf-8", newline="\n")
            files[rel] = {"vanilla_sha256": hashlib.sha256(original.encode("utf-8")).hexdigest(), "replacements": len(replacements), "hand_authored": True}
            continue
        base = original
        if rel in compat_files and target.is_file():
            widened = target.read_text(encoding="utf-8-sig")
            if widened.startswith(wb_compat.HEADER + "\n"):
                base = widened
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("﻿" + HEADER + "\n" + patch_text(base, replacements, rel), encoding="utf-8", newline="\n")
        files[rel] = {"vanilla_sha256": hashlib.sha256(original.encode("utf-8")).hexdigest(), "replacements": len(replacements)}
    for rel in previous:
        stale = mod_root / rel
        # only our own generated copies; a hand-authored override that took the file over stays
        if rel not in files and stale.is_file() and stale.read_text(encoding="utf-8-sig", errors="replace").startswith(HEADER):
            stale.unlink()
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps({"files": files, "reviewed": sorted(cfg.reviewed)}, indent=2) + "\n", encoding="utf-8")
    return {"patched": sorted(files), "reviewed": len(cfg.reviewed)}
