"""Raw-material placement: Prosper or Perish's own rules instead of the goods' ``location_potential`` (EU5 1.4).

EU5 1.4 gave 21 goods a ``location_potential`` (climate, vegetation, topography, geography): where that good may be a
location's raw material. The engine caches it at load, logs every setup RGO that fails it, and the Columbian exchange
actions test it (``is_goods_valid_for_location``, the only script use in 1.4). In 1.3 those tests lived in the two
move-good actions themselves (lumber alone had a goods potential, ``location_wants_lumber_trigger``) and the mod kept
its own copies of them, on the World Builder classes. Jan, 2026-10-01: "Overwrite their rule, we have taken
responsibility over this."

- ``write_goods_without_placement_rules``: every vanilla goods file with a ``location_potential`` gets a same-name copy
  in the mod with those blocks removed. A file of the same relative path replaces vanilla's file whatever the rule (a
  ``REPLACE:`` of a good is ignored by the engine), so no good carries a placement rule and every setup RGO stands.
  The copies are regenerated from the current vanilla files on every ``ppc worldbuilder apply``.
- ``write_actions``: ``move_nw_good_to_new_location`` and ``move_ow_good_to_new_location`` are rebuilt from the current
  vanilla ``columbian_exchange.txt`` (every 1.4 change kept) with three edits: ``is_goods_valid_for_location`` becomes
  one ``trigger_if`` per good on the mod's placement triggers (``pp_<good>_placement_location`` in
  ``pp_raw_material_placement.txt``, the 1.3 rules on the World Builder classes; a good without one has no rule, as in
  1.3), the RGO bonus and orchard refresh follow ``change_raw_material``, and a gated crop (``[unlocks].goods`` of
  ``config/crop_farms.toml``) planted by a country outside its native lands (``pp_<stem>_native_country``) teaches that
  country to farm it (its general advance).
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

GOODS_DIR = Path("in_game/common/goods")
GOODS_HEADER = ("# Generated by ppc worldbuilder: vanilla goods file without the goods' location_potential (Prosper or Perish "
                "places raw materials itself, raw_material_placement.py); do not edit by hand.")
# the compat step's header (worldbuilder/compat.py): goods copies of earlier builds, before this module owned them
_OLD_GOODS_HEADERS = ("# Generated by ppc worldbuilder: vanilla file with every climate/vegetation/topography test widened",)
VANILLA_ACTIONS = Path("in_game/common/generic_actions/columbian_exchange.txt")
ACTIONS_PATH = Path("in_game/common/generic_actions/pp_columbian_exchange_rgo_refresh.txt")
PLACEMENT_TRIGGERS_PATH = Path("in_game/common/scripted_triggers/pp_raw_material_placement.txt")
# action -> the goods origin it moves (vanilla: has_origin_in_new_world / has_origin_in_old_world)
ACTIONS = {"move_nw_good_to_new_location": "origin_in_new_world", "move_ow_good_to_new_location": "origin_in_old_world"}
VALIDITY_TEST = "is_goods_valid_for_location = scope:target_good"
CHANGE_LINE = "change_raw_material = scope:target_good"
REFRESH_EFFECTS = ("pp_refresh_rgo_static_bonus = yes", "pp_refresh_fruit_orchard_eligibility = yes")
ACTIONS_HEADER = """\
# Generated by ppc worldbuilder (raw_material_placement.py) from vanilla columbian_exchange.txt; do not edit by hand.
# Prosper or Perish places raw materials itself: the goods carry no location_potential (EU5 1.4), so the two
# move-good actions test the mod's placement rules (scripted_triggers/pp_raw_material_placement.txt) instead of
# is_goods_valid_for_location, refresh the RGO bonus right after change_raw_material, and teach the acting country
# to farm a gated crop it planted outside its native lands. Everything else is vanilla's.
"""
_POTENTIAL_RE = re.compile(r"^[ \t]*location_potential\s*=\s*\{", re.M)
_TRIGGER_RE = re.compile(r"^pp_(?P<good>[a-z_]+)_placement_location\s*=\s*\{", re.M)


def _block_end(text: str, open_brace: int) -> int:
    """Index of the ``}`` that closes the ``{`` at ``open_brace`` (comments and quoted strings skipped)."""
    depth = 0
    i = open_brace
    while i < len(text):
        ch = text[i]
        if ch == "#":
            nl = text.find("\n", i)
            i = len(text) if nl < 0 else nl
            continue
        if ch == '"':
            close = text.find('"', i + 1)
            i = len(text) if close < 0 else close + 1
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    raise ValueError("unbalanced braces")


def _objects(text: str) -> dict[str, tuple[int, int]]:
    from prosper_or_perish_constructor.worldbuilder.compat import top_level_objects

    return {name: (start, end) for name, start, end in top_level_objects(text)}


def goods_potentials(text: str) -> dict[str, tuple[int, int]]:
    """Good -> (start, end) of its own ``location_potential = { ... }`` (the key's line start to past the brace)."""
    out: dict[str, tuple[int, int]] = {}
    for name, (start, end) in _objects(text).items():
        body_open = text.index("{", start)
        for match in _POTENTIAL_RE.finditer(text, body_open + 1, end):
            before = text[body_open + 1:match.start()]
            if before.count("{") != before.count("}"):
                continue   # a nested block of the same name, not the good's own key
            out[name] = (match.start(), _block_end(text, match.end() - 1) + 1)
            break
    return out


def strip_goods_potentials(text: str) -> tuple[str, list[str]]:
    """``text`` without every good's ``location_potential`` block (whole lines); returns (text, goods)."""
    spans = goods_potentials(text)
    for good, (start, end) in sorted(spans.items(), key=lambda item: -item[1][0]):
        line_end = text.find("\n", end)
        line_end = len(text) if line_end < 0 else line_end + 1
        rest = text[end:line_end].split("#", 1)[0]
        if rest.strip():
            raise ValueError(f"goods {good}: code after its location_potential on the same line: {rest.strip()!r}")
        text = text[:start] + text[line_end:]
    if _POTENTIAL_RE.search("\n".join(line.split("#", 1)[0] for line in text.splitlines())):
        raise ValueError("a location_potential is left in the goods file (not a good's own key)")
    return text, sorted(spans)


def _is_generated_goods_copy(path: Path) -> bool:
    try:
        first = path.read_text(encoding="utf-8-sig").split("\n", 1)[0]
    except (OSError, UnicodeDecodeError):
        return False
    return first == GOODS_HEADER or first.startswith(_OLD_GOODS_HEADERS)


def write_goods_without_placement_rules(mod_root: Path, vanilla_root: Path) -> dict[str, list[str]]:
    """Same-name copies of the vanilla goods files without the goods' ``location_potential``; file -> goods stripped.

    A vanilla goods file without a potential needs no copy: a generated copy left from an earlier build is removed.
    """
    stripped: dict[str, list[str]] = {}
    for vanilla_file in sorted((Path(vanilla_root) / "game" / GOODS_DIR).glob("*.txt")):
        target = mod_root / GOODS_DIR / vanilla_file.name
        text, goods = strip_goods_potentials(vanilla_file.read_text(encoding="utf-8-sig"))
        if not goods:
            if target.is_file() and _is_generated_goods_copy(target):
                target.unlink()
            continue
        if target.is_file() and not _is_generated_goods_copy(target):
            raise ValueError(f"{target}: a hand-written mod file has the name of a vanilla goods file; it would be replaced")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("﻿" + GOODS_HEADER + "\n" + text, encoding="utf-8", newline="\n")
        stripped[vanilla_file.name] = goods
    return stripped


# ------------------------------------------------------------------------------------------------- move-good actions


@dataclass(frozen=True)
class GatedCrop:
    good: str
    native_trigger: str
    advance: str


def placement_goods(text: str) -> list[str]:
    """The goods ``pp_raw_material_placement.txt`` defines a ``pp_<good>_placement_location`` for, in file order."""
    return [m["good"] for m in _TRIGGER_RE.finditer(text)]


def goods_origins(vanilla_root: Path) -> dict[str, set[str]]:
    """Good -> the ``origin_in_*`` flags it sets to yes in the vanilla goods files."""
    out: dict[str, set[str]] = {}
    for path in sorted((Path(vanilla_root) / "game" / GOODS_DIR).glob("*.txt")):
        text = path.read_text(encoding="utf-8-sig")
        for name, (start, end) in _objects(text).items():
            out[name] = set(re.findall(r"\b(origin_in_(?:new|old)_world)\s*=\s*yes\b", text[start:end]))
    return out


def gated_crops(repo: Path) -> list[GatedCrop]:
    from prosper_or_perish_constructor import crop_farms

    table = crop_farms.load_crop_table(repo)
    gated = set(table.gated_goods)
    return [GatedCrop(crop.good, crop_farms.native_trigger(crop), table.general_advance(crop)) for crop in table.crops if crop.good in gated]


def _replace_line(body: str, line: str, render) -> str:
    matches = list(re.finditer(rf"^(?P<indent>[ \t]*){re.escape(line)}[ \t]*$", body, re.M))
    if len(matches) != 1:
        raise ValueError(f"vanilla {VANILLA_ACTIONS.name}: expected one '{line}' per move-good action, found {len(matches)}")
    match = matches[0]
    return body[:match.start()] + render(match["indent"]) + body[match.end():]


def render_action(name: str, body: str, goods: list[str], crops: list[GatedCrop]) -> str:
    """One vanilla move-good action as the mod's ``TRY_REPLACE`` (``body``: ``name = { ... }`` from the vanilla file)."""

    def rules(indent: str) -> str:
        lines = [f"{indent}# Prosper or Perish: the mod's placement rules (pp_raw_material_placement.txt), not the goods' location_potential"]
        for good in goods:
            lines += [f"{indent}trigger_if = {{",
                      f"{indent}\tlimit = {{ scope:target_good ?= goods:{good} }}",
                      f"{indent}\tpp_{good}_placement_location = yes",
                      f"{indent}}}"]
        return "\n".join(lines)

    body = _replace_line(body, VALIDITY_TEST, rules)
    body = _replace_line(body, CHANGE_LINE, lambda indent: "\n".join(f"{indent}{line}" for line in (CHANGE_LINE, *REFRESH_EFFECTS)))
    effect = re.search(r"^\teffect\s*=\s*\{", body, re.M)
    if not effect:
        raise ValueError(f"vanilla {VANILLA_ACTIONS.name}: {name} has no effect block")
    close = _block_end(body, effect.end() - 1)
    if crops:
        lines = ["\t\t# a gated crop planted outside its native lands teaches the acting country to farm it (unless it already knows how)",
                 "\t\tscope:actor ?= {"]
        for crop in crops:
            lines += ["\t\t\tif = {",
                      "\t\t\t\tlimit = {",
                      f"\t\t\t\t\tscope:target_good = goods:{crop.good}",
                      "\t\t\t\t\tNOR = {",
                      f"\t\t\t\t\t\thas_advance = {crop.advance}",
                      f"\t\t\t\t\t\t{crop.native_trigger} = yes",
                      "\t\t\t\t\t}",
                      "\t\t\t\t}",
                      f"\t\t\t\tresearch_advance = advance_type:{crop.advance}",
                      "\t\t\t}"]
        lines.append("\t\t}")
        head = body[:close].rstrip(" \t")
        body = head + "\n".join(lines) + "\n" + body[len(head):close] + body[close:]
    if not body.startswith(name):
        raise ValueError(f"{name}: unexpected object text")
    return "TRY_REPLACE:" + body


def render_actions(vanilla_root: Path, repo: Path, triggers_text: str) -> str:
    vanilla = (Path(vanilla_root) / "game" / VANILLA_ACTIONS).read_text(encoding="utf-8-sig")
    objects = _objects(vanilla)
    goods = placement_goods(triggers_text)
    origins = goods_origins(vanilla_root)
    unknown = sorted(g for g in goods if g not in origins)
    if unknown:
        raise ValueError(f"{PLACEMENT_TRIGGERS_PATH}: placement rules for goods vanilla does not define: {', '.join(unknown)}")
    crops = gated_crops(repo)
    parts = []
    for name, origin in ACTIONS.items():
        if name not in objects:
            raise ValueError(f"vanilla {VANILLA_ACTIONS}: {name} is missing")
        start, end = objects[name]
        parts.append(render_action(name, vanilla[start:end], [g for g in goods if origin in origins[g]],
                                   [c for c in crops if origin in origins.get(c.good, set())]))
    return ACTIONS_HEADER + "\n" + "\n\n".join(parts) + "\n"


def write_actions(mod_root: Path, vanilla_root: Path, repo: Path) -> dict[str, object]:
    triggers = (mod_root / PLACEMENT_TRIGGERS_PATH).read_text(encoding="utf-8-sig")
    text = render_actions(vanilla_root, repo, triggers)
    path = mod_root / ACTIONS_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("﻿" + text, encoding="utf-8", newline="\n")
    return {"actions": list(ACTIONS), "placement_rules": placement_goods(triggers), "gated_crops": [c.good for c in gated_crops(repo)]}


def write(mod_root: Path, vanilla_root: Path, repo: Path) -> dict[str, object]:
    return {"goods_potentials_removed": write_goods_without_placement_rules(mod_root, vanilla_root),
            **write_actions(mod_root, vanilla_root, repo)}
